### ISSUE TITLE
Unable to call a rust method from JS with a `number` if the method argument has type `serde_json::Value`

### ISSUE THREAD

**Issue by AlCalzone** [napi-rs/napi-rs#1013]
[The docs](https://napi.rs/docs/concepts/function#arguments) imply that the rust type `serde_json::Value` corresponds to the JS/TS type `unknown`, which includes `number`. However I'm getting this runtime error when I try to call such a method with a number:
https://github.com/napi-rs/napi-rs/blob/349f747ce47218f4fcece19130e6898746a4651e/crates/napi/src/bindgen_runtime/js_values/serde.rs#L41-L44

I assume this is a deliberate decision because you don't know whether the passed number was a float or int or uint or bigint. However, it would be nice to have **any way** to specify the default behavior instead of simply erroring. Maybe a feature flag or something so we can say _"I don't care what the number in JS is, make it a float"_.

**Comment by zeroslope** [comment]
I want to try this issue

**Comment by AlCalzone** [comment]
@zeroslope something along these lines could work:
```rs
      ValueType::Number => Value::Number(
        Number::from_f64(f64::from_napi_value(env, napi_val)?)
          .expect("Failed to parse number"),
      ),
```

I originally tried to wrap the return type with my own struct. This allowed me to parse floats, but as soon as arrays were involved, this broke down too.

**Comment by zeroslope** [comment]
@AlCalzone I wrote a function in rust and called it with js. Does this replicate your usage scenario ?
``` rust
#[napi]
fn test_serde_value(a: Value) -> Result<Value> {
  Ok(a)
}
```
``` js
test('serde-json-number', (t) => {
  const res = testSerdeValue(1)
  t.is(res, 1)
})
```
![image](https://user-images.githubusercontent.com/10218146/148514489-caec151d-ff60-4db9-9a04-b17d993035c8.png)

**Comment by AlCalzone** [comment]
Yes

**Comment by zeroslope** [comment]
> @zeroslope something along these lines could work:
> 
> ```rust
>       ValueType::Number => Value::Number(
>         Number::from_f64(f64::from_napi_value(env, napi_val)?)
>           .expect("Failed to parse number"),
>       ),
> ```
> 
> I originally tried to wrap the argument type with my own struct. This allowed me to parse floats, but as soon as arrays were involved, this broke down too.

@AlCalzone I tried your solution, but it did not break down. Can you provide more examples to help me improve the test cases?

**Comment by AlCalzone** [comment]
@zeroslope my problem was that I tried to work around it in my code, without touching `napi-rs`. So I basically copied this part of the code, extended it to support `Number`:
```rs
pub struct JSONValue(serde_json::Value);

impl FromNapiValue for JSONValue {
  unsafe fn from_napi_value(env: sys::napi_env, napi_val: sys::napi_value) -> Result<Self> {
    let ty = type_of!(env, napi_val)?;
    let val = match ty {
      ValueType::Boolean => JSONValue(serde_json::Value::Bool(bool::from_napi_value(
        env, napi_val,
      )?)),
      ValueType::Number => JSONValue(serde_json::Value::Number(
        serde_json::Number::from_f64(f64::from_napi_value(env, napi_val)?)
          .expect("Failed to parse number"),
      )),
      ValueType::String => JSONValue(serde_json::Value::String(String::from_napi_value(
        env, napi_val,
      )?)),
      ValueType::Object => {
        let mut is_arr = false;
        check_status!(
          sys::napi_is_array(env, napi_val, &mut is_arr),
          "Failed to detect whether given js is an array"
        )?;

        if is_arr {
          JSONValue(serde_json::Value::Array(Vec::<serde_json::Value>::from_napi_value(
            env, napi_val,
          )?))
        } else {
          JSONValue(serde_json::Value::Object(serde_json::Map::<
            String,
            serde_json::Value,
          >::from_napi_value(
            env, napi_val
          )?))
        }
      }
      #[cfg(feature = "napi6")]
      ValueType::BigInt => todo!(),
      _ => JSONValue(serde_json::Value::Null),
    };

    Ok(val)
  }
}

impl From<JSONValue> for serde_json::Value {
    fn from(j: JSONValue) -> Self {
        j.0
    }
}
```
and used `JSONValue` as the argument type. However `napi-rs`'s internal code was still used for numbers in arrays and objects, so that threw an error.

With the change directly in `napi-rs`, I don't expect a problem with arrays.
