### ISSUE TITLE
What are default targets?

### ISSUE THREAD

**Issue by ragingwind** [napi-rs/napi-rs#1014]
Quick question: with `napi new`, `x86_64-apple-darwin, x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu` are defaults. However, `@cool/core-linux-arm64-gnu for Linux aarch64` is mentioned as default in [document](https://napi.rs/docs/introduction/getting-started)

**Comment by Brooooooklyn** [comment]
> 86_64-apple-darwin, x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu are defaults.

Yes

`@cool/core-linux-arm64-gnu` in document is just for example.
