### ISSUE TITLE
Memory leak using js callback in rust loop

### ISSUE THREAD

**Issue by harscoet** [napi-rs/napi-rs#1016]
I noticed if I use a javascript callback inside a rust loop to be able to emit a string (to simulate an event emitter), the memory seems to leak. If I emit `x` in the example (so i32) the memory is stable
I reproduced it on macOS Catalina 10.15.7 (so darwin-x64 platform)
 
I know I'm creating many strings doing this, but the GC should be able to drop some previous iterations no? Forcing GC with `global.gc()` doesn't help

```rust
#[napi]
pub fn test<T: Fn(String) -> Result<()>>(
    callback: T,
) {
  for x in 0..10000000 {
    callback(x.to_string()).unwrap();
  }
}
```
First log
```
Used 3.96 MB - Total 4.73 MB
```
Last log
```
Used 230.42 MB - Total 259.49 MB
```

Steps to run it:

I created a simple repository https://github.com/harscoet/napi-memory-leak

1. `git clone git@github.com:harscoet/napi-memory-leak.git`
2. `cd napi-memory-leak`
3. `yarn install`
4. `yarn build`
5. `node test.js`

**Comment by Brooooooklyn** [comment]
It is by design https://github.com/nodejs/node/issues/39037
