### ISSUE TITLE
Create JS function in rust

### ISSUE THREAD

**Issue by Mokshit06** [napi-rs/napi-rs#1018]
I was trying to create a NAPI module where I wanted to have a higher order function. The typescript signature would be something like
```ts
type HOF = () => (x: number, y: number) => number
```

In rust, if I were to create a higher order function, I would need to `Box` the return value, but `Box` can't be converted to a NAPI value.

Is it possible to do this in the current version of napi-rs? Could you provide an example in the documentation?

**Comment by Brooooooklyn** [comment]
https://docs.rs/napi/latest/napi/struct.Env.html#method.create_function_from_closure

**Comment by Mokshit06** [comment]
That works! Thanks :)
