### ISSUE TITLE
Type defs don't work with type alias

### ISSUE THREAD

**Issue by Mokshit06** [napi-rs/napi-rs#1019]
If I use a rust type alias in the signature of my function/struct that uses the `#[napi]` macro, it uses the name of type alias in the typescript type definitions, but doesn't include the type declaration.

## Example:
```rust
type Int = i32;

#[napi]
fn sum(x: Int, y: Int) -> Int {
    x + y
}
```

## Type defs generated:
```ts
export function sum(x: Int, y: Int): Int
```

## Expected output:
```ts
type Int = number

export function sum(x: Int, y: Int): Int
```

**Comment by Brooooooklyn** [comment]
It's working as expected. We can't perform type inferring in the `proc_macro`.
If you want to correct the type generated, you can rewrite the `arguments` types with `#[napi(ts_args_type = "x: number, y: number")]`
