### ISSUE TITLE
Number types support

### ISSUE THREAD

**Issue by mateogianolio** [napi-rs/napi-rs#1030]
I'm new to this library so forgive me for asking a possibly stupid question, but is there a rationale for only supporting automatic conversion for the number types `u32`, `i32`, `i64` and `f64`?

Is it related to the possible loss in precision?

Example:

```rust
#[napi]
fn test(x: f32) -> () {
  println!("{}", x)
}
```

...results in...

```
the trait bound `f32: NapiValue` is not satisfied
```

**Comment by Brooooooklyn** [comment]
> Is it related to the possible loss in precision?

Yes, `i64` `f64` `u32` `i32` could be obtained from Node-API https://nodejs.org/api/n-api.html#napi_get_value_double

But `f32` couldn't be obtained from Node-API.

**Comment by mateogianolio** [comment]
Thanks for the quick answer :)

The workaround was simple enough:

```rust
#[napi]
fn number_to_f32(x: f64) -> () {
  println!("{}", x as f32);
}

#[napi]
fn number_from_f32() -> f64 {
  let x: f32 = 2.5;
  x as f64
}
```
