### ISSUE TITLE
Converting a BigInt to a Rust primitive panics when passed 0

### ISSUE THREAD

**Issue by dguenther** [napi-rs/napi-rs#1053]
When passing in a BigInt with value 0 to a function like this:

```rs
#[napi]
pub fn test(bi: BigInt) -> String {
    bi.get_u64().1.to_string()
}
```

The function panics with the following error:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0',
C:\Users\derek\.cargo\registry\src\github.com-1ecc6299db9ec823\napi-2.0.3\src\bindgen_runtime\js_values\bigint.rs:82:7
```

It works as expected if the function is passed a BigInt greater than 0.

I tested this with Node v16.13.0, but haven't tried other versions. I created a demo repository here: https://github.com/dguenther/napi-rs-issue

**Comment by jose-acevedoflores** [comment]
Another data point, this works if you use:
```rust
#[napi]
pub fn test(bi: JsBigInt) -> String {
    bi.get_u64().unwrap().0.to_string()
}
```
I'm still not sure what is the difference between the preload values vs the Js ones (i.e. [BigInt](https://docs.rs/napi/2.0.3/napi/bindgen_prelude/struct.BigInt.html) vs [JsBigInt](https://docs.rs/napi/2.0.3/napi/struct.JsBigInt.html))

**Comment by dguenther** [comment]
Oh, great tip, I didn't think of that! It seems like they should use similar implementations in the code -- JsBigInt calls [sys::napi_get_value_bigint_uint64](https://github.com/napi-rs/napi-rs/blob/666118d69fd31a442f5912531709e12cb3ee636e/crates/napi/src/js_values/bigint.rs#L229), where BigInt uses [sys::napi_get_value_bigint_words](https://github.com/napi-rs/napi-rs/blob/666118d69fd31a442f5912531709e12cb3ee636e/crates/napi/src/bindgen_runtime/js_values/bigint.rs#L79) and parses the u64 from the words directly.
