### ISSUE TITLE
Error `cannot allocate memory in static TLS block` when running in `node:12-slim` or `node:14-slim` Docker

### ISSUE THREAD

**Issue by AlCalzone** [napi-rs/napi-rs#1060]
I'm getting the following error during the CI tests
**Test bindings on Linux-x64-gnu - node@12** and **Test bindings on Linux-x64-gnu - node@14**
```
/build/rsonl-db.linux-x64-gnu.node: cannot allocate memory in static TLS block

      149 | 					try {
      150 | 						if (localFileExisted) {
    > 151 | 							nativeBinding = require("./rsonl-db.linux-x64-gnu.node");
          | 							                ^
      152 | 						} else {
      153 | 							nativeBinding = require("@alcalzone/rsonl-db-linux-x64-gnu");
      154 | 						}
```
which I can reproduce when running `yarn test` locally in the corresponding Docker images.

The same works fine in all other targets, including Node.js 16 on CI and `linux-x64-gnu` w/ Node.js 12/14 locally outside Docker.

I've tried setting 
```
rustflags = ["-Z", "tls-model=global-dynamic"]
```
with the nightly compiler, but that doesn't help. I also tried `local-dynamic`, but then building fails.

Any idea what I could do to mitigate this?

**Comment by AlCalzone** [comment]
Further update: This only seems to happen when https://github.com/facebook/jest/ is involved. Requiring the module normally works... 🤷🏻‍♂️

**Comment by Brooooooklyn** [comment]
After some investigation, it seems like a bug related to `--zig`.

> This only seems to happen when https://github.com/facebook/jest/ is involved. Requiring the module normally works... 🤷🏻‍♂️

The `zig` linked program seems to crash when it was running on `worker_threads`.

You need to replace the `nodejs-rust:lts-zig` image with the `nodejs-rust:lts-debian` image like this: https://github.com/Brooooooklyn/Image/blob/main/.github/workflows/CI.yml#L47. And drop the `--zig --zig-abi-suffix` flags
