### ISSUE TITLE
Node.JS Async callback convention

### ISSUE THREAD

**Issue by Scottapotamas** [napi-rs/napi-rs#107]
Hello,

Here you prepend a null value to the arguments that you pass to the callback:

https://github.com/napi-rs/napi-rs/blob/2ff09ea26d0c2b7b5c520ff40db5ba1154e2e67e/napi/src/threadsafe_function.rs#L207-L213

I don't think this is a convention? I can't find any reference to this in the Node.JS documentation.

Would it be possible to remove this null and move that responsibility to the user if they need to have it?

I can make a PR if you prefer.

**Comment by Brooooooklyn** [comment]
> Would it be possible to remove this null and move that responsibility to the user if they need to have it?

Yes

>I can make a PR if you prefer.

That's great.

**Comment by Mike-Dax** [comment]
I also misunderstood the intention of this API, I now see that it automatically builds the arguments based on the `Result`, if it's an error, it passes that as the first argument, otherwise it passes null as the first argument.

I've made a PR to update the inline documentation to reflect that.
