### ISSUE TITLE
Argument type checking

### ISSUE THREAD

**Issue by KoHcoJlb** [napi-rs/napi-rs#1085]
Hello
Maybe T::from_raw should be used here to leverage automatic type checking when using Js* types as function arguments.

https://github.com/napi-rs/napi-rs/blob/1bee150a7aa214648f2fbcfaf3b4598b9f4193a8/crates/napi/src/bindgen_runtime/js_values.rs#L81

**Comment by KoHcoJlb** [comment]
Tried using `strict` option but it doesn't compile.
```the trait bound `napi::JsFunction: ValidateNapiValue` is not satisfied```
```rust
#[napi(strict)]
fn test(callback: JsFunction) {
}
```

**Comment by Brooooooklyn** [comment]
@KoHcoJlb You can use rust lambda:

```rust
#[napi(strict)]
fn test(callback: Fn(u32) -> u32) {
}
```
