### ISSUE TITLE
Aliases in TypeScript only alias the type, but not the value

### ISSUE THREAD

**Issue by dceddia** [napi-rs/napi-rs#1087]
I ran into an issue where I have some Rust structs annotated with an alias for the JS name, and the generated `index.d.ts` file seems to export the *type* name, but not the value.

The Rust code looks like:

```rust
#[napi(js_name = "Timestamp")]
pub struct JsTimestamp {
    value: i64,
    tb_num: u32,
    tb_den: u32,
}
// ... and some impls ...
```

And the generated `index.d.ts` has this bit:

```ts
export type JsTimestamp = Timestamp
export class Timestamp {
  constructor(value: number, tbNum: number, tbDen: number)
  // ... snip ...
}
```

And I can import it, and attempt to use it...

```ts
import { JsTimestamp, Timestamp } from '../bindings';

// This works fine, using JsTimestamp as a type:
type Segment = {
  start: JsTimestamp,
  duration: JsTimestamp
};

// This doesn't work, using it as a value:
new JsTimestamp(1, 2, 3);
// But using the "real" type works:
new Timestamp(1, 2, 3);
```

When I try to construct one of these types, TypeScript throws this error:

> 'JsTimestamp' only refers to a type, but is being used as a value here.

From searching around it sounds like `export type JsTimestamp = Timestamp` exports *only* the type itself, but not the value. Adding a second line, like `export const JsTimestamp = Timestamp`, fixes the problem by exporting both.

I put up a PR #1086 to add this extra export to the CLI, if that seems like the right way to fix this.

**Comment by Brooooooklyn** [comment]
@dceddia you shouldn't use `aliased` type. Just use the `Timestamp` in your case.

**Comment by dceddia** [comment]
Hahah, yes of course! I'm not sure what I was thinking yesterday... too stuck in Rust-land maybe. lol nevermind me 🤦‍♂️
