### ISSUE TITLE
文档里面没用写如何在一个简单包里面添加新的版本比如 添加linux-x64-gnu

### ISSUE THREAD

**Issue by ChinaMars521** [napi-rs/napi-rs#1102]
文档里面没用写如何在一个简单包里面添加新的版本比如 添加linux-x64-gnu

**Comment by Brooooooklyn** [comment]
不推荐从零开始添加 infra，除非你有经验能搞清楚这些脚本是干嘛的，以及交叉编译的各种细节。推荐从 cli 或者 package-template 上手

**Comment by ChinaMars521** [comment]
我要使用package-template  就要手动兼容所有版本，我只想弄我的版本，这件事很苦恼

**Comment by Brooooooklyn** [comment]
你可以用 cli 新建项目，在选在需要兼容的系统里面勾选你想要的

**Comment by ChinaMars521** [comment]
我就是勾选的只有cli里面会添加，而且上传的时候不会自动修改他的版本

**Comment by ChinaMars521** [comment]
现在我的上传能手动上传上 cil 也会编译 在push 的流程中不会把我玩新建的版本上传上去

**Comment by ChinaMars521** [comment]
napi prepublish -t npm 我查看这个配置也没有

**Comment by Brooooooklyn** [comment]
https://napi.rs/docs/cli/pre-publish

**Comment by ChinaMars521** [comment]
在yarn artifacts 流程中就不会移动这个新增的。node 文件

**Comment by ChinaMars521** [comment]
在下载的流程会下载

**Comment by ChinaMars521** [comment]
你给我发的url 404

**Comment by Brooooooklyn** [comment]
请提供一下:

1. 预期行为
2. 错误信息
3. 重现步骤
4. 最小复现仓库

请不要把 GitHub issues 当版聊，请尽量一次性提供完整信息。否则我无法处理你描述的问题。

**Comment by ChinaMars521** [comment]
我使用napi new 新建了一个默认编写代码，在上传的时候正常，这个时候我新建了一个文件夹重新napi new 添加了一个64-linux-musl 把我新修改的代码上传了上去 执行npm version patch 发现新增的系统没有增加版本，我手动修改了版本重新 npm version patch的时候 编译流程一切正常在cil 上传的时候发现他并没有提交到我的npm 库 在yarn artifacts 流程中没有移动我的.node 文件
在下载流程中是正常下载的，我的最小库https://github.com/ChinaMars521/wtapi 您可以查看我的编译流程！

**Comment by ChinaMars521** [comment]
补充 他并没有出现在我的版本里面

**Comment by ChinaMars521** [comment]
补充：在@napi-rs/cli 发现他是定死的，我只能魔改这个文件来达到我的需求
