### ISSUE TITLE
Feature request: support function reference

### ISSUE THREAD

**Issue by oyyd** [napi-rs/napi-rs#1138]
node-addon-api support [FunctionReference](https://github.com/nodejs/node-addon-api/blob/main/doc/function_reference.md) in order to keep a Function valid when it get called compared to a common Function(or JsFunction in napi-rs).

My scene is that my struct will store a JsFunction: 

``` rust
#[napi]
struct DgramSocket {
  recv_cb: napi::JsFunction,
}
```

And the JsFunction will be called from a callback of callback `uv_poll`:
```rust
extern "C" fn on_event(handle: *mut sys::uv_poll_t, status: i32, events: i32) {
  // Firstly, open a handle scope manually
  // Then get DgramSocket from handle and call `recv_cb`
  socket.recv_cb.call(None, &args).unwrap();
}
```
`socket.recv_cb.call()` will return a error like:

```
{ status: InvalidArg, reason: "" }
```

According to https://github.com/nodejs/node-addon-api/issues/172#issuecomment-341515178, looks like this is because the common JsFunction is invalidated in the callback. Using a FunctionReference here should solve the problem.

I also notice that in https://github.com/napi-rs/napi-rs/issues/646 :
> No, you can't do this because JsObject can only be used in the Main thread. 

But I think these two scenes are different. I don't expect a FunctionReference to be use across different threads.

**Comment by oyyd** [comment]
I tried to add a `into_ref()` like the one for `JsBuffer` but I still got an InvalidArg error when calling `JsFunction`. Need some more investigation.

**Comment by oyyd** [comment]
Finally, I think I understand why I still got `InvalidArg` after wrapping a `JsFunction` in `Ref`. 

It's because `napi_value` (that is a raw pointer) referenced by `napi_create_reference`  could become invalid after some delay(or async operations) and programs should alway get referenced `napi_value` from `napi_ref` with `napi_get_reference_value` like how it's done in `node-addon-api` https://github.com/nodejs/node-addon-api/blob/24455f88af13d577177765070ea35cbf53dc1af5/napi-inl.h#L2963

## Example of my scene
Take `JsObject` for an example, the code below doesn't work as expected:

```rs
#![deny(clippy::all)]

#[macro_use]
extern crate napi_derive;

use napi::{Env, JsObject, Result, Ref, JsString, CallContext};

#[repr(C)]
struct TestS (JsObject); // a struct that store some js values

#[js_function(0)]
fn return_wrapped_obj(ctx: CallContext) -> Result<JsObject> {
  let env = ctx.env;

  // create a js object and return it to js world
  let mut obj = env.create_object()?;

  // encoded_obj will be cached in a TestS and get used later
  let mut encoded_obj = env.create_object()?;
  encoded_obj.set_property(env.create_string("key")?, env.create_string("value")?)?;

  env.wrap(&mut obj, TestS (encoded_obj))?;
  Ok(obj)
}

#[js_function(1)]
fn get_val_from_wrapped_obj(ctx: CallContext) -> Result<JsString> {
  let obj = ctx.get::<JsObject>(0)?;
  let env = ctx.env;

  let test_s = env.unwrap::<TestS>(&obj)?;
  let value: JsString = test_s.0.get_property(env.create_string("key")?)?;
  Ok(value)
}

#[module_exports]
fn init(mut exports: JsObject, env: Env) -> Result<()> {
  exports.create_named_method("returnWrappedObj", return_wrapped_obj)?;
  exports.create_named_method("getValFromWrappedObj", get_val_from_wrapped_obj)?;
  Ok(())
}
```

```js
const mod = require('./index')

const obj = mod.returnWrappedObj()

setTimeout(() => {
  console.log(mod.getValFromWrappedObj(obj)) // expect to get the wrapped string inside the object of TestS
}, 10)
```

We will got errors like:

```
Error: expect String, got: Undefined
```

## Trying to use Ref

Adding a `into_ref`  in `JsObject` tries to keep the `JsObject` live longer:

```rs
#[cfg(feature = "napi5")]
impl JsObject {
  // ignore other code..
  pub fn into_ref(self) -> Result<Ref<Self>> {
    Ref::new(self.0, 1, self)
  }
}
```

(Also modifying the example:)

```rs
#![deny(clippy::all)]

#[macro_use]
extern crate napi_derive;

use napi::{Env, JsObject, Result, Ref, JsString, CallContext};

#[repr(C)]
struct TestS (Ref<JsObject>); // NOTE: this time use a Ref<JsObject> instead 

#[js_function(0)]
fn return_wrapped_obj(ctx: CallContext) -> Result<JsObject> {
  let env = ctx.env;

  let mut obj = env.create_object()?;

  let mut encoded_obj = env.create_object()?;
  encoded_obj.set_property(env.create_string("key")?, env.create_string("value")?)?;

  env.wrap(&mut obj, TestS (encoded_obj.into_ref()?))?; // NOTE: cache a Ref<JsObject>
  Ok(obj)
}

#[js_function(1)]
fn get_val_from_wrapped_obj(ctx: CallContext) -> Result<JsString> {
  let obj = ctx.get::<JsObject>(0)?;
  let env = ctx.env;

  let test_s = env.unwrap::<TestS>(&obj)?;
  let value: JsString = test_s.0.get_property(env.create_string("key")?)?;
  Ok(value)
}

#[module_exports]
fn init(mut exports: JsObject, env: Env) -> Result<()> {
  exports.create_named_method("returnWrappedObj", return_wrapped_obj)?;
  exports.create_named_method("getValFromWrappedObj", get_val_from_wrapped_obj)?;
  Ok(())
}
```

We still get errors:
```
Error: expect String, got: Undefined
```

## Creating new `JsObject` with `napi_get_reference_value`

Impl `value` (which create a new `JsObject` from the `napi_value` by `napi_get_reference_value` ) for `Ref<JsObject>`

```rs
impl Ref<JsObject> {
  pub fn value(&self, env: &Env) -> Result<JsObject> {
    let mut result = ptr::null_mut();
    unsafe { sys::napi_get_reference_value(env.0, self.raw_ref, &mut result) };

    let val = unsafe {
      JsObject::from_raw(env.0, result)
    }?;

    Ok(val)
  }
}
```

Modify the code accordingly:

```rs
// ignore other code 
#[js_function(1)]
fn get_val_from_wrapped_obj(ctx: CallContext) -> Result<JsString> {
  let obj = ctx.get::<JsObject>(0)?;
  let env = ctx.env;

  let test_s = env.unwrap::<TestS>(&obj)?;
  let value: JsString = test_s.0.value(env)?.get_property(env.create_string("key")?)?; // NOTE: use the JsObject created by value()
  Ok(value)
}
```

This time we succeed and the string logged:

```
value
```

This should also apply to `JsFunction`. I wish the document of node api describes this more clearly If I understand correctly.

**Comment by Brooooooklyn** [comment]
> It's because napi_value (that is a raw pointer) referenced by napi_create_reference could become invalid after some delay(or async operations) and programs should alway get referenced napi_value from napi_ref with napi_get_reference_value like how it's done in node-addon-api https://github.com/nodejs/node-addon-api/blob/24455f88af13d577177765070ea35cbf53dc1af5/napi-inl.h#L2963

Yes, I have run into this issue before.

**Comment by oyyd** [comment]
@Brooooooklyn I suggest adding a new api to get js values from `Ref`, and adding `into_ref()` for both `JsFunction` and `JsObject`, consider that node-addon-api have `FunctionReference` and `ObjectReference`. 

How do you think about it? I would like to propose a PR it if you don't have time to do it :)

**Comment by Brooooooklyn** [comment]
@oyyd I'm looking into this now 😁

**Comment by Brooooooklyn** [comment]
I'll support this feature in https://github.com/napi-rs/napi-rs/pull/1156

**Comment by oyyd** [comment]
> I suggest adding a new api to get js values from Ref, and adding into_ref() for both JsFunction and JsObject

Just noticed that we could create a reference by `Env::create_reference`. So that this feature request is not actually urgent. (I was focusing on fns of `Ref`, sorry for the bother.)
