### ISSUE TITLE
Github Action CI Error

### ISSUE THREAD

**Issue by Dominionys** [napi-rs/napi-rs#1139]
I'm using napi-rs with github actions, but recently [stable - aarch64-unknown-linux-gnu - node@16](https://github.com/Dominionys/depcheck-rs/runs/6067739110?check_suite_focus=true#logs) and [stable - x86_64-unknown-linux-gnu - node@16](https://github.com/Dominionys/depcheck-rs/runs/6067738887?check_suite_focus=true#logs) started emitting errors: 

```
Error relocating /usr/lib/libLLVM-13.so: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/bin/llvm-strip: _ZSt28__throw_bad_array_new_lengthv: symbol not found
```
How can I fix it?
Thank you for your work!

**Comment by Brooooooklyn** [comment]
@Dominionys hey re-run  your pipeline, it should be fixed in https://github.com/napi-rs/napi-rs/actions/runs/2187005623

**Comment by Dominionys** [comment]
Yes, 
Thank you.
