### ISSUE TITLE
Windows 32bit (i686) crash under Electron

### ISSUE THREAD

**Issue by Hinton** [napi-rs/napi-rs#1145]
Hi,

We've run into a slightly weird issue where our electron application crashes immediately under 32 bit windows (tested on Windows 7 and 10). Running the same application on x64 W7 and W10/W11 works as expected.

The error started to occur after enabling the `async` feature. Without it it seems to run fine as long as the `--release` compiler flag is not turned on. With the `--release` flag it crashes even without async.

In the Event viewer I got the following fairly cryptic error.
```
Faulting application name: electron-quick-start.exe, version: 1.0.0.0, time stamp: 0x62609421
Faulting module name: KERNELBASE.dll, version: 10.0.22000.613, time stamp: 0xb8da8cf0
Exception code: 0xc06d007e
Fault offset: 0x0013ed42
Faulting process ID: 0x46ac
Faulting application start time: 0x01d858b29aa5e734
Faulting application path: >reducted>\dist\win-ia32-unpacked\electron-quick-start.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 1c4213ea-1876-47ae-903e-4992c4d25598
Faulting package full name: 
Faulting package-relative application ID: 
```

To aid with reproduceability, I've created a sample application using a lightweight boilerplate Electron app + the boilerplate Napi-rs template. The only change to the napi boilerplate is adding the `async`. The code is available at https://github.com/Hinton/electron-napi-crash.

The steps to reproduce the issue are:
```
git clone https://github.com/Hinton/electron-napi-crash.git
cd electron-napi-crash

# Build napi binary
cd native
npm ci
npm run build:i686
cd ..

# Build electron app
npm ci
npm run dist
```

Attempting to launch `dist/win-ia32-unpacked/electron-quick-start.exe` causes an immediate crash, with the above error in the Event Viewer.

Building and running under x64 works as expected. Additionally running the napi module under `node` directly seems to also work fine with the 32bit build of node.js.

Let me know if I can provide any further information.

**Comment by Hinton** [comment]
Running the application using Visual Studio debugger leads to the following additional information:

```
Exception thrown at 0x7C82478A (eeb10752-bb23-4788-9c91-d9b7e447303c.tmp.node) in electron-quick-start.exe: 0xC0000005: Access violation reading location 0xFFFFFFFF.
```

With the following call stack

```
>	eeb10752-bb23-4788-9c91-d9b7e447303c.tmp.node!core::core_arch::x86::sse2::_mm_load_si128(core::core_arch::x86::__m128i * mem_addr) Line 1182	Unknown
 	eeb10752-bb23-4788-9c91-d9b7e447303c.tmp.node!hashbrown::raw::sse2::Group::load_aligned() Line 60	Unknown
 	eeb10752-bb23-4788-9c91-d9b7e447303c.tmp.node!hashbrown::raw::RawIterRange<tuple$<alloc::string::String,tuple$<>>>::new<tuple$<alloc::string::String,tuple$<>>>(hashbrown::raw::Bucket<tuple$<alloc::string::String,tuple$<>>> ctrl, unsigned int data) Line 1862	Unknown
 	eeb10752-bb23-4788-9c91-d9b7e447303c.tmp.node!hashbrown::raw::RawTable<tuple$<alloc::string::String,tuple$<>>,alloc::alloc::Global>::iter<tuple$<alloc::string::String,tuple$<>>,alloc::alloc::Global>() Line 946	Unknown
```

**Comment by Brooooooklyn** [comment]
Related: https://github.com/napi-rs/napi-rs/issues/297

**Comment by Hinton** [comment]
@Brooooooklyn Seems related, but it also occurs when compiling without `--release`.

**Comment by Brooooooklyn** [comment]
Close in https://github.com/napi-rs/napi-rs/pull/1167
