### ISSUE TITLE
Per parameter type override for functions

### ISSUE THREAD

**Issue by Xaeroxe** [napi-rs/napi-rs#1160]
For `napi` functions we have `ts_args_type` right now, which is great. What I'd really like to be able to do though is use attributes for function parameters to override the type of individual arguments. Something like

```rust
#[napi]
fn call_threadsafe_function(
    id: u32,
    #[napi(ts_type="(err: null | Error, result: number) => void")]
    callback: JsFunction
) -> Result<()> {
```

[Per argument attributes are supported by the Rust language.](https://doc.rust-lang.org/reference/items/functions.html) This feature would enable us to only override types that need to be overridden, and otherwise automatically generate the function signature.

**Comment by Brooooooklyn** [comment]
Close in https://github.com/napi-rs/napi-rs/pull/1192
