### ISSUE TITLE
Feature request: add custom target-dir support

### ISSUE THREAD

**Issue by 0xDing** [napi-rs/napi-rs#1170]
Cargo can override the default target dir location by setting target-dir in config.toml, while napi-cli assumes that target-dir is ` . /target ` which leads to a `Type Error: No target dir found error.`

P.s. It makes sense to change the target dir in a large monorepo that contains both Typescript and Rust code

ref: https://github.com/napi-rs/napi-rs/blob/79d7453713edc26bb283f1b63c5314a06163f323/cli/src/build.ts#L517

Thanks

**Comment by Brooooooklyn** [comment]
Closed in https://github.com/napi-rs/napi-rs/pull/1492
