### ISSUE TITLE
issues with `--pipe` option

### ISSUE THREAD

**Issue by kyranet** [napi-rs/napi-rs#1188]
I'm defining the following script in package.json, and with generated files being deleted:

```json
{
	"scripts": {
		"build": "napi build --platform --release --js index.cjs --pipe \"prettier -w\""
	}
}
```

And when running `yarn build`, prettier will fail to format `index.d.ts`, resulting on an unformatted file, but the JS output is fine:

![image](https://user-images.githubusercontent.com/24852502/168495887-066a123e-b68a-42ae-b93a-86530884f355.png)

Running it again will result on Prettier to format the file correctly... often. ~~I haven't been able to reproduce it again, but it once formatted the file and then overwrote with the unformatted code, so this might be caused by a race-condition?~~ Turns out, the built code is written *always* after the piped command finishes writing, which causes the command to output unformatted code. This can be reproduced by modifying the source code or deleting target to force a re-build.

---

Something interesting I found. If I delete both generated files, and then I run `yarn build`, the files won't auto-regenerate, and will still call the script, this causes the script to fail as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/24852502/168495813-256aaacb-8c28-48cb-afb2-ae5f9ab7e8fa.png)

## Additional information

- `OS`: Windows 11 Pro (Version 21H2, OS Build 22000.675).
- `Rustc`: 1.60.0 (7737e0b5c 2022-04-04)
- `Node.js`: 18.1.0
- `@napi-rs/cli`: 2.9.0
- `prettier`: 2.6.2

**Comment by Nytelife26** [comment]
This works for me on Ubuntu. Although, I should note that it seems unusual to have a `--pipe` option at all, and my recommendation would be to remove it altogether in favour of standard operating system pipes if possible - or, if not, at least have the command output the generated filenames so a script can be formed around it.

**Comment by Brooooooklyn** [comment]
Closed in https://github.com/napi-rs/napi-rs/pull/1492
