### ISSUE TITLE
feat: `JsMap` to represent a `Map` is missing

### ISSUE THREAD

**Issue by Hywan** [napi-rs/napi-rs#1215]
Hi,

A `HashMap` is converted into an `Object` on the JS side. However, it works only if the keys are strings. However, JavaScript has a [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) object, where keys and values can be of any types (or kind of). That could be extremely useful to represent more exotic `HashMap` or `BTreeMap`.

**Comment by Brooooooklyn** [comment]
Unfortunately, there is no JavaScript `Map` API provided by the [Node-API](https://nodejs.org/docs/latest/api/n-api.html)

**Comment by Hywan** [comment]
Oh, yeah, of course… I'll close this PR then :-).
