### ISSUE TITLE
NAPI doesn't check for types received by a function

### ISSUE THREAD

**Issue by Hywan** [napi-rs/napi-rs#1218]
Hello,

Let's imagine we have the following code:

```rust
#[napi]
pub struct Foo { … }

#[napi]
pub struct Bar { … }

#[napi]
pub fn baz(foo: &Foo) -> … { … }
```

In JavaScript, both following execution will be accepted:

```javascript
baz(new Foo(…))
baz(new Bar(…))
```

Of course, in the second case, `baz` —on the Rust side— will receive a totally corrupted value. That's extremely dangerous, it's even an Undefined Behavior. I'm confused that `napi-rs` doesn't check the type, at least the type name. I know JavaScript is very dynamic but still, it's possible to retrieve the type name somehow (not reliably, but still).

**Comment by Brooooooklyn** [comment]
If you want to check the parameter types, you can use `strict` attr on `#[napi]`, for example: 

```rust
#[napi(strict)]
pub fn baz(foo: &Foo) -> … { … }
```

But, there are some issues while strictly checking the `Class` instance, it will be fixed in  https://github.com/napi-rs/napi-rs/pull/1200

**Comment by Hywan** [comment]
`#[napi(strict)]` doesn't seem to work with argument of type `Option<String>` for example. Is it the expected behavior?

**Comment by Brooooooklyn** [comment]
> `#[napi(strict)]` doesn't seem to work with arguments of type, like, `Option<String>`. Is it the expected behavior?

No, I'll fix it
