### ISSUE TITLE
`.d.ts` not regenerated on `napi build`

### ISSUE THREAD

**Issue by probablykasper** [napi-rs/napi-rs#1249]
It looks like if you delete the `.d.ts` file, it won't be regenerated when you run `napi build` again.

### Reproduction

1. Run `napi build`
2. Delete the generated `.d.ts` file
3. Run `napi build`

**Comment by Brooooooklyn** [comment]
It's because the rust project is not rebuilt, try `touch src/lib.rs` and build again

**Comment by probablykasper** [comment]
Isn't there a way to fix this by always regenerating it at the end of the `napi build` command?

**Comment by Brooooooklyn** [comment]
No, we can't do this at present as the type metadata will be deleted after `.d.ts` file is generated

**Comment by probablykasper** [comment]
Oh well, that's unfortunate

**Comment by JSerFeng** [comment]
Maybe we could record type info in the previous compilation, and just add missing types in the current compilation, happy to make a pr for that

**Comment by JSerFeng** [comment]
We can get crate and ts type_def in that crate, and use that to cache some type_def information.
If we rebuild without actual compiling we can get ts type from cache.

The only problem here is that I can not tell if some crates are not rebuild this time and should get from cache, OR the napi derive struct in that crate is deleted, and we cannot get type from cache.

If only I can  find a better way to get what crates are rebuilt this time.

1. Use --timings flag, and we can get all dirty units, but that will cause a bit bad perf in dev
2. Use stdout info, like `Compiling foo v0.0.1` we can known foo has been rebuilt, but will fail if set --quiet

Both are not elegant.

**Comment by JSerFeng** [comment]
It's a hack though, but is important to some scenario.
Assuming I want develop a pluggable system, I certainly want to use cargo workspace, and napi-rs is very convenient, I use napi-rs every plugin crate, and expose binding crate for my user.

Each time I develop a plugin crate, I will have to rebuilt the whole workspace just for d.ts correctness, bad DX.
Or I maintain d.ts myself each package, that's not a good way either
