### ISSUE TITLE
use block_on with  tokio::runtime::Runtime::new() ,  Promise never callback , how to resolve this ?

### ISSUE THREAD

**Issue by usrtax** [napi-rs/napi-rs#1268]
as title , see image below

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/110233389/184540956-ff6e924e-12a2-49ca-b9e5-f713a16603df.png">

code is there https://github.com/iuser-dev/i18n-db/blob/main/src/i18n.rs

**Comment by i-user-link** [comment]
I also try use async fn , but get this error 

> `*mut napi_value__` cannot be shared between threads safely

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/110233389/184566321-5a88f3d8-6534-4661-b1c2-005378549b3e.png">

**Comment by i-user-link** [comment]
要是异步函数能支持传入函数作为参数就方便了
