### ISSUE TITLE
Build fails if the cargo package is in a workspace

### ISSUE THREAD

**Issue by Azorlogh** [napi-rs/napi-rs#128]
If you try to call the build script from a cargo package that is inside a [cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html), the script will look for the target directory in the directory of the package

However, building a package in a workspace produces a target directory that is at the level of the cargo workspace, so the build will fail with a "ENOENT: no such file or directory" error.

**Comment by Brooooooklyn** [comment]
See https://github.com/napi-rs/node-rs for example

**Comment by kyle-mccarthy** [comment]
@Brooooooklyn could you expand on the example that you referenced? Does it require for Lerna to be used?

**Comment by Brooooooklyn** [comment]
You can build without lerna using the —cwd flag of yarn: `yarn —cwd packages/subpkg build`
