### ISSUE TITLE
d.ts codegen is wrong in cargo workspace incremental compilation

### ISSUE THREAD

**Issue by JSerFeng** [napi-rs/napi-rs#1297]
# Minimal reproduce repo: [here](https://github.com/JSerFeng/napi-rs-issue)
Reproduce:

```
pnpm install

pnpm run build
```

Now index.d.ts is expected.

Then we just modify crates/core, like add a blank line anywhere, then run build again. crate core will be recompiled by Cargo, crate plugin will not which is expected.

New generated index.d.ts won't have any type info that related to crates/plugin.

dts gen rely on proc macro expansion, and incremental compilation won't do proc macro expansion

**Comment by Brooooooklyn** [comment]
duplicated https://github.com/napi-rs/napi-rs/issues/1249

**Comment by JSerFeng** [comment]
We can get crate and ts type_def in that crate, and use that to cache some type_def information.
If we rebuild without actual compiling we can get ts type from cache.

The only problem here is that I can not tell if some crates are not rebuild this time and should get from cache, OR the napi derive struct in that crate is deleted, and we cannot get type from cache.

If only I can find a better way to get what crates are rebuilt this time.

Use --timings flag, and we can get all dirty units, but that will cause a bit bad perf in dev
Use stdout info, like Compiling foo v0.0.1 we can known foo has been rebuilt, but will fail if set --quiet
Both are not elegant.

**Comment by JSerFeng** [comment]
It's a hack though, but is important to some scenario.
Assuming I want develop a pluggable system, I certainly want to use cargo workspace, and napi-rs is very convenient, I use napi-rs every plugin crate, and expose binding crate for my user.

Each time I develop a plugin crate, I will have to rebuilt the whole workspace just for d.ts correctness, bad DX.
Or I maintain d.ts myself each package, that's not a good way either
