### ISSUE TITLE
General purpose Promise/Deferred

### ISSUE THREAD

**Issue by devongovett** [napi-rs/napi-rs#1304]
Currently, the Promise support is pretty tied to tokio. I think it would be useful to have a Promise primitive that wasn't tied to any specific runtime. Basically a threadsafe function, combined with a deferred.

In my case, I'm using `rayon::spawn` to run a task in the background. I had to recreate some of the logic used for tokio support in napi-rs to do this. [Here's the code](https://github.com/parcel-bundler/lightningcss/blob/b769f7a0c934887e8d02cb533010f4b1f60fab75/node/src/lib.rs#L354-L442).

I was thinking napi-rs could have an object like `JsDeferred`, and the above could be implemented like this (pseudo code):

```rust
fn run_bundle_task(...) -> napi::Result<JsUnknown> {
  let deferred = env.create_deferred()?;
  rayon::spawn(move || {
    // ...
   deferred.resolve(...); // or reject
  });

  Ok(deferred.promise())
}
```

Internally, it would use a threadsafe function like in my implementation so that resolve/reject could be called from any background thread.

If this sounds useful, I'm happy to implement it and send a PR!

**Comment by Brooooooklyn** [comment]
It looks great!
