### ISSUE TITLE
support auto encode string to Uint8Array

### ISSUE THREAD

**Issue by usrtax** [napi-rs/napi-rs#1310]
now is use Uint8Array as arguments, string need TextEncoder encode

maybe support auto encode string to Uint8Array is easy for use

or add new type , for example `Uint8ArrayOrString`

**Comment by Brooooooklyn** [comment]
There is no `TextEncoder` API in Node-API

**Comment by usrtax** [comment]
不一定要用 TextEncoder 啊，utf8编码可以用rust的string来搞？

**Comment by Brooooooklyn** [comment]
没懂你的意思，现在的实现 JavaScript 的 String 不管是什么编码如果 Rust 这边接收的是 `String` 就是使用 https://nodejs.org/api/n-api.html#napi_get_value_string_utf8 API 获取内容转换到 Rust String

**Comment by usrtax** [comment]
@Brooooooklyn 我提交了一个pull request，
我的场景是这样的，我封装一个redis客户的给nodejs用，redis的key可以是字符串也可以是二进制

也就是可以 redis.get('1') 或者 redis.get(Buffer.from(hash))
有这个自动转换会方便很多

**Comment by usrtax** [comment]
@Brooooooklyn 在使用这个技巧之后，对于String和Uint8Array都可以，但是传入Buffer就报错

有办法修复吗？我没搞明白应该怎么修复

代码见 https://github.com/user-tax-dev/redis/tree/main/src

错误如下图

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110233389/190872623-2d42549d-ed27-480c-bb4c-2d326259398f.png">

```

thread 'tokio-runtime-worker' panicked at 'assertion failed: mid <= self.len()', /Users/z/user/napi-rs/crates/napi/src/bindgen_runtime/js_values/arraybuffer.rs:386:1
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: tokio::runtime::task::core::CoreStage<T>::poll
   4: tokio::runtime::task::raw::poll
   5: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   6: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by usrtax** [comment]
报错我搞定了，

pub type StringUint8Array = Either<String, Uint8Array>;
改成
pub type StringUint8Array = Either<String, Buffer>;

就都可以了，诡异的问题，先不管了
