### ISSUE TITLE
Threadsafe this context lost on call

### ISSUE THREAD

**Issue by Kruptein** [napi-rs/napi-rs#132]
Hi, I discovered your repo today, and was delighted how quickly I had a very basic function call working with `callback.call(Some(js_this), &[js_string, js_num]);`

Then I wanted to move on to testing the threadsafe functions using `ToJs`, but got a bit stuck.
I'm under the impression that the call_js_cb in threadsafe_function.rs, will always use 'undefined' as the value for the `recv` arg in the napi_call_function.  Which I need to be the correct context or my js function won't have the proper this context.

Any ideas/suggestions?

**Comment by Brooooooklyn** [comment]
It's not possible get `this` on thread safe callback see: https://nodejs.org/api/n-api.html#n_api_napi_threadsafe_function_call_js

You can use class property and arrow function to store the `this` in JavaScript side

**Comment by Kruptein** [comment]
Thanks for the quick reaction, apparently I was just doing something stupid in the js side of things. It all works now cheers!
