### ISSUE TITLE
Add support for Slice/TypedArray conversion

### ISSUE THREAD

**Issue by shachlanAmazon** [napi-rs/napi-rs#1344]
It would be very helpful if Uint8Array (which is a view over a buffer) could be cast to &[u8], and same for the other typed arrays.
I'm willing to implement this, if I can get guidance on where to start.

**Comment by Brooooooklyn** [comment]
`Uint8Array` could be `Deref` as `[u8]`

**Comment by shachlanAmazon** [comment]
@Brooooooklyn I'm talking about the whole package - given a 
```rust
#[napi]
fn foo(slice: &[u8]) { ... }
```
having the `#[napi]` macro automatically create the correct Typescript bindings and extract the argument in the generated `__napi__foo` function. Is this possible?

**Comment by Brooooooklyn** [comment]
@shachlanAmazon it's not possible. Because the framework doesn't know which type of data you are passing, it could be  `Buffer/Uint8Array`.
