### ISSUE TITLE
Cannot allocate Buffer into Chromium v8.

### ISSUE THREAD

**Issue by hallahan** [napi-rs/napi-rs#1346]
I have a function like so:

```rs
  pub async fn tile(&self, z: u8, x: u32, y: u32) -> Result<Buffer> {
    tokio::task::spawn(async move { 
      let t = Tile::from_zxy(z, x, y);
      let buf = tile_info(t).into();
      Ok(buf)
    }).await.unwrap()
  }
```

However, whenever I call it from an Electron app, with sandboxing turned off, I still get the following error:

```
[31872:1015/170858.344491:ERROR:node_bindings.cc(146)] Fatal error in V8: v8_ArrayBuffer_NewBackingStore When the V8 Sandbox is enabled, ArrayBuffer backing stores must be allocated inside the sandbox address space. Please use an appropriate ArrayBuffer::Allocator to allocate these buffers.
```

I want to essentially have a `Vec<u8` / `Uint8Array` of data created in a tokio task, and I want to access that data in NodeJS. Am I doing this wrong, or is there a bug here?

Is there a way to tell v8 to allocate a buffer, and do it from within a tokio task?

**Comment by hallahan** [comment]
Under the hood, any buffer sent over to Node should be transferred to v8, which should manage a reference and garbage collection.

What is the recommended pattern to follow to create buffers in Rust and pass a reference over to V8 without any copy?

I think this is a very common use case. I'm happy to PR to napi.rs docs an example once I figure this out.

PS - Rust noob here.

**Comment by Brooooooklyn** [comment]
See https://github.com/nodejs/abi-stable-node/issues/441, electron 21 doesn't allow to use zero-copy API anymore.

**Comment by hallahan** [comment]
Thank you for the clarification. Electron's security paranoia is going to drive away developers that care about performance.

I guess I will have to stick with v20.

**Comment by hallahan** [comment]
Would it be helpful if I added this info to the napi-rs docs? Allocating a Buffer or TypedArray is an important use case, as this is the most performant way to expose data to v8. Electron apps are very common these days, so it is likely someone else will run into this.

Note, **creating Buffers and Uint8Arrays is working fine when I downgrade electron to 20.3.2.**

I don't understand why the Electron project emphasizes sandboxing, with no consideration that it may be prohibitive to force the developer to copy large amounts of data, as well as require transferring data across processes unnecessarily.

For example, if someone were to build a desktop application using Qt or Cocoa, there would be no requirement or suggestion to sandbox a back-end. The fact that Electron provides JavaScript execution doesn't change anything from a security standpoint?

**Comment by nashaofu** [comment]
same issue：https://github.com/nashaofu/napi-rs-issue

**Comment by hallahan** [comment]
How does napi-rs allocate other things like standard JavaScript arrays?

**Comment by nashaofu** [comment]
This is my solution: https://github.com/nashaofu/node-screenshots/blob/master/src/lib.rs#L106
```rust
  #[napi]
  pub fn capture_sync(&self, env: Env) -> Option<JsBuffer> {
    let image = self.screen.capture()?;
    let buffer = env.create_buffer_copy(image.buffer()).ok()?;
    Some(buffer.into_raw())
  }
```

**Comment by hallahan** [comment]
Note that you're doing an extra allocation and copy.

I pinned Electron to 20.3.2 which is before they became overly paranoid.

I'm just going to stick with that version and eventually move away from Electron.

**Comment by yisibl** [comment]
## About V8 memory cage
@Brooooooklyn [Sharp v0.31.3 recently added a solution for memory cage.](https://github.com/lovell/sharp/issues/3384#issuecomment-1351737836) will napi-rs consider adding a similar solution?

**Comment by Brooooooklyn** [comment]
See https://github.com/Brooooooklyn/snappy/pull/97
