### ISSUE TITLE
Cannot pass callback to async function

### ISSUE THREAD

**Issue by Grandnainconnu** [napi-rs/napi-rs#1353]
I am trying to implement a socket TCP server with tokio and communicate with node directly.

```
#[napi]
pub async fn listen<T: Fn(&Connection) -> Result<()>>(
  host: Option<String>,
  port: Option<i32>,
  callback: T,
) -> Result<()> {...}
```

But this is not possible, is there a workaround ?

Thank's in advance !

**Comment by Brooooooklyn** [comment]
It's a limitation of NAPI-RS api, I'm improving it with new `ThreadsafeFunction` API
