### ISSUE TITLE
How to accept a union or unknown type in the async function?

### ISSUE THREAD

**Issue by romeerez** [napi-rs/napi-rs#1370]
I'm trying to get an array of numbers or strings `(string | number)[]` into the async function, but that would require a `Box<dyn ...>` which cannot be used as a parameter of async fn.

`unknown[]` would be okay too, but `napi::JsUnknown` type also doesn't implement `Send` trait.

The async function will perform a database query with tokio-postgres, and I'm trying to get query params from JS side.

Is there some way, or workaround?

**Comment by Brooooooklyn** [comment]
`Either<String, u32>` is for this scenario

**Comment by romeerez** [comment]
Thank you, that works nicely!
