### ISSUE TITLE
Debian docker image now requires GLIBC 2.35

### ISSUE THREAD

**Issue by devongovett** [napi-rs/napi-rs#1375]
After our last release, we've received some reports that lightningcss and parcel won't load anymore on ARM systems (or docker containers) with Ubuntu 20.04 LTS (e.g. https://github.com/parcel-bundler/lightningcss/issues/335). I think this is because of this commit in the base docker image https://github.com/messense/manylinux-cross/commit/76f103138b2c65450b1d181318004203ef760ad5, where Ubuntu was upgrade to 22.04. When loading a binary that is compiled using this image, an error occurs if using an older version of Ubuntu/GLIBC.

For now I've pinned us to an older version of the docker image: https://github.com/parcel-bundler/lightningcss/pull/342.

Should the base image be pinned to a specific version so that the Ubuntu version doesn't change without warning? Ideally LTS versions would continue to be supported by default for binaries compiled using napi-rs images.

**Comment by yisibl** [comment]
I guess it's settled here: https://github.com/napi-rs/napi-rs/pull/1384

**Comment by AlCalzone** [comment]
The same happens for the `nodejs:aarch64-${{ matrix.node }}` and `nodejs:armhf-${{ matrix.node }}` images. Both fail due to missing GLIBC 2.33.

@devongovett can you describe how you figured out which container version worked for you?

**Comment by devongovett** [comment]
If you look in an old GitHub actions run that passed, it'll print out the container it's running.

**Comment by AlCalzone** [comment]
Unfortunately this is a new project, where I've yet to produce a passing build.

**Comment by AlCalzone** [comment]
Looks like I had an outdated version of the `napi-rs` cli. After recreating the project boilerplate including `CI.yml`, the builds are working now.
