### ISSUE TITLE
Pass closure for Property setter/getter

### ISSUE THREAD

**Issue by MarkusJx** [napi-rs/napi-rs#1378]
Currently, you can already define a js function for an object from a closure like this:
```rust
this.set_named_property(
	"name",
	env.create_function_from_closure(
		"name",
		move |ctx: CallContext| -> napi::Result<JsUnknown> {
			method(&ctx, &variable_copied_from_above)
		},
	)?,
)?;
```

As I'd also like to copy variables from above into getters and setters, it would be great if I could do something like this:
```rust
this.define_properties(&[Property::new("name")?
	.with_getter(move |ctx: CallContext| -> napi::Result<JsUnknown> {
		getter_method(&ctx, &variable_copied_from_above)
	})
	.with_setter(move |ctx: CallContext| -> napi::Result<JsUnknown> {
		setter_method(&ctx, &variable_copied_from_above)
	})
	.with_property_attributes(PropertyAttributes::Enumerable)])?;
```

Just as a Background, I want to create objects with automatically generated getters and setters, thus, I need to pass the name of the getter and setter to the actual implementation of the getter/setter.

**Comment by LeoLeSommer** [comment]
I made some researches about it while i was diving into the code for my own needs.

(I'm absolutely not an expert of rs-napi).

If you take a look at the implementation of create_function_from_closure, it use napi_sys::napi_create_function. Which is a simple wrapper over the C++ api.

```
    fn napi_create_function(
        env: napi_env,
        utf8name: *const c_char,
        length: usize,
        cb: napi_callback,
        data: *mut c_void,
        result: *mut napi_value,
      ) -> napi_status;
```

As you see, there is a data parameter, which is an any pointer to a value.

With this pointer, you can send every data you want, personally i'm just sending a reference to a string representing the name of the property i want to access.

The property descriptor has an analog way to send datas to the getter/setter function, if you take a look at Property::raw(), it looks like it:

```
  pub(crate) fn raw(&self) -> sys::napi_property_descriptor {
    sys::napi_property_descriptor {
      utf8name: self.name.as_ptr(),
      name: ptr::null_mut(),
      method: self.method,
      getter: self.getter,
      setter: self.setter,
      value: self.value,
      attributes: self.attrs.into(),
      data: ptr::null_mut(),
    }
  }
```

You can affect the properties to a js object with the following code (where properties is a vec of sys::napi_property_descriptor):

```
                    unsafe {
                        check_status!(napi_sys::napi_define_properties(
                            env.raw(),
                            js_object.raw(),
                            properties.len(),
                            properties.as_ptr(),
                        ))?;
                    }
```

You can get it back in the getter/setter function using napi_sys::napi_get_cb_info:
 
            let mut this = std::ptr::null_mut();
            let mut args = [std::ptr::null_mut(); 1];
            let mut argc = 1;
            let mut data_ptr: *mut std::ffi::c_void = std::ptr::null_mut();

            check_status!(napi_sys::napi_get_cb_info(
                raw_env,
                callback_info,
                &mut argc,
                args.as_mut_ptr(),
                &mut this,
                &mut data_ptr,
            ))?;
    
In the current implementation of getter/setter, this value is always null. But you can use it to send a pointer to your closure and execute it.
    
It's a little bit tricky to do it in a proper way, you need to implements a finalizer to take care your closure is cleaned when the object is destroyed. I strongly encourage you to take a look at the implementation of create_function_from_closure in the rs-napi code. It's a little bit tricky but remains understandable.
    
What I'm sure is that there is no way to do that without getting your head into napi_sys crate which is a wrapper over the C++ API. I strongly hesitated to propose an evolution for a future release when i saw that this feature wasn't implemented but didn't took the time to do it. I think it should not be so hard to do (I've never participated to an open source project in my life but maybe it could be my first time).

I don't know if my explanations was clear, so if you need more help, don't hesitate to contact me, i can show you my code and maybe you'll find some inspirations from it.

**Comment by MarkusJx** [comment]
Thank you for your comment. I've also had something like this in mind (that's why I mentioned my use case) as I've been working with the C++ API for quite some time now. But I thought using closures, if possible, would be a little bit easier, as you wouldn't have to deal with the finalizers.

The best way of using finalizers would be of course to accept any data (possibly a `std::boxed::Box<T>`) or accept any napi value. The latter option would involve converting all values to napi values and back, which doesn't sound great. The option using any type with `Box` would involve creating a new struct for Property, so nobody has to define the template parameter when creating a property. And storing the Box inside Property might be necessary to not create any memory leaks.

But I don't know which one is better, or if there is an even better one.

If you want to try your luck with this, sure. Otherwise I could also try and implement this, you decide 🙂

**Comment by LeoLeSommer** [comment]
I think for now you should go with a DIY solution, i think i will take the time to propose the evolution but for now I'm quite busy in my life.

Finalizers on JsObject are using closures, so you can just send the data ownership to the closure data and free it from the closure ? It should be ok cause your object will be destroyed after any property use. That's what i've done.

**Comment by MarkusJx** [comment]
Well, I'm not quite willing to wait and if I'm implementing something, I'd rather do it properly once and submit the result in here, so...imma take a shot at this

**Comment by MarkusJx** [comment]
So I went down the lazy path with this and implemented a version of this in my code but that on is not *really* convenient to use, thus, this task might be still up for grabs

**Comment by victorteokw** [comment]
I implement ORM with rust for Node.js, and I need this, too. 🥹

**Comment by victorteokw** [comment]
Seems like we could add closure equivalents of `pub fn with_getter(mut self, callback: Callback) -> Self {`.

**Comment by victorteokw** [comment]
I tried to implement this but I cannot handle pointers well https://github.com/napi-rs/napi-rs/pull/1526

**Comment by victorteokw** [comment]
I implemented both getter and setter with closures in https://github.com/napi-rs/napi-rs/pull/1526

**Comment by MarkusJx** [comment]
Thank you @victorteokw for implementing this 🙂 

Unfortunately, I'm getting an access violation, when passing external data into the closure.
I've created a simple example highlighting the issue:

`lib.rs`:
```rs
#![deny(clippy::all)]

#[macro_use]
extern crate napi_derive;

use napi::{Env, JsObject, Property};

#[napi]
pub fn create_object(env: Env, val: String) -> napi::Result<JsObject> {
  let mut res = env.create_object()?;

  res.define_properties(&[Property::new("test")?.with_getter_closure(move |env, _| {
    println!("{}", val); // Access violation right here
    Ok(env.create_string(val.as_str()))
  })])?;

  Ok(res)
}
```

`index.js`:
```js
const native = require('.');

const obj = native.createObject("test");
console.log(obj);
console.log(obj.test);
```

I've also ran a similar example with address sanitizing enabled, the output of which can be found [here](https://github.com/MarkusJx/node-java-bridge/actions/runs/4588223489/jobs/8102287412).

I'll maybe look into this a bit further, if I find the time for it

**Comment by MarkusJx** [comment]
Should be fixed by #1552

**Comment by MarkusJx** [comment]
This seems to be implemented now, thanks again @victorteokw

**Comment by victorteokw** [comment]
Thanks @MarkusJx , by the way we need to thank @Brooooooklyn for implementing and test. Haha.
