### ISSUE TITLE
compile errors on some targets

### ISSUE THREAD

**Issue by universalmind303** [napi-rs/napi-rs#1389]
Description 

Compilation of the following targets fails.

- [aarch64-linux-android](https://github.com/universalmind303/nodejs-polars/actions/runs/3516256794/jobs/6241302143#logs)
- [x86_64-unknown-linux-musl](https://github.com/universalmind303/nodejs-polars/actions/runs/3516256794/jobs/6241301519#logs)
- [aarch64-unknown-linux-musl](https://github.com/universalmind303/nodejs-polars/actions/runs/3516256794/jobs/6241302291#logs)

Many of these worked on earlier versions of the docker images

**Comment by Brooooooklyn** [comment]
@universalmind303 yes, upstream Docker images and toolchains are updated very quickly, I'll fix it

**Comment by Brooooooklyn** [comment]
Close in https://github.com/pola-rs/nodejs-polars/pull/34
