### ISSUE TITLE
Incorrect argument of napi_create_async_work()

### ISSUE THREAD

**Issue by iamstolis** [napi-rs/napi-rs#1392]
The third argument of `napi_create_async_work()` [should be](https://nodejs.org/api/n-api.html#napi_create_async_work) `napi_value`. Unfortunately, `async_work.rs` [invokes this method with C string](https://github.com/napi-rs/napi-rs/blame/5994ef1b9519e2146851e5cdb38087d3a8d04c5b/crates/napi/src/async_work.rs#L68). C string is not `napi_value` (`napi_create_string_latin1` or `napi_create_string_utf8` are generally used to obtain `napi_value` corresponding to a C string). V8 (the JavaScript engine in the original Node.js) is able to survive this mismatch somehow but `graal-nodejs` (fork of Node.js in GraalVM) fails/crashes because of that.

**Comment by Brooooooklyn** [comment]
Closed in https://github.com/napi-rs/napi-rs/pull/1396
