### ISSUE TITLE
Nested classes

### ISSUE THREAD

**Issue by v-morlock** [napi-rs/napi-rs#1402]
Hi, 

I'm trying to have a class which has some public properties which also contain class instances. When defining them like that

```rs
#[napi(constructor)]
pub struct StructOne {
    pub two: StructTwo,
}

#[napi(constructor)]
pub struct StructTwo {
    pub a: i32,
}
```

I'm getting the following compiler error

```
the trait bound `api::req_out::StructTwo: NapiValue` is not satisfied
the following other types implement trait `NapiValue`:
  JsArrayBuffer
  JsBoolean
  JsBuffer
  JsDataView
  JsDate
  JsExternal
  JsFunction
  JsGlobal
and 9 others
required for `api::req_out::StructTwo` to implement `napi::bindgen_prelude::FromNapiValue
```

What would be the correct way to have a structure like that? The idea is to define instance methods on both levels.

**Comment by Brooooooklyn** [comment]
The ownership of the `Class` instance is belong to Node.js engine, so it could not be owned by another struct.

You can use `ClassInstance<StructTwo>` ([example](https://github.com/napi-rs/napi-rs/blob/main/examples/napi/src/class.rs#L342)) or `SharedReference<StructTwo>` ([example](https://github.com/napi-rs/napi-rs/blob/main/examples/napi/src/reference.rs#L49)) here

**Comment by v-morlock** [comment]
Thank you so much, that has cleared up my questions!

**Comment by Ethan-Arrowood** [comment]
@Brooooooklyn I'm still a little confused. The `ClassInstance` example only shows how to put a Class Instance (`Bird`) into an Object (`ObjectFieldClassInstance`). How can I get one class to include an instance of another? 

For example:

```rs
#[napi]
pub struct F {}

#[napi]
impl F {
  #[napi(constructor)]
  pub fn new() -> Self { F {} }
}

#[napi]
pub struct G {
  f: ClassInstance<F>
}

#[napi]
impl G {
  #[napi(constructor)]
  pub fn new (env: napi::Env) -> Self {
    G {
      f: F {}.into_instance(env).unwrap()
    }
  }
}
```

**Comment by Ethan-Arrowood** [comment]
Do I need to leverage SharedReference instead?
