### ISSUE TITLE
Better JS usage

### ISSUE THREAD

**Issue by AngeloCore** [napi-rs/napi-rs#1438]
[feature request]

First of all, thanks for this useful and easy library!
Using rust with your library is so easy, but when it comes to using the compiled `.node` files, it's a pain...
As we can see in [index.js](https://github.com/napi-rs/package-template/blob/main/index.js), we need to check for the user's OS and then return the correct native file.
Is it possible to generate just one file that works on each OS and just use it as `module.exports = require('./napi-rs.node')`

**Comment by Brooooooklyn** [comment]
@AngeloCore you can use `@napi-rs/cli` like that: `napi build --js false --release` (without `--platform`) and write your own `index.js`: `module.exports = require('./napi-rs.node')`

**Comment by AngeloCore** [comment]
Thanks!
