### ISSUE TITLE
Create `Reference` inside `ThreadSafeFunction`

### ISSUE THREAD

**Issue by HerringtonDarkholme** [napi-rs/napi-rs#1456]
Thanks for the great project.
I'm using napi-rs' `Reference` to pass Rust object to JavaScript for AST manipulation. However, it seems like there is no API for creating `Reference` from `env` now.

For more context, I'm traversing a directory using multiple threads and passing the parsed file to JavaScript callback via ThreadSafeFunction. https://github.com/ast-grep/ast-grep/blob/main/crates/napi/src/lib.rs#L476 

The Rust object is a wrapped tree-sitter ffi object with lifetime annotation. So I used `Reference<T>` to create a JS consumable object.

Here is a reduced example for object declaration.

```rust
// rust object
struct RustTree(ffi::Tree);
struct RustNode<'t>(ffi::Node, &'t RustTree);

// napi object
#[napi]
struct NapiTree(RustTree);
#[napi]
struct NapiNode(SharedReference<RustTree, RustNode<'static>>)
```

Then, I want to use tsfn to pass `NapiNode` to JavaScript.

```rust
#[napi]
pub fn parse_files(callback: JsFunction) -> Result<()> {
  let tsfn: ThreadsafeFunction<NapiNode> =
    callback.create_threadsafe_function(0, |ctx| Ok(vec![ctx.value]))?;
  // parallel parse files in directory 
  std::thread::spawn(|| {
     tsfn.call(Ok(????))   // what to pass here? RustTree or RustNode?
  })
}

```
In the child thread code path, I want to pass a `RustNode` to a `tsfn` and wrap it in `NapiNode` for JS consumption.

There are two issues about this code

1. Pass `RustNode` with reference across boundary. This is not a napi specific issue but a more fundamental Rust limitation. I can work around it by using `Box::leak` or raw pointer.
2. How to create a `NapiNode` from a `RustNode`. This is a napi issue and I don't know what's the best practice to do that.

I'm thinking about this solution:

1. make `tsfn` be called with both a tuple of `RustNode` and `RustTree`
2. in `create_threadsafe_function` call back, create a `NapiTree` from `RustTree` and pass it to node. A `Reference<NapiTree>` should be returned from node.
3. create a `NapiNode` from the `Reference<NapiTree>` and `RustNode`. Pass the NapiNode to JavaScript.

However, I don't know how to complete step 2 here. Do you have any suggestion on it?

**Comment by Brooooooklyn** [comment]
@HerringtonDarkholme  There is an `into_reference` static method on `#[napi]` derived struct, you can pass `RustTree` to tsfn callback, and create a reference with the `ctx.env`: `let tree_reference = RustTree::into_reference(ctx.value, ctx.env)?;`

**Comment by HerringtonDarkholme** [comment]
Thanks! It works great!
