### ISSUE TITLE
C/C++ source

### ISSUE THREAD

**Issue by wenq1** [napi-rs/napi-rs#1465]
Is it possible to add C sources to the project via modifying build.rs, like in https://doc.rust-lang.org/cargo/reference/build-scripts.html?

**Comment by Brooooooklyn** [comment]
Sure, there are serval projects that contain both C/C++ codes and Rust codes and build with NAPI-RS:
- https://github.com/Brooooooklyn/canvas
- https://github.com/Brooooooklyn/ttf2woff2

**Comment by wenq1** [comment]
Thanks!
