### ISSUE TITLE
Unnecessary BigInt when converting number via env.to_js_value

### ISSUE THREAD

**Issue by Brooooooklyn** [napi-rs/napi-rs#1470]
### Discussed in https://github.com/napi-rs/napi-rs/discussions/1468

<div type='discussions-op-text'>

<sup>Originally posted by **m1212e** February  2, 2023</sup>
Hi,

I'm converting a `serde_json::Value` which is the number 17 to a JS object via a `env::to_js_value` call. The conversion is successful but returns 17n instead of 17. So it returns a BigInt instead of Number. Why does this happen?</div>

**Comment by Brooooooklyn** [comment]
@m1212e does the type of `17` is `u64`?

**Comment by m1212e** [comment]
I don't really know, this depends on the internals of serde_json. I'll paste my code for better understanding:

```
    let tsf = crate::threadsafe_function::ThreadsafeFunction::create(
      env.raw(),
      unsafe { func.raw() },
      0,
      |ctx: crate::threadsafe_function::ThreadSafeCallContext<(
        Vec<serde_json::Value>,
        oneshot::Sender<serde_json::Value>,
      )>| {

        // The args are a vec of serde_json::Value which get converted to js values below
        let args = ctx
          .value
          .0
          .iter()
          .map(|v| ctx.env.to_js_value(v))
          .collect::<Result<Vec<JsUnknown>, napi::Error>>()?;

        let response = ctx.callback.call(None, args.as_slice())?;
        let response_channel = ctx.value.1;

        if !response.is_promise()? {
          let response: serde_json::Value = ctx.env.from_js_value(response)?;
          ctx
            .env
            .execute_tokio_future(
              async move {
                match response_channel.send(serde_json::to_value(&response)?) {
                  Ok(_) => {}
                  Err(err) => {
                    return Err(napi::Error::from_reason(format!(
                      "Could not send response: {err}"
                    )))
                  }
                };
                Ok(())
              },
              |_, _| Ok(()),
            )
            .unwrap();
        } else {
          unsafe {
            let prm: Promise<serde_json::Value> =
              Promise::from_napi_value(ctx.env.raw(), response.raw())?;
            ctx.env.execute_tokio_future(
              async move {
                let result = prm.await?;
                match response_channel.send(serde_json::to_value(result)?) {
                  Ok(_) => {}
                  Err(err) => {
                    return Err(napi::Error::from_reason(format!(
                      "Could not send response: {err}"
                    )))
                  }
                };
                Ok(())
              },
              |_, _| Ok(()),
            )?;
          }
        };

        Ok(())
      },
    )?;
```
The creation of these serde_json::Value happens via `serde_json::from_slice` from json data that looks like this:
```json
[
	1,
	"23",
	17,
	true,
	33.4,
	-4
]
```
Everything works as expected, only the 17 is converted to a BigInt

**Comment by m1212e** [comment]
You might be right about this, as far as I can see serde_json::Value always uses a u64 for positive int:

From serde_json::Value
```
enum N {
    PosInt(u64),
    /// Always less than zero.
    NegInt(i64),
    /// Always finite.
    Float(f64),
}
```
My problem with this is, that equality comparison in JS fails when comparing the big int and e.g. a hard coded seventeen
(`17 !== 17n`). I'd like to return a BigInt only when necessary. So the best way to do this probably would be to check if it is a number, then check if it is necessary to use a u64 and if not, cast it to a different type?

**Comment by m1212e** [comment]
My suggested workaround works:

```
let args = ctx
          .value
          .0
          .iter()
          .map(|v| {
            // serde json by default uses u64 for positive integers. This results in napirs using a BigInt instead of a number
            // to avoid this, we need to check if the value is a number and if it fits into a smaller number type
            // if this is the case, we convert it and then pass it to napi rs
            match v.as_u64() {
              Some(nb) => {
                if nb <= u32::MAX.into() {
                  ctx.env.to_js_value(&(nb as u32))
                } else {
                  ctx.env.to_js_value(v)
                }
              }
              None => ctx.env.to_js_value(v),
            }
          })
          .collect::<Result<Vec<JsUnknown>, napi::Error>>()?;
```
I'm not sure if this is something that should be handled by napi.rs to be honest. On one side, an automatic type conversion into the optimal type is very convenient to use, but also would hide potentially unexpected conversion, which might not be ideal.

**Comment by eandre** [comment]
We noticed this behaving a bit strange for numbers greater than u32 but less than [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). Since those numbers can be safely expressed using the regular `number` type, it's unexpected to me that they get mapped to a BigInt.

Would you be open to a PR to convert numbers > u32::MAX and <= Number.MAX_SAFE_INTEGER as a regular JS `number`, instead of a `BigInt`?

**Comment by eandre** [comment]
We noticed this behaving a bit strange for numbers greater than u32 but less than [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). Since those numbers can be safely expressed using the regular `number` type, it's unexpected to me that they get mapped to a BigInt.

@Brooooooklyn: Would you be open to a PR to convert numbers > u32::MAX and <= Number.MAX_SAFE_INTEGER as a regular JS `number`, instead of a `BigInt`?

**Comment by Brooooooklyn** [comment]
> Would you be open to a PR to convert numbers > u32::MAX and <= Number.MAX_SAFE_INTEGER as a regular JS number, instead of a BigInt?

Sounds reasonable, I'll do that

**Comment by eandre** [comment]
Are you doing the PR? Or do you want me to?

**Comment by Brooooooklyn** [comment]
> Or do you want me to?

You can try it! Thanks!
