### ISSUE TITLE
Create API duplicating the capabilities of the CLI.

### ISSUE THREAD

**Issue by TheLarkInn** [napi-rs/napi-rs#1482]
We are looking to introduce Rust into our monorepo management tool Rush. I have looked at the napi-rs/package-template and noticed that the scripts are very noisy. 

In a monorepo we depend on abstracting away that noise to make it easy for users to iterate. I would like to request that napi-rs introduce a NodeJS API that we can use programmatically to pass in configuration, outputpaths, destDir, and other behaviors found in the CLI. 

Today I'm forced to use `child_process.spawn()` to abstract away these complexities as seen in this PR:  https://github.com/microsoft/rushstack/pull/3961 

(specifically here https://github.com/microsoft/rushstack/pull/3961/files#diff-590cba6f6874b67951ecf78cf7ee4907cd6a9cd537a29cfd7ee71fbd461a4f6cR29-R58 )

**Comment by forehalo** [comment]
@TheLarkInn

The api version of napi cli is available now in `@napi-rs/cli` prerelease phase. You can have a taste by `npm install @napi-rs/cli@alpha`.

We will ship it asap when we think it's stable enough and get all docs work done.

quick example:

```ts
import { NapiCli } from '@napi-rs/cli'

// more detail at https://github.com/napi-rs/napi-rs/tree/main/cli#readme
new NapiCli().build({
  // options
})
```

**Comment by Brooooooklyn** [comment]
Close in https://github.com/napi-rs/napi-rs/pull/1492
