### ISSUE TITLE
Can't throw JSError?

### ISSUE THREAD

**Issue by southorange1228** [napi-rs/napi-rs#1495]
```rust
[napi]
pub test() -> Result<number> {
  let response: DnsResponse = client
    .query(&name, DNSClass::IN, RecordType::A)
    .map_err(|e| Error::from_reason(format!("Query dns server failed with: {}", e.to_string())))?;
}
```

I use`Error::from_reason` to return `error`.Buy always throw rust error? 
<img width="991" alt="图片" src="https://user-images.githubusercontent.com/32590310/221088778-29568b5e-7081-43df-97c4-34e43729b1c1.png">

Any info should i to provider?

**Comment by Brooooooklyn** [comment]
Panic here https://github.com/southorange1228/network-tools/blob/main/packages/dns/src/lib.rs#L58, it's nothing to do with NAPI-RS.

**Comment by southorange1228** [comment]
> Panic here https://github.com/southorange1228/network-tools/blob/main/packages/dns/src/lib.rs#L58, it's nothing to do with NAPI-RS.

I know.If i want to throw `jserror`not `rust panic`,what should i do?

**Comment by Brooooooklyn** [comment]
`.map_err(|e| Error::from_reason(format!("Query dns server failed with: {}", e.to_string())))?`

**Comment by southorange1228** [comment]
> ```rust
> [napi]
> pub test() -> Result<number> {
>   let response: DnsResponse = client
>     .query(&name, DNSClass::IN, RecordType::A)
>     .map_err(|e| Error::from_reason(format!("Query dns server failed with: {}", e.to_string())))?;
> }
> ```
> 
> I use`Error::from_reason` to return `error`.Buy always throw rust error? <img alt="图片" width="991" src="https://user-images.githubusercontent.com/32590310/221088778-29568b5e-7081-43df-97c4-34e43729b1c1.png">
> 
> Any info should i to provider?

Try it.But throw rust panic.. @Brooooooklyn

**Comment by Brooooooklyn** [comment]
The screenshot you provide is panic from `unwrap`, not the `JsError` you returned. You should `map_err` and return `napi::Error` here

**Comment by southorange1228** [comment]
Yeah, so i changed my code.
https://github.com/southorange1228/network-tools/blob/main/packages/dns/src/lib.rs#L73

You can try it with `pnpm install && pnpm run test`,and can be repreduced.  Amazing...

**Comment by Brooooooklyn** [comment]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/3468483/221136743-797b8ffa-f399-4d70-840b-c36c74439803.png">
