### ISSUE TITLE
  [npm].darwin-x64.node execution error after mac codesign

### ISSUE THREAD

**Issue by limerickgds** [napi-rs/napi-rs#1496]
@napi-rs/cli version: 2.13.0-alpha.6

**Comment by Brooooooklyn** [comment]
Please try the version `2.14.8`

**Comment by limerickgds** [comment]
@Brooooooklyn Does this support x86_64-pc-windows-msvc build？

**Comment by limerickgds** [comment]
@Brooooooklyn 
napi build --release --platform --cargo-name [name] --js ./binding.js --dts ./binding.d.ts --cargo-cwd crates/napi --zig
Internal Error: x86_64-pc-windows-msvc can not be cross compiled by zig
    at BuildCommand.<anonymous> (/home/code/node_modules/@napi-rs/cli/scripts/index.js:11386:27)
    at Generator.next (<anonymous>)

**Comment by Brooooooklyn** [comment]
@limerickgds please `omit` the `--zig` flag, and install `cargo-xwin`: `cargo install cargo-xwin`, then running the following command: `napi build --release --platform --target x86_64-pc-windows-msvc  --cargo-name [name] --js ./binding.js --dts ./binding.d.ts --cargo-cwd crates/napi`

**Comment by limerickgds** [comment]
@Brooooooklyn it still has problems. `[1]    55369 segmentation fault  node `

template code :  
[test.zip](https://github.com/napi-rs/napi-rs/files/10831216/test.zip)

**Comment by Brooooooklyn** [comment]
> execution error after mac codesign

I can be sure it's not a NAPI-RS problem.
