### ISSUE TITLE
Using napi-rs with vercel/pkg to bundle cross-platform packages

### ISSUE THREAD

**Issue by Mikescops** [napi-rs/napi-rs#1507]
Hello @Brooooooklyn,

I'm looking to use vercel/pkg to package cross-platform binaries. In my dependencies I have few packages using napi-rs (or node-rs).

The problem I encounter is that the optionalDependencies are expecting a specific os/cpu during the `npm install` so the non-matching one will be removed.
When bundling, pkg won't try to re-download the dependencies matching the expected architecture. Which will end up in a *.node not found when running the final binary.

Do you have ideas on how it could be supported? and let me know if I should open this issue on pkg side.

**Comment by Brooooooklyn** [comment]
Use `yarn` instead: https://yarnpkg.com/configuration/yarnrc#supportedArchitectures

**Comment by Mikescops** [comment]
Excellent, thanks a lot, it works like a charm 👍 (as long as you use yarn >=2). 
Thanks again for your work here 😄
