### ISSUE TITLE
If I can use napi crate as a lib ?

### ISSUE THREAD

**Issue by GiveMe-A-Name** [napi-rs/napi-rs#1508]
I have two crates:

1. cool1
```rust
#[napi]
pub fn sum1(a: i32, b:i32) -> i32 {
  a + b
} 
```

2. cool
```rust
pub use cool1;
#[napi]
pub fn sum(a: i32, b:i32) -> i32 {
  a + b
} 
```
Can I use `cool1` as `cool` dependency ? That I can reuse crate `cool1` 
But When I run `pnpm build` in `cool` dependency, the index.js was product is not export sum1.  

Then I determinate write `module.export.sum1 = sum1` in `index.js` by myself. 
Like this:
```js 
// index.js
const { sum, sum1 } = nativeBinding;

module.exports.sum1 = sum1;
module.exports.sum = sum;
```
It is work !!!
So Does it mean the `napi-cli` can not correctly product js file when this situation.

**Comment by Brooooooklyn** [comment]
No, cli can't handle this, because [Procedural Macros](https://doc.rust-lang.org/reference/procedural-macros.html#procedural-macros) can only scan the sources in the current crate.

But you can do something like this, in `cool` package: `build: napi build --platform --release --js cool.js --dts cool.d.ts`
and re-export everything in `index.js` and `index.d.ts`:

```js
const { sum1 } = require('cool1')
const { sum } = require('./cool.js')
module.exports.sum1 = sum1
module.exports.sum = sum
```

**Comment by GiveMe-A-Name** [comment]
> No, cli can't handle this, because [Procedural Macros](https://doc.rust-lang.org/reference/procedural-macros.html#procedural-macros) can only scan the sources in the current crate.
> 
> But you can do something like this, in `cool` package: `build: napi build --platform --release --js cool.js --dts cool.d.ts` and re-export everything in `index.js` and `index.d.ts`:
> 
> ```js
> const { sum1 } = require('cool1')
> const { sum } = require('./cool.js')
> module.exports.sum1 = sum1
> module.exports.sum = sum
> ```

Thanks.
