### ISSUE TITLE
How to save javascript callback in rust and call in other function ?

### ISSUE THREAD

**Issue by oohusl** [napi-rs/napi-rs#1513]
code like this：

const cb;
#[napi]
pub fn testCallback(callback: Fn) {
cb = t;
}
pub fn xx(){
   cb();
}

**Comment by Brooooooklyn** [comment]
@oohusl it's hard to write codes like this in Rust. You need `once_cell` crate to implement this:

```rust
static CALLBACK: Lazy<Mutex<Option<Ref<JsFunction>>>> = Lazy::new(Default::default);
```

**Comment by oohusl** [comment]
We are starter of rust. How to save JsFunction to CALLBACK, how to fetch JsFunction and execute it, please also guide. Thank you very much.

**Comment by Brooooooklyn** [comment]
@oohusl you guys need to learn Rust first, it's out of my scope here
