### ISSUE TITLE
Any example use custom Type(C ptr) as function params or result? 

### ISSUE THREAD

**Issue by southorange0929** [napi-rs/napi-rs#1517]
```rs
#[repr(C)] 
pub struct ctx_ptr { _private: [u8; 0] }

extern {
  pub fn test(ctx: *const ctx_ptr) -> *const ctx_ptr;
  pub fn new() -> *const ctx_ptr;
}


#[napi]
pub fn js_func(params: xx) -> xx {
  test(params)
}
#[napi]
pub fn js_func_new() -> xx {
  xx
}
```

usage:
```js
const ctx = js_func_new();
const result = js_func(ctx);
```

If using ffi to extern dll/dylib, how to declare `xx` as `*const ctx_ptr`?
Any suggest about this? Thanks

**Comment by southorange0929** [comment]
Any suggest about this ? Thanks

**Comment by Brooooooklyn** [comment]
Could it be implemented by a `Class`?

```rust
#[napi]
pub struct Context {
  inner: *const ctx_ptr
}

#[napi]
impl Context{
  #[napi(constructor)]
  pub fn new() -> Self {
    Self { inner: unsafe { ffi::new() } }
  }

  #[napi]
  pub fn func(&self) {
    unsafe { ffi::test(self.inner) };   
  }
}
```

**Comment by southorange0929** [comment]
I think you are right, but this approach may lead to changes in the business logic of the function being called.
If there is no better idea,i'll try it.Thanks!

**Comment by Brooooooklyn** [comment]
You can also use `External` and pass `External` back, see https://napi.rs/docs/concepts/external

**Comment by southorange0929** [comment]
> You can also use `External` and pass `External` back, see https://napi.rs/docs/concepts/external

That's a good idea! Thanks
