### ISSUE TITLE
First argument passed into thread safe function appears to be the second argument

### ISSUE THREAD

**Issue by victorteokw** [napi-rs/napi-rs#1521]
Hi, thanks for this great package. However, I encountered a strange circumstance.

<img width="1237" alt="Screenshot 2023-03-16 at 19 19 35" src="https://user-images.githubusercontent.com/3055936/225601935-50c0c07e-82b5-42af-bc14-31e59f6b35e7.png">
See `Ok (vec![js_value])`, the argument list only contains a single value, which is the `js_value`.

But when accessing from Node.js, the value being passed in appears at the second argument:
<img width="406" alt="Screenshot 2023-03-16 at 19 20 12" src="https://user-images.githubusercontent.com/3055936/225602176-c2df61ff-a142-4dfc-a2de-0628b498adfa.png">

The first argument is a strange `null` value. How can I fix this and make it appear as the first argument?

**Comment by Brooooooklyn** [comment]
See https://napi.rs/docs/concepts/threadsafe-function#errorstrategy
