### ISSUE TITLE
String argument is invalid argument for the Node.js `require` function

### ISSUE THREAD

**Issue by victorteokw** [napi-rs/napi-rs#1522]
Hi, thanks for the great package! 👏

I obtain a `require` from the global. And try to require a package installed with `npm`. I saw examples [here](https://docs.rs/napi/latest/napi/struct.JsFunction.html) for passing arguments into `JsFunction`. But when I run, I get errors:
<img width="990" alt="Screenshot 2023-03-16 at 22 32 47" src="https://user-images.githubusercontent.com/3055936/225651004-f82dc5c1-f53b-488d-b0be-49517f2904b2.png">
<img width="1159" alt="Screenshot 2023-03-16 at 22 33 13" src="https://user-images.githubusercontent.com/3055936/225651021-13c035c0-ce5e-43a7-b4b7-c598b7e2c0e9.png">
When unwrap the calling result, it panics with an argument invalid error. How to correctly require or import a node.js package?

Thanks

**Comment by Brooooooklyn** [comment]
Unfortunately you can't access `require` in the `global` in Node-API. All you can do is pass the `require` function from JavaScript side to the Rust side

**Comment by victorteokw** [comment]
Hi @Brooooooklyn , I fixed by doing this:
```js
const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process
globalThis.require = require; // <----- New
let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim();
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}
```

Can I provide some context and info maybe through `#[napi]` to modify the generated `index.js`?

**Comment by Brooooooklyn** [comment]
We don't have a way to modify the generated binding.js file yet, but there are several ways to workaround:

1. You can re-export the bindings from another files: 

```js
// main.js
globalThis.require = require;
module.exports = require('./index.js') // generated binding
```

2. There is `--pipe` flag in `napi build`: https://napi.rs/docs/cli/build. You can use it to modify the generated after the build

**Comment by victorteokw** [comment]
Thanks @Brooooooklyn, I'll have a try.

**Comment by victorteokw** [comment]
Hi @Brooooooklyn, I fixed by doing this thanks to your workarounds.
<img width="633" alt="Screenshot 2023-03-17 at 11 59 29" src="https://user-images.githubusercontent.com/3055936/225809405-ac8e76f2-3e1d-44f0-aace-a2065cbf32ab.png">
I just can't understand, when I write Python in rust, I can import any packages. Why Node.js official C++ addons API don't support this? Wouldn't be nice if there is some formal and official way to load packages from rust code?

**Comment by Brooooooklyn** [comment]
IMO, it may be because the `require` function in Node.js relies on JavaScript implementation

**Comment by victorteokw** [comment]
Am I understanding right that require is not from nodejs but its underlying vm?

**Comment by Brooooooklyn** [comment]
- Ref: https://github.com/nodejs/node/issues/27064

**Comment by victorteokw** [comment]
Many thanks @Brooooooklyn
