### ISSUE TITLE
feaqure request: Config for custom file header

### ISSUE THREAD

**Issue by suyanhanx** [napi-rs/napi-rs#1523]
The current configuration can only determine whether to display the header.
It would be helpful to add a setting that allows users to customize the header, for example when adding a license.

**Comment by Xuanwo** [comment]
Regarding the issues https://github.com/apache/incubator-opendal/pull/1664 and https://github.com/apache/incubator-opendal/issues/1662, we would like to submit a pull request to implement this feature. Kindly consider our proposal.

**Comment by Brooooooklyn** [comment]
@suyanhanx does the `--pipe` flag work? https://napi.rs/docs/cli/build

**Comment by Xuanwo** [comment]
> @suyanhanx does the `--pipe` flag work? https://napi.rs/docs/cli/build

I don't understand. How can we use this flag to add headers?

**Comment by Brooooooklyn** [comment]
@suyanhanx could you try this version https://github.com/napi-rs/napi-rs/releases/tag/%40napi-rs%2Fcli%402.15.0? It supposes to fix it

**Comment by suyanhanx** [comment]
I found that you moved the pipe to the back, which is reasonable, but deleted the pipe for `dts` file. 
It seems like this still didn't fully achieve the purpose.
@Brooooooklyn
