### ISSUE TITLE
can't build with link or can't find dylib?

### ISSUE THREAD

**Issue by southorange0929** [napi-rs/napi-rs#1524]
I try to add `rustc-link-search` before build:
```rs
// build.rs
extern crate napi_build;

fn main() {
  // add lib folder to link
  println!("cargo:rustc-link-search=custom_path/lib");
  napi_build::setup();
}
```

And use link with:
```
#[link(name="mylib")]
extern "C" {}
```

`custom_path/lib` folder with those files: `mylib.so` `mylib.dll` `mylib.dylib`

Then run `npm run build` and get error

<img width="1431" alt="图片" src="https://user-images.githubusercontent.com/32590310/225874753-41cc81a8-aa31-4707-b4a6-2f9bb06352ca.png">

Any suggest with it? 
platform: linux

**Comment by Brooooooklyn** [comment]
can you build with `cargo build` ?

**Comment by messense** [comment]
> `custom_path/lib` folder with those files: `mylib.so` `mylib.dll` `mylib.dylib`

Doesn't Linux and macOS require a `lib` prefix for shared libraries? Like `libmylib.so`, `libmylib.dylib`?

**Comment by southorange0929** [comment]
I'm sorry that reply so late. And i try to add `lib` prefix with file,it can build successfully. Thanks
