### ISSUE TITLE
build failed with rust:1.59.0-buster

### ISSUE THREAD

**Issue by southorange0929** [napi-rs/napi-rs#1534]
I use `dockerfile` to create docker image with ci.

run `pnpm build` failed.
`cargo build` success.

Error info:
<img width="963" alt="图片" src="https://user-images.githubusercontent.com/32590310/226798850-25d5b229-5176-447a-8fea-2df68f83bbc0.png">

System info:

Linux 9f278b9366d5 5.4.119-1-tlinux4-0008 #1 SMP Fri Nov 26 11:17:45 CST 2021 x86_64 GNU/Linux

Dockerfile info:

```Dockerfile
FROM rust:1.59.0-buster

SHELL ["/bin/bash", "-c"]

RUN curl https://get.volta.sh | bash

ENV VOLTA_HOME="/root/.volta"

ENV PATH="${VOLTA_HOME}/bin:${PATH}"

RUN volta install node@16.14.0 && \
    npm config set registry https://mirrors.tencent.com/npm/ && \
    npm i -g pnpm 

ENV PNPM_HOME="/lib/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"

COPY package.json pnpm-lock.yaml ./

RUN pnpm install
```

**Comment by Brooooooklyn** [comment]
@southorange0929 it was broken by the `napi-derive` release yesterday, you can upgrade `@napi-rs/cli` to 2.15.1 to fix that, or I will draft a new release of `napi-derive` to fix it asap.

**Comment by southorange0929** [comment]
> @southorange0929 it was broken by the `napi-derive` release yesterday, you can upgrade `@napi-rs/cli` to 2.15.1 to fix that, or I will draft a new release of `napi-derive` to fix it asap.

Update and fixed.Thanks
