### ISSUE TITLE
Concepts > async fn  not work

### ISSUE THREAD

**Issue by at86** [napi-rs/napi-rs#1535]
cannot find function `execute_tokio_future` in module `napi::bindgen_prelude`
not found in `napi::bindgen_prelude`

```
use futures::prelude::*;
use napi::bindgen_prelude::*;
use tokio::fs;
 
#[napi]
async fn read_file_async(path: String) -> Result<Buffer> {
  fs::read(path)
    .map(|r| match r {
      Ok(content) => Ok(content.into()),
      Err(e) => Err(Error::new(
        Status::GenericFailure,
        format!("failed to read file, {}", e),
      )),
    })
    .await
}
```

**Comment by Brooooooklyn** [comment]
@at86 have you enabled `async` feature in `napi`? like this:

```toml
# Cargo.toml
napi = { version = "2", features = ["async"] }
```

**Comment by at86** [comment]
> @at86 have you enabled `async` feature in `napi`? like this:
> 
> ```toml
> # Cargo.toml
> napi = { version = "2", features = ["async"] }
> ```

thanks, I forgot it.
