### ISSUE TITLE
How to cross complie without glibc?

### ISSUE THREAD

**Issue by southorange0929** [napi-rs/napi-rs#1540]
Run `napi build --release build-dist --target=x86_64-unknown-linux-musl --zig`
But i can't get dist without glibc. `ldd`'s result deps on `glibc`

Any other setting should i add? 

<img width="689" alt="图片" src="https://user-images.githubusercontent.com/32590310/227400326-caaeb224-ee68-41bf-b6fc-c5247e802c55.png">

**Comment by Brooooooklyn** [comment]
You need to separate `musl` and `glibc` targets. The Node.js addon (dynamic linked library) does not support compile without `glibc` it self

**Comment by southorange0929** [comment]
Or I mean how to be compatible with glibc lower version? For example, Node.js with `12.x` need `glibc2.17`, how to adapt this low version(2.17)?

**Comment by messense** [comment]
Have you read through the documentation? There is an explicit mention of `glibc 2.17` in this page: https://napi.rs/docs/cross-build/summary.

**Comment by Brooooooklyn** [comment]
@southorange0929 or you can compile your package in the official Docker image: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian

**Comment by southorange0929** [comment]
> Have you read through the documentation? There is an explicit mention of `glibc 2.17` in this page: https://napi.rs/docs/cross-build/summary.

I am sorry that.But i can't rely on github actions.I used inner platform and always deps on high version,for example: `2.25`

**Comment by southorange0929** [comment]
> @southorange0929 or you can compile your package in the official Docker image: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian

Let me try it. Thanks

**Comment by Brooooooklyn** [comment]
> I am sorry that.But i can't rely on github actions.I used inner platform and always deps on high version,for example: 2.25

@southorange0929 The documentation mentioned by @messense explains how to cross-platform compile different binaries on a self-hosted CI, and you should read it.

**Comment by messense** [comment]
> But i can't rely on github actions.I used inner platform and always deps on high version,for example: `2.25`

You don't really need to use github actions, you just need to take some inspiration from the commands it executes: https://github.com/napi-rs/cross-build/blob/main/.github/workflows/pure-rust-build-on-linux.yml

**Comment by southorange0929** [comment]
About project `cross-build` runned successfully? 
I try to use it to get some idea with official Docker images,but get some error.Sad...

Try it with Dockerfile 
```Dockerfile
FROM ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian

ARG ZIG_VERSION=0.10.1

RUN wget https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz && \
  tar -xvf zig-linux-x86_64-${ZIG_VERSION}.tar.xz && \
  mv zig-linux-x86_64-${ZIG_VERSION} /usr/local/zig && \
  ln -sf /usr/local/zig/zig /usr/local/bin/zig && \
  rm zig-linux-x86_64-${ZIG_VERSION}.tar.xz

RUN cargo install cargo-xwin

RUN npm config set registry https://mirrors.tencent.com/npm/ && \
    npm i -g pnpm 

WORKDIR /data/orange-ci/workspace

# 设置pnpm setup
ENV PNPM_HOME="/lib/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"

COPY package.json pnpm-lock.yaml ./

RUN pnpm install
```

Then run these commaders: 
```shell
docker build . -t rust_cross_compile/linux -f Dockerfile
docker run --rm -ti -v `pwd`:/data/orange-ci/workspace rust_cross_compile/linux
```

run commanders in container:
```shell
rustup target add x86_64-unknown-linux-musl
yarn workspace @napi-cross-build/01-pure-rust build --zig --target x86_64-unknown-linux-musl

cd 01-pure-rust &&  ldd 01-pure-rust.linux-x64-musl.node
```

and then you can get some error with it.Is there not supported with `x86_64-unknown-linux-musl` target?  Thanks

**Comment by southorange0929** [comment]
> What's the reason for using the `x86_64-unknown-linux-musl` target? If you are going to deploy on a glibc system, it won't run anyway.

There is always to get some error about `glibc` version.
In our deploy system,always not fount some version for `*.node`file. For example: 2.18 2.15 and so on.

Run with `ldd --version`, result is `glibc2.17`

Any suggest for me?

**Comment by Brooooooklyn** [comment]
@southorange0929 there are 2 different ways that you can build a native addon with GLIBC_2.17:

1. Build your package in ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian directly without zig, just run `napi build --release --platform` **WITHOUT ANY OTHER ARGS**
2. Build your package on any systems with `zig`, just run `napi build --release --platform --zig --zig-abi-suffix 2.17 --target x86_64-unknown-linux-gnu`

Please follow these two approaches strictly before asking again and don't build the musl target.

**Comment by southorange0929** [comment]
I'm sorry that too many or simple questions. With your help, i solved it. Thanks a lot!
