### ISSUE TITLE
build target `x86_64-apple-darwin` failed with ci mode but success with real device

### ISSUE THREAD

**Issue by southorange0929** [napi-rs/napi-rs#1543]
I try to build `x86_64-apple-darwin` with ci. Try to build with `osxcross` or without `osxcross`,but get failed.

I tried these steps:
|step|result| mode |
|----|----|----|
|run `napi build --release build-dist --target x86_64-apple-darwin` `without osxcross`| Failed | CI |
|run `napi build --release build-dist --target x86_64-apple-darwin` `with osxcross`     | Failed | CI |
|run `cargo build --target x86_64-apple-darwin`| Success | CI |
|run `napi build --release build-dist --target x86_64-apple-darwin` in my real mbp machine(M1 PRO) | Success | real machine |

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/32590310/227775975-a750e783-f982-459d-9866-b6f5cfc8966e.png">

Any suggest about it? Is my code fault or any more information should be provide? Thanks.

**Comment by southorange0929** [comment]
That's my fault.Look like some conditional compile not work

**Comment by southorange0929** [comment]
In `build.rs`, cross compile should use `env::var("CARGO_CFG_TARGET_OS")` to get build target, not `cfg!`.
`cfg!` always get operation system,not `--target` system.
For example, `cargo build --target x86_64-apple-darwin` on linux. `cfg!(target_os = "macos")` is false in `build.rs`

**Comment by messense** [comment]
That's right, congrats you're getting the hang of it.

See also https://kazlauskas.me/entries/writing-proper-buildrs-scripts
