### ISSUE TITLE
How to extract `env` at `JsFunction`?

### ISSUE THREAD

**Issue by sunrabbit123** [napi-rs/napi-rs#1629]
I want to next code
```rs
pub fn call_event(f: &JsFunction, this: Option<&JsObject>, args1: JsString, args2: JsFunction) -> Result<JsUnknown> {
    let raw_this = this
        .map(|v| unsafe { v.raw() })
        .or_else(|| {
            unsafe { Env::from_raw(f.0.env) }
                .get_undefined()
                .ok()
                .map(|u| unsafe { u.raw() })
        })
        .ok_or_else(|| Error::new(Status::GenericFailure, "Get raw this failed".to_owned()))?;
    f.
    let raw_args = vec![ args1.raw(), args2.raw()];
    let mut return_value = ptr::null_mut();
    check_pending_exception!(f.0.env, unsafe {
        sys::napi_call_function(f.0.env, raw_this, f.0.value, 2, raw_args.as_ptr(), &mut return_value)
    })?;
    unsafe { JsUnknown::from_raw(f.0.env, return_value) }
}
```

but, f.0 is private field
So I decided to only access the env and 
value field that I needed.

However, while I was able to get the value
Where do I get the env?

**Comment by Brooooooklyn** [comment]
```rust
#[napi]
pub fn call_event(env: Env, f: &JsFunction)
```

**Comment by sunrabbit123** [comment]
I don't know what the `env` of the argument value is doing

Does the `env` of the `function` i received as input match the `env` i received at the same time?

I think it's possible that the env of the anonymous function, which captures a different context, is different from the env of the function when it is executed.

Of course, the above is for `env` as I understand them.

I still don't know what `env` does
