### ISSUE TITLE
get_named_property no longer type checks, causing downstream errors

### ISSUE THREAD

**Issue by devongovett** [napi-rs/napi-rs#1641]
When upgrading napi-rs in lightningcss, I noticed that I started getting runtime errors like "Cannot convert null or undefined to an object". I traced this to code like this:

```rust
if let Ok(value) = some_object.get_named_property::<JsObject>("some_property") {
  // Do anything with the object, and it errors.
  value.get_named_property("something")
}
```

This attempts to get a property, and it used to assert that the value was an object. However, in this PR that changed: https://github.com/napi-rs/napi-rs/pull/1473/files#diff-05418fc5eaa013f49a15c302a691f7b8564d0a1d0956f9445005443d854ed076R347. Now it calls `from_napi_value` instead of `from_raw`, and `from_napi_value` uses `from_raw_unchecked` instead, therefore skipping the type check.  https://github.com/napi-rs/napi-rs/blob/9c09975b9eb6616ce1eb33caaeb8798171d74ea8/crates/napi/src/bindgen_runtime/js_values.rs#L91

So now the above `get_named_property` always succeeds, even if the value isn't an object (e.g. is null or undefined), and then the next call assumes it is an object and fails at runtime.

I checked and changing `from_napi_value` to use `from_raw` instead of `from_raw_unchecked` fixes the problem, but I'm not sure if there are any downsides or why it was using unchecked in the first place.

**Comment by kwonoj** [comment]
@Brooooooklyn mind share some thoughts on this issue? This hits us as well with latest versions of napi using lightningcss's existing code.

Since issue was filed a while ago, curious if this is being considered as something to be fixed or it's an expected upstream behavior any consumer need own way to check values.
