### ISSUE TITLE
fix: future cannot be sent between threads safely

### ISSUE THREAD

**Issue by jjangga0214** [napi-rs/napi-rs#1644]
Hi, if I turn a function to async, this error occurs.

<img width="867" alt="스크린샷 2023-07-07 오전 10 44 30" src="https://github.com/napi-rs/napi-rs/assets/28584151/04065602-3885-4602-89b2-fc170eec2159">

```
future cannot be sent between threads safely
within `[async block@src/lib.rs:107:1: 107:80]`, the trait `Send` is not implemented for `*mut napi_env__`rustc 
Click for full compiler diagnostic
lib.rs(107, 1): captured value is not `Send`
tokio_runtime.rs(89, 18): required by a bound in `execute_tokio_future`
```

Is this an intentional design, or a bug?

Thanks :)

**Comment by nawbc** [comment]
Remove the `async`

**Comment by jjangga0214** [comment]
@nawbc ofc I know. I can indeed remove `async` in this example, as the function `foo` doesn't do anything async in fact. 
But this is just a minimal example that proves there's something wrong. Why shouldn't I declare `async` function at all?

**Comment by Brooooooklyn** [comment]
because the function argument: `JsFunction` is not thread safe,

**Comment by jjangga0214** [comment]
@Brooooooklyn Then how can I pass a js callback function to async rust function?

**Comment by Brooooooklyn** [comment]
you can pass `ThreadsafeFunction` as an argument directly like this: https://github.com/napi-rs/napi-rs/blob/main/examples/napi/src/threadsafe_function.rs#L150

**Comment by jjangga0214** [comment]
@Brooooooklyn Thanks! I'll try. However, maybe the fact that `JsFunction` shouldn't be used in favor of `ThreadsafeFunction ` for async function is good to be documented explicitly. How about your opinion?

**Comment by Brooooooklyn** [comment]
> However, maybe the fact that JsFunction should be replaced by ThreadsafeFunction for async function is good to be documented explicitly.

Yes, you are right
