### ISSUE TITLE
Not possible to have a property on a constructor reference an object or another constructor?

### ISSUE THREAD

**Issue by nobu-sh** [napi-rs/napi-rs#1655]
I apologize if this is noobish but I couldn't find relevant information anywhere or any issues similar. I simply want to be able to have a constructor that can have properties that are objects or constructors.

EX:
```rs
#[napi(constructor)]
pub struct Bean {
  pub name: String,
  pub age: i32,
}

#[napi(constructor)]
pub struct TinCan {
  pub beans: Vec<Bean>,
}
```

Errors:
![image](https://github.com/napi-rs/napi-rs/assets/61068742/b0368a43-e7ee-45f3-ae25-91db87e67759)

**Comment by Brooooooklyn** [comment]
The `FromNapiValue` won't be implemented for `#[napi]` class, you should use `Reference<Bean>` or `SharedReference<Bean>` here. See https://github.com/napi-rs/napi-rs/blob/main/examples/napi/src/reference.rs for example

**Comment by nobu-sh** [comment]
Ah ok thanks. I am still having a bit of trouble after looking at that example specifically https://github.com/napi-rs/napi-rs/blob/main/examples/napi/src/reference.rs#L136C33-L136C33. Editing the above example to closer match what you have given it looks something like: 

```rs
#[napi(constructor)]
pub struct Bean {
  pub name: String,
  pub age: i32,
}

#[napi]
pub struct TinCan {
  beans: Option<Reference<Vec<Bean>>>,
}

#[napi]
impl TinCan {
	#[napi(constructor)]
	pub fn new() -> Self {
	  Self {
	    beans: None,
	  }
	}

	#[napi(getter)]
	pub fn beans(&self, env: Env) -> Result<Reference<Vec<Bean>>> {
    if let Some(beans) = &self.beans {
        return beans.clone(env);
    }

    let beans = vec![
      Bean {
        name: "Bob".to_string(),
        age: 1,
      },
    ];

    let beans = env.create_reference(beans)?;
  }
}
```
![image](https://github.com/napi-rs/napi-rs/assets/61068742/16da352d-095e-4a80-9472-033ff9b5e3f0)

**Comment by nobu-sh** [comment]
I don't know if this is "proper" but after a lot of messing around I found this works.

```rs
#[napi(constructor)]
#[derive(Clone)]
pub struct Bean {
  pub name: String,
  pub age: i32,
}

impl FromNapiValue for Bean {
  unsafe fn from_napi_value(env: napi_env, value: napi_value) -> Result<Self> {
    let object = Object::from_napi_value(env, value)?;

    let name: String = object.get_named_property("name")?;
    let age: i32 = object.get_named_property("age")?;

    Ok(Bean {
      name,
      age,
    })
  }
}

#[napi(constructor)]
pub struct TinCan {
  pub beans: Vec<Bean>,
}
```

**Comment by jzeuzs** [comment]
> The `FromNapiValue` won't be implemented for `#[napi]` class, you should use `Reference<Bean>` or `SharedReference<Bean>` here. See https://github.com/napi-rs/napi-rs/blob/main/examples/napi/src/reference.rs for example

Same here @Brooooooklyn, I'm also having trouble understanding the example. But, the example that @nobu-sh gave works.
