### ISSUE TITLE
Serde JSON Value no longer supported?

### ISSUE THREAD

**Issue by nobu-sh** [napi-rs/napi-rs#1674]
In the docs it states being able to use `serde_json::Value` as a return type or parameter for a function but attempting to do so does not function:

```rs
#[napi(object)]
pub fn test() -> serde_json::Value {
  Value::String("test".to_string())
}
```
```log
required for `Value` to implement `napi::bindgen_prelude::ToNapiValue`
```

`serde_json::Map` also has the same issue. I need a way to handle arbitrary objects and arbitrary values. Sadly it appears both ways spec'd do not function.

**Comment by sreeni-wayvo** [comment]
You must be missing the "serde-json" feature!
