### ISSUE TITLE
triples configuration option is ignored on Windows

### ISSUE THREAD

**Issue by dominic-simplan** [napi-rs/napi-rs#1678]
Hello,

I am trying to build https://github.com/napi-rs/cross-build on Windows.

However, the only output is the x64 node module for Windows. It doesn't seem to build the other variants which are defined in triples.additional.
Here is the output with debug enabled:

```
PS C:\Projects\Playground\cross-build\01-pure-rust> yarn build
  napi:build Start parse toml +0ms
  napi:build Current triple is: x86_64-pc-windows-msvc +185ms
  napi:build Run cargo build --release +1ms
  napi:build Platform: {
  napi:build   "platform": "win32",
  napi:build   "arch": "x64",
  napi:build   "abi": "msvc",
  napi:build   "platformArchABI": "win32-x64-msvc",
  napi:build   "raw": "x86_64-pc-windows-msvc"
  napi:build } +0ms
    Finished release [optimized] target(s) in 0.15s
  napi:build Dylib name: napi_cross_build_01_pure_rust +220ms
  napi:build Platform: win32 +0ms
  napi:build Platform name: .win32-x64-msvc +0ms
  napi:build remove old binary [01-pure-rust.win32-x64-msvc.node] +1ms
  napi:build Write binary content to [01-pure-rust.win32-x64-msvc.node] +2ms
  napi:build do not find tmp type file. skip type generation +2ms
```

What could be the reason? Do I need to install anything else?

By the way, in the [example for the configuration here](https://napi-rs.github.io/napi-rs/cli/#--config-c) "addition" instead of "additional" is used.

**Comment by dominic-simplan** [comment]
Thank you, yarn build --target works, I just wanted to avoid calling the build multiple times when there is a convenient configuration option avaiable 🙂 

So you are saying that the triples configuration option is not supported on Windows?

**Comment by Brooooooklyn** [comment]
> So you are saying that the triples configuration option is not supported on Windows?

No I mean the zig cross compiling is not fully available on Windows
