### ISSUE TITLE
Allow generation of non const enums

### ISSUE THREAD

**Issue by samvdst** [napi-rs/napi-rs#1689]
`@napi-rs/cli` always generates `const enum`. The build flag `--const-enum` defaults to true, which means there's no way to disable it. If you don't set the flag, it's true, and if you set it, it's also true.

I have seen the issue #1345 and also PRs #1527, #1647. None of them resolved the issue for me.

**Comment by RobinMalfait** [comment]
Hey!

Just ran into this issue myself as well. Looking at the library they use ([clipanion](https://mael.dev/clipanion/docs/api/option#optionboolean)) it looks like setting `--const-enum false` is not a real thing. Instead passing `--no-const-enum` solves the issue for me. Hope that helps!

**Comment by samvdst** [comment]
Hey @RobinMalfait, thanks for the tip. I basically created this PR because I couldn't find a way to negate these options in the documentation and help messages. Ideally, we should update the documentation to include these negated options. I haven't found the time to do that yet.
