### ISSUE TITLE
feat: generate wrapper for async function (due to VERY weird behavior for error of async function)

### ISSUE THREAD

**Issue by jjangga0214** [napi-rs/napi-rs#1706]
Let's say I have an async function that can throw an error.
```rs
#[napi]
pub async fn run() -> napi::Result<()> {
  Err(napi::Error::from_reason("this is error"))
}
```

I expected this code would work.

```ts
async function run2() {
  run()
}

try { 
  await run2()
} catch { 
  console.log("catched")
}
```

But an error happens.

```bash
[Error: this is error] { code: 'GenericFailure' }
```

If I change the code like this,

```ts
async function run2() {
  await run() // <== I awaited!
}

try { 
  await run2()
} catch { 
  console.log("catched")
}
```

Then it works!

```bash
catched
```

I think this is very weird behavior, which is worth to be documented.

How do you think?

Thanks :)

**Comment by jjangga0214** [comment]
I think it may be useful for napi-rs to **generate** a wrapper function for an async function. For example, `run2` is the wrapper for `run`.

**Comment by Brooooooklyn** [comment]
@jjangga0214 you don't know JavaScript. This behavior is nothing to do with NAPI-RS. Try this pure JavaScipt version:

```js
async function run() {
  return Promise.reject('error');
}

async function run2() {
  try {
    run();
  } catch {
    console.log('catch');
  }
}

run2();

```

**Comment by jjangga0214** [comment]
Sorry, I was confused. Thanks.
