### ISSUE TITLE
Environment updated from node is not reflected in Rust code behind NAPI

### ISSUE THREAD

**Issue by stevenliebregt** [napi-rs/napi-rs#1707]
I have a Rust library that reads certain configuration values from the environment using `std::env::var`.

In the node process that uses that I have `process.env.MY_KEY = 'new value'`; which used to work with a native JS version of the library, but now that I'm using NAPI and Rust when I debug print in Rust I still see the old value of `MY_KEY` in the environment.

**Comment by Brooooooklyn** [comment]
This is expected, because `process.env.XX = YYY` doesn't change the actually environment variable on your system

**Comment by stevenliebregt** [comment]
But it should for the current process right? I'm not a 100% clear on how NAPI calls the Rust, but I thought it would run in the same process as the Node, and thus inherit the changed environment

**Comment by Brooooooklyn** [comment]
`process.env.XX` is a simple Node.js object, it will not reflect any changes on your system-level environment variable. Not process level and thread level.

**Comment by stevenliebregt** [comment]
Right, I misunderstood how that worked, thanks for enlightening me!
