### ISSUE TITLE
Build creates JS exports that no longer exist

### ISSUE THREAD

**Issue by sbking** [napi-rs/napi-rs#1719]
When I run `napi build`, the resulting `index.js` and `.d.ts` files contain exports that are no longer in the rust source code anywhere. I've tried deleting the `target` dir and deleting all build files, clearing cargo cache, etc. The only thing that works is to change the name of my package in `Cargo.toml`, but the same issue eventually happens for the new package name as well.

**Comment by kovapatrik** [comment]
This is still happening to me using the latest alpha version. Is there a workaround for this? The package name change is indeed working, but I don't want to change it.

**Comment by Brooooooklyn** [comment]
@kovapatrik use `napi build --no-dts-cache` can help

**Comment by kovapatrik** [comment]
It's working with this flag, thank you!
