### ISSUE TITLE
How to bypass  cargo channel flag like "+nightly-x86_64-pc-windows-msvc" to napi build command?

### ISSUE THREAD

**Issue by lencil** [napi-rs/napi-rs#1729]
How to bypass  cargo channel flag like "+nightly-x86_64-pc-windows-msvc" to napi build command?

**Comment by Brooooooklyn** [comment]
`CARGO="cargo +nightly-x86_64-pc-windows-msvc" yarn build`

**Comment by lencil** [comment]
> `CARGO="cargo +nightly-x86_64-pc-windows-msvc" yarn build`

in windows, it should be
set CARGO=cargo +nightly-x86_64-pc-windows-msvc && napi build
