### ISSUE TITLE
error: failed to run custom build command for `proc-macro2 v1.0.67`

### ISSUE THREAD

**Issue by Darmody** [napi-rs/napi-rs#1751]
<img width="1541" alt="Screenshot 2023-10-10 at 22 38 13" src="https://github.com/napi-rs/napi-rs/assets/6788752/29dd89b7-c9e1-4898-9407-9e6891aa5366">

The app is inside a mono repo. And there is no other difference from the default app created by Napi CLI.

You can see the code from https://github.com/pleisto/flappy/pull/47

**Comment by Darmody** [comment]
Sometimes the error disappeared and the action ran successfully. It's wired.

**Comment by forehalo** [comment]
It's time to migrate to proc-macro v2
