### ISSUE TITLE
How to deal with buffer that are not U8

### ISSUE THREAD

**Issue by MatthD** [napi-rs/napi-rs#1757]
I have in JS a buffer to send to the napi.rs programm

It's created with a code like this

```typescript
  const test: Buffer = Buffer.from(data.samples.buffer);
```

And `data.sample` are of type `Int16Buffer`

I am doing:

```rust
 fn re_sample_buffers(args: ArgsAudioBuffer) -> Buffer {
  let input_slice = input_buffer.to_vec(); // here I got a vec<u8>
  ...
  input_slice.into()
}
```

How to deal with the fact that my Buffer input param can have sub type of u8 or int16 ..  ? I am afraid this will lead to memory issue
Futhermore later in my program I need to know from which king of data I am manipulating  and return a buffer of int16 (and not u8)

**Comment by Brooooooklyn** [comment]
Try the `TypedArray` like `Uint32Array` https://github.com/napi-rs/napi-rs/blob/main/examples/napi/src/typed_array.rs#L21

**Comment by MatthD** [comment]
Thanks !
