### ISSUE TITLE
How to call one "function" but only once for enable debug

### ISSUE THREAD

**Issue by MatthD** [napi-rs/napi-rs#1761]
I am unable to use the log crate library

I need to 

```rust
use log::debug;

.. //Somewhere in the code I should enable it depending on the env variable via env_logger::init();
```

But AFAIK we don't have main function so how and where to enable it (only once ) ? 

I may think to use class constructor but I would prefer to only have exported functions

**Comment by Brooooooklyn** [comment]
Try this:

```rust
use napi::module_init;

#[module_init]
fn init() {
  env_logger::init();
}
```

**Comment by MatthD** [comment]
Thanks did not found documentation about this ! Hope it will help other people ;)

**Comment by Brooooooklyn** [comment]
> Thanks did not found documentation about this ! 

I'll add it to the documentation! Thanks for report it.

**Comment by loynoir** [comment]
@Brooooooklyn

Would be nice to add it to more visible place, if it had been added.

Search same problem and reach here.
