### ISSUE TITLE
GitHub Actions Fails With Timeout Error

### ISSUE THREAD

**Issue by lunaisnotaboy** [napi-rs/napi-rs#1762]
Hi there!

I recently forked the repository [misskey-dev/gotoh](https://github.com/misskey-dev/gotoh) from another repository in my organization, and GitHub Actions keeps taking well over five hours before timing out. Is there a way to fix this, or am I missing something?

**Comment by Brooooooklyn** [comment]
See here: https://napi.rs/blog/freebsd-actions-update

**Comment by lunaisnotaboy** [comment]
Thanks!
