### ISSUE TITLE
How to deal with i16 data for buffer ?

### ISSUE THREAD

**Issue by MatthD** [napi-rs/napi-rs#1764]
I have an incoming  buffer that contains i16 data

I should return a buffer that contain i16 data (not u8)

I have an issue telling me that it should be u8 , how to deal with this ? BTW I just cannot convert to u8 because it's audio and will lost data

```rust
#[napi]
pub fn re_sample_buffers(data: Buffer) -> Buffer {
  // ... some operations...
  let vec_i16: Vec<i16> = output_data.iter().map(|&f| f as i16).collect();
  vec_i16.into() // ! here is the issue
}

```

**Comment by bmacnaughton** [comment]
A buffer is just a sequence of 8 bit bytes, no matter how you choose to interpret those bytes.

there are probably other ways to do it, but this should work.

```rust
fn main() {
    let output_data: &[i16] = &[11i16, 155i16, 207i16, -1i16];
    let mut buffer: Vec<u8> = Vec::with_capacity(output_data.len() * 2);
    
    for data in output_data {
        let hi: u8 = (data >> 8) as u8;
        let lo: u8 = (data & 0xFF) as u8;
        buffer.push(hi);
        buffer.push(lo);
    }
    
    // return buffer.into()
    
    // read the buffer in javascript using buffer.readInt16(index, endian)
}
```
rust playground [link](https://play.rust-lang.org/?version=beta&mode=debug&edition=2015&code=%0Afn+main%28%29+%7B%0A++++let+output_data%3A+%26%5Bi16%5D+%3D+%26%5B11i16%2C+155i16%2C+207i16%2C+-1i16%5D%3B%0A++++let+mut+buffer%3A+Vec%3Cu8%3E+%3D+Vec%3A%3Awith_capacity%28output_data.len%28%29+*+2%29%3B%0A++++%0A++++for+data+in+output_data+%7B%0A++++++++let+hi%3A+u8+%3D+%28data+%3E%3E+8%29+as+u8%3B%0A++++++++let+lo%3A+u8+%3D+%28data+%26+0xFF%29+as+u8%3B%0A++++++++buffer.push%28hi%29%3B%0A++++++++buffer.push%28lo%29%3B%0A++++%7D%0A++++%0A++++%2F%2F+return+buffer.into%28%29%0A++++%0A++++%2F%2F+read+the+buffer+in+javascript+using+buffer.readInt16%28index%2C+endian%29%0A%7D)

**Comment by MatthD** [comment]
Thanks but in your example you are using vec of u8 which will truncate my i16 data to a max/min of 255 & 0.
The issue I have is with the buffer usage of Napi.rs it seems [it's hardcoded it's data type here](https://github.com/napi-rs/napi-rs/blob/main/crates/napi/src/bindgen_runtime/js_values/buffer.rs#L26)

But according to node.js documentation  depending on the data you send to buffer, a buffer [can take int16Array as args and will not truncate this data](https://nodejs.org/api/buffer.html#static-method-bufferfromarraybuffer-byteoffset-length)

**Comment by bmacnaughton** [comment]
My example does not truncate the data. It convert the i16 data (5 values) to u8 data (10 values). They can be "reassembled" in node using one of the `buffer.readInt16LE()` or `buffer.readInt16BE()` functions.

Node explicitly allows a JavaScript [Int16Array ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array)to be converted into a buffer, but that's not a JavaScript Int16Array you're working with in rust.

Please look at the data I've provided - there is not magic there. Buffers always contain bytes; how you interpret them is the only thing that is in question.

**Comment by bmacnaughton** [comment]
I understand this is not familiar territory for you, but I also know exactly how this works. The bytes have to be recombined in the buffer that is passed to node - buffers are views into memory. Memory is laid out in bytes. Buffers cannot hold i16s because an i16 does not fit in a single byte. Therefore, you have to recombine them using one of the `readInt16xx()` functions. Or you can manually do it, but it's a little bit of a pain because you want signed values.

Here's how to use the buffer I created in node:

```js
> b = Buffer.from([0, 11, 1, 64, 0, 207, 255, 255, 255, 254])
<Buffer 00 0b 01 40 00 cf ff ff ff fe>
> b.readInt16BE(2)
320
```

**Comment by bmacnaughton** [comment]
Just to show that it returns the original data. All you need to do is push the values into an array:

```js
> b = Buffer.from([0, 11, 1, 64, 0, 207, 255, 255, 255, 254])
<Buffer 00 0b 01 40 00 cf ff ff ff fe>
> b.readInt16BE(2)
320
> for (let i = 0; i < b.length; i += 2) {
... console.log(b.readInt16BE(i));
... }
11
320
207
-1
-2
undefined
>

```

**Comment by MatthD** [comment]
Thank you for all of this your explanation was very clear and helped a lot !
