### ISSUE TITLE
Default `win32-x` package naming conversion triggers spam detection during npm publish

### ISSUE THREAD

**Issue by tamascsaba** [napi-rs/napi-rs#1767]
I have started to use `napi-rs`. My project is [node-rs-krb5](https://github.com/tamascsaba/node-rs-krb5).
I can tell I really how `napi-rs` works. 👍  

My first experience is when I trying to publish a `win32-x` package to npm, it triggers the npm spam detector.
More details here: https://github.com/tamascsaba/node-rs-krb5/actions/runs/6696124416/job/18193428910
It is not only my problem: https://blog.orhun.dev/packaging-rust-for-npm/

Possible solutions:
- write to the npm support (they solved under a day)
- use different package naming conversion

**Comment by Brooooooklyn** [comment]
See here https://napi.rs/docs/introduction/getting-started#deep-dive
