### ISSUE TITLE
How about performance with buffer and napi object?

### ISSUE THREAD

**Issue by southorange0929** [napi-rs/napi-rs#1799]
Now, i know two method to exchange complex object with rust and js.
1. use `napi(object)`
2. use `buffer`,need serialize to `string` ,then convert to `vec<u8>`  and `toString()` or `toJSON()` with js.

I'm not sure which has better performance,or any other method to get better performance.
Is there any suggestion for me? Thanks.

**Comment by Brooooooklyn** [comment]
For huge objects, Buffer + json is much faster.

**Comment by southorange0929** [comment]
Thanks a lot
