### ISSUE TITLE
feat: panic hook

### ISSUE THREAD

**Issue by jjangga0214** [napi-rs/napi-rs#1802]
Hi! 

In a general rust project, we can set panic hook like this.

```rs
#[tokio::main]
async fn main() {
    std::panic::set_hook(Box::new(move |info| {
        let stacktrace = std::backtrace::Backtrace::force_capture();
        println!("Got panic. @info:{}\n@stackTrace:{}", info, stacktrace);
        std::process::abort();
    }));
}
```

However, there is no `main` rust function with `napi-rs`.
There're just several functions.

```rs
#[napi]
pub fn foo() { /* ... */ }

#[napi]
pub async fn bar() { /* ... */}

#[napi]
pub async fn qux() {
  tokio::spawn(async move { /* ... */ });
  loop { /* ... */ }
}
```

Then how we can set a hook for panic?

Should we set it on every function?
If so, what happens if `std::process::abort()` is called in the hook?

Thanks.

**Comment by Brooooooklyn** [comment]
`#[napi(catch_unwind)]`

**Comment by jjangga0214** [comment]
Thanks!
(I think it worths to be documented, but wonder your thought)
