### ISSUE TITLE
Support `napi` proc macro with Task

### ISSUE THREAD

**Issue by segevfiner** [napi-rs/napi-rs#1811]
Instead of having to code the conversion of the result yourself using `napi_env`, it would be cool to be able to use the same conversions done by the `napi` derive macro with `Task`s.

**Comment by segevfiner** [comment]
I think this same idea also applies to thread safe functions. Where you also need to supply a callback to convert to a JS type from a Rust type.

**Comment by Brooooooklyn** [comment]
You can add `#[napi]` on the `impl Task for ...` like this: https://github.com/napi-rs/napi-rs/blob/main/examples/napi/src/task.rs#L55

For `ThreadsafeFunction`, I have a plan to refactor it to support TypeScript generation
