### ISSUE TITLE
symbol not found in flat namespace '_napi_create_error'

### ISSUE THREAD

**Issue by HomyeeKing** [napi-rs/napi-rs#1818]
maybe some llvm dependencies have problem? 

reproduce repo: https://github.com/HomyeeKing/gito/tree/repro

**Comment by Brooooooklyn** [comment]
how could I reproduce it?

**Comment by HomyeeKing** [comment]
@Brooooooklyn  sorry, forget about the reproduce repo link

**Comment by Brooooooklyn** [comment]
@HomyeeKing you should enable `noop` feature in `napi-derive` crate while using NAPI-RS lib as a crate:

`packages/local_dep/Cargo.toml`

```diff
+[features]
+independent = ["napi-derive/noop"]
```

`packages/cli/Cargo.toml`

```diff
-local_dep = {path = "../local_dep", version = "1.0.3"}
+local_dep = {path = "../local_dep", version = "1.0.3", features = ["independent"]}
```

**Comment by HomyeeKing** [comment]
thanks! it's all good now.  
by the way, do you think it's necessary to explain this case to the document?

**Comment by Brooooooklyn** [comment]
@HomyeeKing thanks, I'll add it into the document later
