### ISSUE TITLE
pnpm missing from docker images

### ISSUE THREAD

**Issue by Cammisuli** [napi-rs/napi-rs#1840]
Hey there!

We're currently using `ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine` in our release pipeline, and noticed that `pnpm` was removed from the base image in https://github.com/napi-rs/napi-rs/pull/1833. 

What was the main reason for this? We can install pnpm ourselves, but we just want to make sure we're not missing anything by the removal of it in the base image. 

thanks!

**Comment by Brooooooklyn** [comment]
I think `pnpm` was accidentally removed, I will fix this issue:  https://github.com/napi-rs/napi-rs/actions/runs/7103600609
