### ISSUE TITLE
How about remove RS-CLI with type-def?

### ISSUE THREAD

**Issue by southorange0929** [napi-rs/napi-rs#1896]
<img width="1074" alt="image" src="https://github.com/napi-rs/napi-rs/assets/32590310/a98400a5-821a-4c24-bbf2-5a172b4bbc37">

Is it possible to remove this logic for us? It looks like useless now, but i'm not sure there are some special logic.

**Comment by Brooooooklyn** [comment]
This is for compatibility with the old CLI, to prevent someone from installing the old version of CLI and the new version of napi-derive.

**Comment by southorange0929** [comment]
So it can be  removed  with 3.0 release?

**Comment by Brooooooklyn** [comment]
> So it can be removed with 3.0 release?

Yes
