### ISSUE TITLE
feature request: add support for `chrono::DateTime<FixedOffset>`

### ISSUE THREAD

**Issue by naskya** [napi-rs/napi-rs#1902]
Thanks to #1069 and #1601, currently we can use the [`chrono`](https://docs.rs/chrono/latest/chrono/) crate to some extent, and I'd be very grateful if you could add [`chrono::DateTime<FixedOffset>`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#impl-DateTime%3CFixedOffset%3E) support as well. I'm using this type for database processing and get the following errors when I try to use `#[napi_derive::napi(object)]`:

```
error[E0277]: the trait bound `chrono::DateTime<FixedOffset>: NapiRaw` is not satisfied
    |         ^^^^^^^^^^ the trait `NapiRaw` is not implemented for `chrono::DateTime<FixedOffset>`
    = note: required for `chrono::DateTime<FixedOffset>` to implement `ToNapiValue`
error[E0277]: the trait bound `chrono::DateTime<FixedOffset>: NapiValue` is not satisfied
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `NapiValue` is not implemented for `chrono::DateTime<FixedOffset>`
    = note: required for `chrono::DateTime<FixedOffset>` to implement `FromNapiValue`
```

Thank you for developing this amazing tool!

**Comment by Brooooooklyn** [comment]
Close in https://github.com/napi-rs/napi-rs/pull/2074
