### ISSUE TITLE
support `napi build --lib` flag

### ISSUE THREAD

**Issue by OmarTawfik** [napi-rs/napi-rs#1906]
Using NAPI with a crate that has multiple targets (lib, bin, etc...) currently is problematic, and causes build/linking issues for the `bin` target (more info https://github.com/rust-lang/cargo/issues/8628).

Currently `@napi-rs/cli v2.16` supports customizing the `cargo build` command it invokes by supporting the same flags like `--target`, `--features`, and `--bin`:

```log
$ napi build --help

... other flags
  --target #0                       Bypass to cargo build --target
  --features #0                     Bypass to cargo build --features
  --bin #0                          Bypass to cargo build --bin
... other flags
```

I wonder if it is possible to also add/support the `--lib` flag to `napi build`?

Otherwise, we are forced to either monkey-patch `@napi-rs/cli/scripts/index.js`, or have complex workarounds/wrappers in our `Cargo.toml` setup to ensure only the `[lib]` target is picked up during the build.

Thank you!

**Comment by OmarTawfik** [comment]
@Brooooooklyn thank you so much for looking at this!
I don't know when is next `@napi-rs/cli` release. I wonder if you already started on it? Otherwise, please let me know if I can help with anything.

**Comment by Brooooooklyn** [comment]
@OmarTawfik In the @napi-rs/cli, you can use `napi build --release -- --lib` to pass `--lib` to cargo, it will be released very soon

**Comment by Brooooooklyn** [comment]
In current stable release, you can use `--cargo-flags` to pass flags to `cargo` command like this: `napi build --release --platform --cargo-flags="--lib"`
