### ISSUE TITLE
Does napi-rs support users to compile their own binding when installing packages

### ISSUE THREAD

**Issue by luckyadam** [napi-rs/napi-rs#1932]
The current bindings are pre compiled during CI, then directly published to the NPM package, and developers directly download the pre compiled bindings when installing dependencies.

However, our project encountered an issue where pre compiled bindings cannot run perfectly in the developer's system, especially in various Linux systems. Is there a solution to this and is it possible for developers to compile bindings when installing dependencies.

Related issues:
https://github.com/NervJS/taro/issues/15147
https://github.com/NervJS/taro/issues/15187
https://github.com/NervJS/taro/issues/15061

**Comment by Brooooooklyn** [comment]
You can add a `postinstall` script in your package to let the user decide whether to enable the self compile step: https://github.com/Brooooooklyn/pinyin/blob/main/postinstall.js
