### ISSUE TITLE
feature request: Add ability to represent nullable TypeScript fields

### ISSUE THREAD

**Issue by naskya** [napi-rs/napi-rs#1944]
## Problem
Let's say you want to handle some HTTP requests (or whatever), whose payload contains a nullable field:
```typescript
interface Payload {
    id: number
    name: string | null
}

function do_stuff(payload: Payload) {}
```

And you want to accept these kinds of payloads:

```typescript
{id: 1, name: null}
{id: 2, name: 'kitan'}
```

The equivalent implementation in Rust would be something like this:

```rust
#[napi(object)]
pub struct Payload {
    pub id: u32,
    pub name: Option<String>,
}

#[napi]
pub fn do_stuff(payload: Payload) {}
```

But napi exports the following type definition,

```typescript
export interface Payload {
    id: number
    name?: string
}

export function do_stuff(payload: Payload): void
```

so it produces an error when `null` is passed in the optional field:
```typescript
// Error: Failed to convert JavaScript value `Null` into rust type `String`
do_stuff({id: 1, name: null})
```

Given that such use cases are pretty common, I think napi should also provide a way to handle `null`s in JavaScript objects.

## Proposal

To handle such cases, I suggest that napi exports the following type definition from the Rust code above:

```typescript
export interface Payload {
    id: number
    name?: string | null
}

export function do_stuff(payload: Payload): void
```

So it works in both cases:

```typescript
do_stuff({id: 1, name: null})     // Payload {id: 1, name: None}
do_stuff({id: 2, name: 'kitan'})  // Payload {id: 2, name: Some("kitan")}
```

**Comment by Brooooooklyn** [comment]
@naskya After careful consideration, I think it's more appropriate to keep the original semantics of Option. Your scenario can be expressed as `Either<String, Null>`.

**Comment by naskya** [comment]
@Brooooooklyn Thank you for your reply and consideration. I'm so glad to see that you are maintaining this project with a careful thought.

To give another example, I'm using [SeaORM](https://github.com/SeaQL/sea-orm) to manipulate databases, and it automatically turns the following database schema

```sql
CREATE TABLE "foo" (
    "field_a" boolean NOT NULL,
    "field_b" boolean
)
```

into this structure in Rust, which makes sense to me because `field_b` may or may not be set,

```rust
pub struct Foo {
    pub field_a: bool,
    pub field_b: Option<bool>,
}
```

which will be bound to the following interface by napi-rs:

```typescript
export interface Foo {
    field_a: boolean
    field_b?: boolean
}
```

but `field_b` is treated as `boolean | null` in other database manipulation tools for TypeScript (such as TypeORM), which also makes sense because it's not "`NOT NULL`". So unfortunately there is a sort of disharmony between Rust and TypeScript. I'm actually very struggling with that now, and I expect there are many other such scenarios.

Of course, if you feel this design (converting `a: Option<T>` field into `a?: T | null`) contradicts to the project's philosophy, it's okay to mark this as wontfix, and in that case I'll start my journey to find a workaround...

Anyways, thanks for maintaining this amazing tool! I really appreciate that :blue_heart:

**Comment by naskya** [comment]
Or, how about adding a new attribute like `#[napi(use_nullable = true)]` which converts `Option<T>` fields into `T | null`, so it doesn't break any backward compatibility?

**Comment by jimsimon** [comment]
Is it possible to configure these examples to produce a type that allows both null and undefined?

```rust
#[napi(object)]
pub struct Animal {
  pub name: String,
  pub kind: Option<u32>,
}
```

```typescript
export interface Animal {
  name: string
  kind?: number | null
}
```

**Comment by sup39** [comment]
Hi @jimsimon,

You can use `Either` without `use_nullable` in this case:
```rust
use napi::bindgen_prelude::{Either, Null};

#[napi(object)]
pub struct Animal {
  pub name: String,
  pub kind: Option<Either<u32, Null>>,
}
```

You can find more examples in https://github.com/napi-rs/napi-rs/issues/1986#issuecomment-1976678735.
