### ISSUE TITLE
#[napi(constructor)] broken on struct

### ISSUE THREAD

**Issue by lbarthon** [napi-rs/napi-rs#1959]
Since the change made in https://github.com/napi-rs/napi-rs/issues/1952, structs have an `IsEmptyStructHint` param. This breaks the #[napi(constructor)] annotation, on both empty and non-empty struct.

There are other ways to make a constructor, but this one being documented here https://napi.rs/docs/concepts/class#constructor - it should be fixed or documentation updated, if that's the easiest!

Reproduction code:
```rust
#[napi(constructor)]
pub struct Foo {
    pub nbr: u32,
}
```

Note: the reproduction works whether the struct is empty or not.

This seems to also break the following
```rust
#[napi]
pub struct Foo;

#[napi]
impl Foo {
    #[napi(constructor)]
    pub fn new() -> Self {
        Self {}
    }
}
```

**Comment by Brooooooklyn** [comment]
@lbarthon have you upgraded both `napi` and `napi-derive` to the latest version?

**Comment by Boshen** [comment]
Also breaking in Rspack 

```
error[E0282]: type annotations needed
  --> crates/node_binding/src/lib.rs:61:1
   |
61 | #[napi]
   | ^^^^^^^ cannot infer the value of const parameter `IsEmptyStructHint` declared on the method `construct`
   |
   = note: this error originates in the attribute macro `napi` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by Brooooooklyn** [comment]
I forgot to upgrade `napi-derive-backend` version in `napi-derive`. I'll publish a new version.
