### ISSUE TITLE
Cannot convert JSFunction to JSObject

### ISSUE THREAD

**Issue by victorteokw** [napi-rs/napi-rs#1988]
Hi @Brooooooklyn,
This commit: https://github.com/napi-rs/napi-rs/commit/aeb0b4766d9554519eb4002e02910ebb2b4a0b36

Before:
```rust
        let util = require.call(None, &[env.create_string("node:util").unwrap().into_unknown()])?.coerce_to_object()?;
        let inspect: JsObject = util.get_named_property("inspect")?;
```

After:
```rust
        let util = require.call(None, &[env.create_string("node:util").unwrap().into_unknown()])?.coerce_to_object()?;
        let inspect_f: JsFunction = util.get_named_property("inspect")?;
        let inspect: JsObject = inspect_f.coerce_to_object()?;
```

The API becomes broken after upgrade to napi 2.16.0, and I must update API to be this. I'm just afraid of a lot of libraries would be broken after upgrading to this version of napi.

**Comment by Brooooooklyn** [comment]
@victorteokw you are relying on a behavior that was considered a bug in the previous version, please see the context: https://github.com/napi-rs/napi-rs/issues/1641

You can avoid a `coerce_to_object` call by changing `util.get_named_property("inspect")?` to `util.get_named_property_unchecked("inspect")?`

**Comment by victorteokw** [comment]
Thanks @Brooooooklyn
