### ISSUE TITLE
Unsoundness of `External`

### ISSUE THREAD

**Issue by h-a-n-a** [napi-rs/napi-rs#1994]
I was trying to debug a segmentation fault issue. This case happens when an `External` value passed back from the JS side and trying to use it later time and after I manually expand the macro and eagerly clone the value in `External`, the problem went away. 

Theoretically, when an `External` value being transferred from Rust to JS and then passed back to Rust, v8 garbage collector would probably collect this value depending on the size of the value being contained. In NAPI-RS, a `napi_finalize` callback is provided and this callback will `drop` the underlying value if it's being called. However, at the same time, `External` is not dropped. So it's ok to use it, which causes the memory issue and leads to potential segmentation fault.

I checked the implementation from neon, they seems to have a bounded lifetime for `External` to avoid it being garbage collected https://github.com/neon-bindings/neon/blob/50c74c0554fc90495157879a5b32c78bd1676016/crates/neon/src/types_impl/boxed.rs#L265.
What's your recommendation for NAPI-RS to solve this issue?

**Comment by Brooooooklyn** [comment]
`External` shouldn't impl `FromNapiValue` trait, it should impl the `FromNapiRef` and `FromNapiMutRef` traits instead
