### ISSUE TITLE
declare_class macro, like declare_types in neon

### ISSUE THREAD

**Issue by Brooooooklyn** [napi-rs/napi-rs#2]
https://api.neon-bindings.com/neon/macro.declare_types.html

**Comment by cztomsik** [comment]
hey, not sure what is the status of this project but I've actually turned away from neon and it's macro approach (very hard to track compiler errors) - what I have instead is a set of flat functions and so far it works great.
[here's an example](https://github.com/cztomsik/node-webrender/blob/master/native/src/lib.rs)

So maybe you might want to reconsider this too.

BTW: I've made few changes needed for my project, I can make a pull with some of those if you're interested

**Comment by Brooooooklyn** [comment]
Oh that's really great if you want contribute you changes to this project!
Honestly I don't have enough time in this project to continue improve it.
So, feel free to make changes on it.

**Comment by cztomsik** [comment]
ok, I will send a PR once it gets little more stable
