### ISSUE TITLE
cli: pass --locked and --frozen over to cargo

### ISSUE THREAD

**Issue by selfisekai** [napi-rs/napi-rs#2011]
currently, cargo lockfiles cannot be enforced when building

**Comment by Brooooooklyn** [comment]
`--cargo-flags="--locked --frozen"`

**Comment by matthme** [comment]
Has this been removed again? With napi 3.1.3 I'm getting this error:

`Unknown Syntax Error: Invalid option name ("--cargo-flags=--locked")`

And I can't find a similar option with `napi build --help`

**Comment by Brooooooklyn** [comment]
@matthme `napi build -- --locked`

**Comment by matthme** [comment]
Great, thanks! Would be good to mention in the [migration guide](https://napi.rs/docs/more/v2-v3-migration-guide) I think.
