### ISSUE TITLE
What's the best way to cross-platform? (App cross-platform but native lib is not)

### ISSUE THREAD

**Issue by Zagrios** [napi-rs/napi-rs#2046]
Hi,

I've created [regedit-rs](https://github.com/Zagrios/regedit-rs) which is only for Windows. However, when it's used with cross-platform apps, the import results in an error because the .node file does not exist (for example, when the app is launched on Linux).

I had this issue in one of my own projects and recently an issue was reported on the [regedit-rs](https://github.com/Zagrios/regedit-rs) repo.

This is how I deal with this issue for now: Zagrios/regedit-rs#1.

And I wonder if there is a better way to manage specific platform native libraries with cross-platform apps. 🤔

I think i can add all platform in the native lib and return function that's throws error when its not the right platform, but idk if this is the right way to do that 🤔

**Comment by Brooooooklyn** [comment]
Platform-related dependencies should be treated as `optionalDependencies`:
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies

**It is still your program's responsibility to handle the lack of the dependency**
