### ISSUE TITLE
[napi] Macro compiles & expands but doesn't register exports

### ISSUE THREAD

**Issue by aaronclong** [napi-rs/napi-rs#2048]
I'm kind of losing my mind over this, but I can't figure out a function and struct annotated with `[napi]` failed to get registered in the nodejs module. I've tried hundred iterations but nothing works. Admittedly, I am extremely weak at Rust programming, and can be making several mistakes. You can see the code here: https://github.com/turingscript/tokenizers/blob/8ee1e65e5cb190f3e451865d29d807d120b5b072/bindings/node/src/bpe_trainers.rs

<img width="561" alt="image" src="https://github.com/napi-rs/napi-rs/assets/7354981/cfa41710-f68c-492b-bd47-85ca16d1d152">

The PR is located here but contains various changes as well. https://github.com/turingscript/tokenizers/pull/6/files

I'm testing this by compiling and packing my build. I then install it locally in a dummy project using `npm install ${locall file path...}`.

In the advent the component can't be exported, I would expect the build to fail or at least give a warning in the logs.

In addition, the documentation is very sparse and lacking some critical info and examples. I can seem to find a single section that would help me debug this.

I would appreciate any help in debugging this, and in addition would like to encourage any improvements to create better feedback on this error and it's route cause. I imagine [a compiler plugin](https://crates.io/crates/rustc-tools) or something of the sort could greatly help here. 

https://github.com/napi-rs/napi-rs/issues/1214#issuecomment-2054104037

**Comment by Brooooooklyn** [comment]
@aaronclong you should move your `#[napi(factory)]` and it's fn into `impl` block. I've created a PR to emit a compile error for your situation.

**Comment by aaronclong** [comment]
> @aaronclong you should move your `#[napi(factory)]` and it's fn into `impl` block. I've created a PR to emit a compile error for your situation.

@Brooooooklyn I have done that locally as well but it still doesn't work. Can you please reopen the issue

**Comment by aaronclong** [comment]
@Brooooooklyn I just pushed those local changes to the PR and also ran it again. I can confirm the function still isn't registered

https://github.com/turingscript/tokenizers/blob/63791ada1693738eca9c346277d6f9b674e154c7/bindings/node/src/bpe_trainers.rs#L69-L87

**Comment by Brooooooklyn** [comment]
@aaronclong I found that if you delete the `Cargo.toml` in the workspace root, everything is fine

**Comment by aaronclong** [comment]
@Brooooooklyn is there a reason that is causing problems and is there a way to fix it. Thanks so much for responding here

**Comment by aaronclong** [comment]
> @aaronclong I found that if you delete the `Cargo.toml` in the workspace root, everything is fine



> @Brooooooklyn is there a reason that is causing problems and is there a way to fix it. Thanks so much for responding here

@Brooooooklyn I was able to confirm this, and thank you so much for your help!!!  Is there anything to be done to allow the cargo workspaces?
I'm not great at rust, but it seems weird that would stop it. Could it be because of the `resolver = "2"`?

https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html
https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
