### ISSUE TITLE
cannot find function `register_module_exports`

### ISSUE THREAD

**Issue by chenkovsky** [napi-rs/napi-rs#2061]
error[E0425]: cannot find function `register_module_exports` in module `napi::bindgen_prelude`
   --> src/lib.rs:89:1
    |
89  |   #[module_exports]
    |   ^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `register_module_export`
    |
   ::: ..../napi-2.16.4/src/bindgen_runtime/module_register.rs:124:1
    |
124 | / pub fn register_module_export(
125 | |   js_mod: Option<&'static str>,
126 | |   name: &'static str,
127 | |   cb: ExportRegisterCallback,
128 | | ) {
    | |_- similarly named function `register_module_export` defined here

**Comment by Brooooooklyn** [comment]
@chenkovsky you need to enable  `compat-mode` feature both in `napi` and `napi-derive` to use the `module_exports` macro
