### ISSUE TITLE
Module did not self-register 

### ISSUE THREAD

**Issue by avp1598** [napi-rs/napi-rs#2068]
Getting this issue when i try to use napi generated module, I am following the same tutorial of building cool package

```bash
node:internal/modules/cjs/loader:1341
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Module did not self-register: '/example_server/node_modules/package-darwin-arm64/package.darwin-arm64.node'.
```

I am installing it in node environment through npm and trying to run it in typescript script

**Comment by Brooooooklyn** [comment]
Can you provide a minimal reproducible repo?

**Comment by avp1598** [comment]
Sorry, this was not a bug it was a silly issue on my end.

It was because my napi code was under a feature but i was not building with that feature enabled. However it was still spitting out the types file which i guess is not related to compilation at all, so I assumed everything is good.
