### ISSUE TITLE
public Ser and De?

### ISSUE THREAD

**Issue by Gentle** [napi-rs/napi-rs#2127]
Could [De](https://github.com/napi-rs/napi-rs/blob/main/crates/napi/src/js_values/de.rs) and [Ser](https://github.com/napi-rs/napi-rs/blob/main/crates/napi/src/js_values/ser.rs) be made public? My usecase is to use [serde-transcode](https://docs.rs/serde-transcode/latest/serde_transcode/) to parse messagepack directly into a JsValue without having to use an intermediary struct

in general, having access to the Serializer and Deserializer impls allows writing more efficient code, but both De and Ser are only pub(crate)

**Comment by SoloJiang** [comment]
I have the same problem for simplify handle export:
```rust
struct A {}
struct B {}

enum Payload {
  A(A),
  B(B),
}
```

**Comment by Gentle** [comment]
https://github.com/napi-rs/napi-rs/pull/2131

I PRed my proposed change

**Comment by Gentle** [comment]
merged
