### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by abnerCrack** [napi-rs/napi-rs#2181]
I have a few suggestions for the project:

During practical usage, it is often necessary to create a glue layer for both Python and Node. The proposed solutions are pyo3 and napi respectively. I have noticed that pyo3's design practices are quite effective and might offer some valuable insights. For example, the clear macro naming conventions such as pyclass and pyfunction in pyo3 greatly help in maintaining clarity. Implementing a consistent naming convention in napi, similar to "napi", could be very beneficial, especially as the codebase grows.

Additionally, regarding serialization, pyo3 provides a convenient method like toPyObject. A similar serialization method in napi could also enhance consistency and ease of use.

I hope you find these suggestions helpful and consider incorporating some of the design elements from pyo3 into your project.

Thank you for taking the time to address this issue.

**Comment by Brooooooklyn** [comment]
Thank you for your suggestion. We mostly draw from the JavaScript community for API design experiences, such as https://rustwasm.github.io/docs/wasm-bindgen/reference/types/exported-rust-types.html, as we believe it facilitates a better transition and migration for developers from the JavaScript community.
