### ISSUE TITLE
it seems like napi build cannot assure package.name exist

### ISSUE THREAD

**Issue by zhangyuang** [napi-rs/napi-rs#219]
as this [code fragment]( https://github.com/napi-rs/napi-rs/blob/master/src/build.ts#L63)

![image](https://user-images.githubusercontent.com/17424434/95557793-e40dd680-0a47-11eb-9dd3-af59ebb7d02b.png)

`??` syntax only assure package field exact but not package.name

![image](https://user-images.githubusercontent.com/17424434/95558050-3fd85f80-0a48-11eb-8c02-dc6795727099.png)
maybe `tomlContent.package && tomlContent.package.name` or `tomlContent.package?.name`

**Comment by Brooooooklyn** [comment]
You can not build rust codes using `cargo build` if no name field in `[package]`.

**Comment by zhangyuang** [comment]
yeah，i find napi build command in build script executed after cargo build。maybe judgement in here can be more compact



发自我的iPhone


------------------ Original ------------------
