### ISSUE TITLE
Bug: Incorrect declaration of raw points, which can lead to memory leaks

### ISSUE THREAD

**Issue by zxcloli666** [napi-rs/napi-rs#2201]
### Sometimes napi sets the wrong raw point value, which can lead to memory leaks.
The essence of the problem is that the raw point is set to an incorrect length, which causes memory leaks.
Occurs when "opt-level" is set to "s". May also occur on other values.
Can also set raw point length to 0, regardless of changing the build profile (tested on release).

### Screens:
log1 = Ordinary string: &str or String (same behavior)
log2 = Raw point
log3 = Conversion to string via winapi::PCSTR
log4 = Conversion to string via CStr

![image](https://github.com/user-attachments/assets/6e028f4f-419f-4717-9bc1-376be38c45a1)
![image](https://github.com/user-attachments/assets/bdc4bcd6-ace7-402e-870b-c1221c8fe4d4)

![image](https://github.com/user-attachments/assets/35929984-e8eb-49ab-bb62-9afd4a53333f)

![image](https://github.com/user-attachments/assets/26ec1a19-e915-40dd-8da9-8e83f26f6426)

![image](https://github.com/user-attachments/assets/0e7688ee-e73a-4052-9d54-38b1292aa2e2)

### Reproduction steps
```rust
//let root = "Software\\Classes\\sc";
const TAG = "sc";
let root = format!("Software\\Classes\\{}", TAG);
let ptr = root.as_ptr();
let pcstr = PCSTR::from_raw(ptr);

let c_str: &CStr = unsafe { CStr::from_ptr(ptr.cast()) };
let str_slice: &str = c_str.to_str().unwrap();

println!("log1: {}", root);
println!("log2: {:?}", ptr);
unsafe { println!("log3: {}", pcstr.to_string().unwrap_or_default()); }
println!("log4: {}", str_slice);
```

**Comment by cuviper** [comment]
`CStr::from_ptr` requires a nul terminator, which `root` and `ptr` don't have.
