### ISSUE TITLE
Support native ESM codegen

### ISSUE THREAD

**Issue by wemeetagain** [napi-rs/napi-rs#2244]
In ESM projects, where napi bindings are just one part of the repo, mixing ESM and CJS files can be a huge pain.
It would be nice for napi-rs to generate an index.js that is valid ESM.

At a bare minimum, this can be done by adding the following lines to the top of the generated file:
```js
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);

const __dirname = new URL('.', import.meta.url).pathname;
```
and updating the exports.

**Comment by Brooooooklyn** [comment]
@wemeetagain what kind of pain? I believe it's okay to import NAPI-RS generated binding file in esm project

**Comment by wemeetagain** [comment]
I'm dealing with an opinionated tool [aegir](https://github.com/ipfs/aegir) that uses a few different build tools under the hood. (Esbuild to build/bundle the .js, tsc to build the .d.ts)
I believe the problem is with esbuild.

I solved my problem by running a post-napi-build script to manually edit the generated js file into a valid esm module.
But it would be nice for napi-rs to support this out of the box.

**Comment by theoparis** [comment]
When will this be released?

**Comment by Brooooooklyn** [comment]
@theoparis published

**Comment by charlag** [comment]
Is this documented?
