### ISSUE TITLE
Unable to make the typegen output custom TypeName implementations

### ISSUE THREAD

**Issue by JonoPrest** [napi-rs/napi-rs#2246]
For instance I want to be able to express an enum as a union of string literals. I've implemented TypeName and From/ToNapiValue.

The index.d.ts filed does not get the type declaration for "Test" in this case.

```rs
pub enum Test {
    A,
    B,
}

impl TypeName for Test {
    fn type_name() -> &'static str {
        "\"A\" | \"B\""
    }

    fn value_type() -> napi::ValueType {
        napi::ValueType::String
    }
}

#[napi]
pub fn test(val: Test) -> () {
    let _ = val;
}
```

Is there a way to make the build generate the types as defined in the trait TypeName trait?

**Comment by CPunisher** [comment]
Can https://napi.rs/docs/concepts/enum#string-enum meet your requirements?

**Comment by CPunisher** [comment]
You can use `npx napi build --platform --release --no-const-enum` or add the build flag to `package.json` .

**Comment by JonoPrest** [comment]
Thanks very much @CPunisher!
