### ISSUE TITLE
Customize the output directory of the compilation product

### ISSUE THREAD

**Issue by mycrl** [napi-rs/napi-rs#2306]
I see that there is a related issue: https://github.com/napi-rs/napi-rs/issues/1061 which mentions that this issue is already supported, I looked at the merge request and didn't find any options to support this, and the documentation doesn't show how to do this requirement, so , is customizing the output path doable now?

I don't really want to output the compiled .node .ts .js files to the root of the package, it would be better to make it so that I can control where to output to, probably most people don't mind the current output location, but there is still an undeniable need to customize the output.

**Comment by DrJonki** [comment]
Anybody else stumbling upon this, it's currently possible to set the output directory as a positional argument to `napi build`, e.g.
```
napi build --platform --release dist
```
