### ISSUE TITLE
ToNapiValue for napi class object

### ISSUE THREAD

**Issue by alshdavid** [napi-rs/napi-rs#2322]
Hi all, I am trying to set a napi class object as a key on an existing JavaScript object but cannot because it does not implement `ToNapiValue`.

```rust
#[napi_derive::napi]
pub struct Foo {}

#[napi_derive::napi]
fn set_values(env: Env, mut target: JsObject) -> napi::Result<JsObject> {
  target.set_named_property("foo", Foo{})?; 
  //                                ⬆️
  //  "the trait bound `Foo: ToNapiValue` is not satisfied"
  Ok(target)
}
```

What is the correct way to handle this case?

**Comment by CPunisher** [comment]
Which napi version do you use? I try your code with latest napi2 and napi3 and everything works.

```js
import { setValues } from "./index.js";
const obj = {};
setValues(obj);
console.log(obj); // { foo: Foo {} }
```

Or there's something wrong with your development environment. Try to run `cargo clean` and rebuild.

**Comment by alshdavid** [comment]
You are right. 

My `.vscode/settings.json` has ` "rust-analyzer.procMacro.ignored": { "napi-derive": ["napi"] }` because of the proc-macros issue.

This issue: https://github.com/napi-rs/napi-rs/issues/944
