### ISSUE TITLE
[Question] Possible to use the generated module with Deno

### ISSUE THREAD

**Issue by SteveMcFarlin** [napi-rs/napi-rs#2352]
Was wondering if anyone had tried to use the module with Deno given it's support for NAPI.

**Comment by Brooooooklyn** [comment]
@SteveMcFarlin hey, Deno is compatible with the `Node-API`, so basically you can use the `NAPI-RS` projects in Deno without any compatible layer

**Comment by SteveMcFarlin** [comment]
Thank you @Brooooooklyn
