### ISSUE TITLE
Error: The process '/usr/bin/ssh' failed with exit code 1 

### ISSUE THREAD

**Issue by Shyam-Raghuwanshi** [napi-rs/napi-rs#2357]
Build FreeBSD actions failed 
[Build FreeBSD](https://github.com/Shyam-Raghuwanshi/cool/actions/runs/11854608349/job/33038575031#logs)

I am following these napi docs
[simple-package](https://napi.rs/docs/introduction/simple-package.en)

**Comment by Brooooooklyn** [comment]
@Shyam-Raghuwanshi Use the latest config here: https://github.com/napi-rs/package-template/blob/main/.github/workflows/CI.yml#L132-L177
I'll update the document soon

**Comment by Shyam-Raghuwanshi** [comment]
it's working, Thank you very much
