### ISSUE TITLE
Equivalent to Napi::ObjectWrap and Class with Private Data

### ISSUE THREAD

**Issue by nickbabcock** [napi-rs/napi-rs#236]
From a cursory look at the [classes test case](https://github.com/napi-rs/napi-rs/blob/9c3465543f47704efe24ef27a888dfaacef5f3f9/test_module/__test__/class.spec.ts) it appears that the property internally used is still [represented as a JsNumber](https://github.com/napi-rs/napi-rs/blob/9c3465543f47704efe24ef27a888dfaacef5f3f9/test_module/src/class.rs#L26). Is there a way to represent a class that holds rust structs that can't be represented as a JS property (like a `File` or `reqwest::Client`, etc). I see that C++ [`Napi::ObjectWrap` is a bit what I'm after](https://github.com/nodejs/node-addon-api/blob/826e466ef67d75c9dad38637054759af61c2b529/doc/object_wrap.md):

```cpp
class Example : public Napi::ObjectWrap<Example> {
  public:
    static Napi::Object Init(Napi::Env env, Napi::Object exports);
    Example(const Napi::CallbackInfo& info);
    static Napi::Value CreateNewItem(const Napi::CallbackInfo& info);

  private:
    double _value;
};
```

In the above example, `_value` field isn't exposed and can pretty be anything.

I took a look at some of the downstream [napi-rs packages](https://github.com/napi-rs/node-rs/tree/25aa2ea5f44bc436816fd758cdfae6af75e59e01/packages) and there isn't too much in the way classes, so I figured that this feature may not be implemented and it be best to raise an issue.

**Comment by Brooooooklyn** [comment]
You can use `ctx.env.create_external` to create `JsExternal` value, which hold a native value and could be assign to object property. See: https://github.com/napi-rs/napi-rs/blob/master/test_module/src/external.rs#L10

**Comment by Brooooooklyn** [comment]
And you can also wrap native object to `this` in class `Constructor`, see example in linked pull request.

**Comment by Brooooooklyn** [comment]
Close for now, feel free to reopen it if you had more questions about this topic.
