### ISSUE TITLE
GitHub workflow failed in "Test bindings on Linux-x64-gnu - node@18" with "Error: Process completed with exit code 129" message

### ISSUE THREAD

**Issue by sumbad** [napi-rs/napi-rs#2389]
Latest generated workflow by `@napi-rs/cli` fails.

The failed action - https://github.com/sumbad/pub/actions/runs/12159696834

[Test bindings on Linux-x64-gnu - node@18](https://github.com/sumbad/pub/actions/runs/12159696834/job/33910472609#logs)
[Test bindings on Linux-x64-gnu - node@20](https://github.com/sumbad/pub/actions/runs/12159696834/job/33910473194#logs)

ends with the next message:

`Error: Process completed with exit code 129.`

**Comment by Brooooooklyn** [comment]
You can add this config to your package.json: https://github.com/napi-rs/package-template/blob/main/package.json#L91

In the next major release, I'll refactor the `new` command in the cli, the infra of the cli is too old and it need to be synced with the https://github.com/napi-rs/package-template

**Comment by sumbad** [comment]
Thanks for your answer. Another option is to replace the AVA test runner with the Node.js test runner (https://nodejs.org/download/release/v20.0.0/docs/api/test.html) It works without errors and no needed dependencies.
