### ISSUE TITLE
ThreadsafeFunction not available

### ISSUE THREAD

**Issue by martonlanga** [napi-rs/napi-rs#246]
Hey @Brooooooklyn, tried to follow [this example](https://github.com/napi-rs/napi-rs/blob/v0.4.1/test_module/src/napi4/tsfn.rs), but I can't use ThreadsafeFunction.

```
no method named `create_threadsafe_function` found for reference `&napi::Env` in the current scope
method not found in `&napi::Env`
```

I have version `5.1` installed, does only `4.x` support these methods?

**Comment by Brooooooklyn** [comment]
It's been a big refactor after `napi@0.5`, so if you want use `Env.create_threadsafe_function`, you must specified `napi = { git="https://github.com/napi-rs/napi-rs" }` in `Cargo.toml`

**Comment by martonlanga** [comment]
Thanks for your reply!

1. `Env.create_threadsafe_function` is available now, but `ThreadSafeContext` isn't so I can't specify the `ctx`.

```rs
ctx.env.create_threadsafe_function(_, _,
  |ctx: ThreadSaveContext<Vec<u32>>|  // how do I annotate ThreadSaveContext ?

Error:
type annotations needed for `napi::threadsafe_function::ThreadSafeCallContext<T>`
type must be known at this point
```

2. Converting `JsString` to `String` seems to break now, getting this:
```the trait bound `std::string::String: std::convert::From<napi::JsString>` is not satisfied```

3. Also, I'm using it with Electron (using [electron-builder](https://www.electron.build), and webpack with `node-loader`), and it works just fine! I'm not doing `node-gyp rebuild`, but it seems to work without that as well. Do you think this might cause a problem in the future?

**Comment by Brooooooklyn** [comment]
> Env.create_threadsafe_function is available now, but ThreadSafeContext  isn't 

Try `use napi::threadsafe_function::ThreadSafeCallContext;`

> Converting JsString to String seems to break now, getting this:
the trait bound `std::string::String: std::convert::From<napi::JsString>` is not satisfied

Because the old implement will cause undefined behavior if `JsString` is not valid `utf8` string.

You can use `js_string.into_utf8()?.to_ownd()?;` to convert `JsString` to `String` (or `into_utf16()/into_latin1()`)

>  I'm not doing node-gyp rebuild, but it seems to work without that as well. Do you think this might cause a problem in the future?

No, it's just fine because `napi-rs` is not dependent on `node-gyp` and `N-API` will ensure the binary ABI compatible cross all node versions since `node@8.9`

**Comment by martonlanga** [comment]
Still not available, maybe because it's private?
https://github.com/napi-rs/napi-rs/blob/5025ffa7917955b3e47fd357858a25660a977608/napi/src/threadsafe_function.rs#L108

> You can use js_string.into_utf8()?.to_ownd()?; to convert JsString to String (or into_utf16()/into_latin1())

Thanks, this worked.

> No, it's just fine because napi-rs is not dependent on node-gyp and N-API will ensure the binary ABI compatible cross all node versions since node@8.9

Awesome, thanks! Gotta love `N-API`

**Comment by Brooooooklyn** [comment]
> Still not available, maybe because it's private?

Oh it's `ThreadSafeCallContext` not `ThreadSafeContext`, `ThreadSafeContext` is internal used.

Try `use napi::threadsafe_function::ThreadSafeCallContext;`

**Comment by martonlanga** [comment]
Ooooh, my bad. `ThreadSafeCallContext` works! Thanks @Brooooooklyn  :))

**Comment by martonlanga** [comment]
Now I'm having troubles calling the function. Here's my code:

```rust
let send_stdout = ctx.env.create_threadsafe_function(
        func,
        0,
        |ctx: napi::threadsafe_function::ThreadSafeCallContext<Vec<String>>| {
            ctx.value
                .iter()
                .map(|arg| ctx.env.create_string(arg))
                .collect::<Result<Vec<JsString>, Error>>()
        },
    )?;

    thread::spawn(move || {
        let output = vec!["hello".to_string()];
        send_stdout.call( // Error: Expected 1 argument, found 2
            Ok(output),
            napi::threadsafe_function::ThreadsafeFunctionCallMode::NonBlocking,
        );
    });
```

When I remove the 2nd argument, it says: `this function takes 2 arguments but 1 argument was supplied
expected 2 arguments`

**Comment by martonlanga** [comment]
Ran `cargo check` and it compiles, so seems like this is an issue with `rust-analyzer`

**Comment by martonlanga** [comment]
Quick question @Brooooooklyn - was wondering why the first argument in a threadsafe callback is always of type `null`. Is there a reason for this? Or does that stand for something?

#### Example:
 ##### Sending
`Ok(arg1, arg2, arg3)`
##### Receiving
` [null, arg1, arg2, arg3]`

**Comment by Brooooooklyn** [comment]
Follow async callback conventions: https://nodejs.org/en/knowledge/errors/what-are-the-error-conventions/
Check if the Result is okay, if so, pass a null as the first (error) argument automatically.
If the Result is an error, pass that as the first argument.

**Comment by martonlanga** [comment]
Ahh makes sense, thanks!
