### ISSUE TITLE
Communicate with threads from JS

### ISSUE THREAD

**Issue by martonlanga** [napi-rs/napi-rs#254]
I have a `js_function` that creates a thread every time it gets called. Is there a way to send messages to this thread from the JS side of things?

Here's what I'm trying to do, but this obviously doesn't work:
```rust
#[js_function(4)]
fn command(ctx: CallContext) -> napi::Result<JsFunction)> {
    let (sender, receiver) = unbounded();

    thread::spawn(move || {
      loop {
        // ...
        let message = receiver.recv();
      }
    });

    // call sender.send() somehow from JS
    // ...
}
```

I had a few ideas in mind, but couldn't make either of them work:
1. Initialize a HashMap in the `init()` function that keeps track of the `sender`s based on an *id* and provide them to the command alongside `ctx`
2. Return a `JsFunction` from `command` that calls `sender.send` when its invoked

Is there a way to to achieve what I'm trying to do?

**Comment by Brooooooklyn** [comment]
You can covert `sender` to `JsExternal` and return it to js side.
Then you can cache it with `Map` or anything you want.
And next, you could write a `js_function` in `rust` side which take `JsExternal` and your payload as arguments, `unwrap` `Sender` from `JsExternal` and send the payload.

**Comment by martonlanga** [comment]
Thanks @Brooooooklyn, this worked
