### ISSUE TITLE
Most sys enums are unsafe

### ISSUE THREAD

**Issue by adumbidiot** [napi-rs/napi-rs#277]
According to the [bindgen docs for rustified enums](https://docs.rs/bindgen/0.55.1/bindgen/struct.Builder.html#method.rustified_enum):
> Use this with caution, creating this in unsafe code (including FFI) with an invalid value will invoke undefined behaviour. You may want to use the newtype enum style instead.

This is problematic, as NAPI often adds to these enums across editions. This causes UB if, for example, an napi 3 module is loaded in an napi 6 context and calls [typeof](https://nodejs.org/api/n-api.html#n_api_napi_typeof) on a bigint, creating a rust enum with an invalid state. 

This can be fixed by not using rust enums for these types and using constant values instead. Many `From`/`Into` impls will have to be replaced with `TryFrom/TryInto`, but these impls were unsafe anyways. 

I ran into this issue while working on #271. If you want, I can push fixes there or I can just make a new PR fixing this.

**Comment by Brooooooklyn** [comment]
> You may want to use the newtype enum style instead

So how about change bindgen to generate newtype enum?

**Comment by adumbidiot** [comment]
Ok, I'll open a new PR for that

**Comment by adumbidiot** [comment]
@Brooooooklyn This should be reopened. We use low level sys enums directly in napi calls again which can lead to them having an invalid state between versions of napi.
