### ISSUE TITLE
Benchmark action is broken for PRs from users without "collaborator" privileges

### ISSUE THREAD

**Issue by adumbidiot** [napi-rs/napi-rs#279]
This action fails for PRs from people who don't have collaborator privileges. I elaborated slightly more [here](https://github.com/napi-rs/napi-rs/pull/271#issuecomment-720260548). 

I think we could either disable it on PRs, or switch back to a manually specified secret and skip that action if it is not present. Maybe there is another may I'm missing.

**Comment by TheBrenny** [comment]
This still isn't fixed? Maybe we could have a bot comment on all forked PRs with the benchmark stats?
