### ISSUE TITLE
Remove bindgen

### ISSUE THREAD

**Issue by Brooooooklyn** [napi-rs/napi-rs#286]
Bindgen rely on the `llvm` and many other dependecies, which make the build slower and complicated.

/cc @adumbidiot

**Comment by adumbidiot** [comment]
I'd need to look into it more, but one problem we will run into is the fact that we also generate bindings of libuv headers, which don't have abi stability. They would be dependent on node versions, not napi versions. Maybe we could make bindgen an optional dep if people want libuv bindings.

**Comment by Brooooooklyn** [comment]
> one problem we will run into is the fact that we also generate bindings of libuv headers

I think it's time to remove `Env::execute` from `napi-rs`, it was used to running rust Future on `libuv`.
But it can not run `tokio future` or `async-std future` directly, so it's useless for most scenarios.
