### ISSUE TITLE
exit 3221225477 running with nodejs x32 on windows 64 in release mode

### ISSUE THREAD

**Issue by Brooooooklyn** [napi-rs/napi-rs#297]
Everything is just fine in debug mode, but node.exe exit with status 1 while loading the `.node` file  compiled with `--release` flag

See https://github.com/napi-rs/package-template/actions/runs/361398266

**Comment by adumbidiot** [comment]
I think this is a compiler codegen error. I don't think working around it is wise as `opt-level='z'` breaks it on my computer again. I found a similar issue: https://github.com/rust-lang/rust/issues/67497. I think we should try to find a smaller example of this behavior and report it to the rust compiler repo.

**Comment by Brooooooklyn** [comment]
Fixed `test_module` in this repo, but failed again in https://github.com/napi-rs/package-template/pull/86/files ....

**Comment by Brooooooklyn** [comment]
Confirmed fixed by change `CString::as_ptr()` to `CString::into_raw()` in windows, which was considered to cause memory leak.

Seems like `node` will free the `CString` and cause double free if using `as_ptr` ?

**Comment by Brooooooklyn** [comment]
wired, still failed in CI https://github.com/napi-rs/package-template/pull/86/checks

But in my windows virtual machine I was using node@10.x 32bit, I will try again tomorrow night.

**Comment by adumbidiot** [comment]
Pointers created from into_raw must be returned to rust and freed with from_raw. If node tries to free these pointers, we have much bigger issues.

**Comment by adumbidiot** [comment]
After debugging, I found that attaching `#[inline(never)]` to `check_status` fixed the issue on my machine. This is definitely a rust codegen issue. That function is inlined incorrectly on that target.

**Comment by Brooooooklyn** [comment]
@adumbidiot oh, let me try

**Comment by Brooooooklyn** [comment]
Seems not work in CI https://github.com/napi-rs/package-template/pull/86/checks?check_run_id=1428438105

**Comment by adumbidiot** [comment]
The latest stable breaks it again

**Comment by adumbidiot** [comment]
Setting `opt-level = 's'` appears to generate good code on my computer, though it will probably break too in the future.

**Comment by Brooooooklyn** [comment]
`opt-level='s'` seems not work on my computer, but opt-level=1 could work

**Comment by Brooooooklyn** [comment]
> opt-level = 1 worked fine

Not work actually, just can execute `require('index.node')`, exit `3221225477 ` again while running tests

**Comment by pantharshit00** [comment]
Hey, I was trying this out and I can confirm adding a `build.rs` fixed the build on windows :)

**Comment by Brooooooklyn** [comment]
Seems like it could be resolved by change the `codegen-units` to 32 (or higher) and disable `lto`: https://github.com/napi-rs/package-template/pull/134/files#diff-b268bb7dc66e8638921e223098a11eabb92b424875ec72a19d6145dc1efbe3f2R90

**Comment by Brooooooklyn** [comment]
Close in https://github.com/napi-rs/napi-rs/pull/1167
