### ISSUE TITLE
Electron throws "A dynamic link library (DLL) initialization routine failed" error on Windows

### ISSUE THREAD

**Issue by wspl** [napi-rs/napi-rs#304]
I compiled my library with vs2019+cmake+llvm on Windows 10.
Then I use the generated .node file in an electron project, it throws error with info "A dynamic link library (DLL) initialization routine failed".

Reproduce on Windows:
```
git clone https://github.com/napi-rs/package-template
cd package-template
electron .
```

But it works fine with Node 14 on Windows, and Electron on macOS.

Some useful(maybe) links:
https://github.com/electron/electron/issues/19884
https://github.com/cmake-js/cmake-js/issues/188

**Comment by adumbidiot** [comment]
What library version are you using?

**Comment by wspl** [comment]
> What library version are you using?
> 
> Assuming you are using 0.5, try master. Electron support was added recently.

The package version of this repo(napi-rs) is 0.3.9. Which package should I update to the master version?

**Comment by Brooooooklyn** [comment]
> The package version of this repo(napi-rs) is 0.3.9.

This is the `npm` package version.

We are talking about the `Cargo` package version, which you should change to:

```
[dependencies]
napi = { git = "https://github.com/napi-rs/napi-rs" }
napi-derive = { git = "https://github.com/napi-rs/napi-rs" }

[build-dependencies]
napi-build = { git = "https://github.com/napi-rs/napi-rs" }
```

**Comment by wspl** [comment]
> > The package version of this repo(napi-rs) is 0.3.9.
> 
> This is the `npm` package version.
> 
> We are talking about the `Cargo` package version, which you should change to:
> 
> ```
> [dependencies]
> napi = { git = "https://github.com/napi-rs/napi-rs" }
> napi-derive = { git = "https://github.com/napi-rs/napi-rs" }
> 
> [build-dependencies]
> napi-build = { git = "https://github.com/napi-rs/napi-rs" }
> ```

Great! It works now. Thanks.
