### ISSUE TITLE
Issues while trying to upgrade to `^1.0.0-alpha.0`

### ISSUE THREAD

**Issue by martonlanga** [napi-rs/napi-rs#341]
### Libuv not available

(this might be a known issue)

```
Updating crates.io index
error: failed to select a version for `napi`.
    ... required by package `native v0.1.4
versions that meet the requirements `^1.0.0-alpha.0` are: 1.0.0-alpha.0

the package `native` depends on `napi`, with features: `libuv` but `napi` does not have these features.


failed to select a version for `napi` which could resolve this conflict
```

### Creating a threasafe function
```
error[E0599]: no method named `create_threadsafe_function` found for mutable reference `&mut Env` in the current scope
  --> src/lib.rs:86:34
   |
86 |     let server_message = ctx.env.create_threadsafe_function(
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `&mut Env`
```
Related:
```
error[E0433]: failed to resolve: could not find `threadsafe_function` in `napi`
   --> src/shell.rs:352:19
    |
352 |             napi::threadsafe_function::ThreadsafeFunctionCallMode::NonBlocking,
    |                   ^^^^^^^^^^^^^^^^^^^ could not find `threadsafe_function` in `napi`
```
---

I'm trying to make napi work with Electron on Windows, that's why I'm trying to upgrade so early. Maybe `0.5.1` would work as well?

**Comment by adumbidiot** [comment]
`libuv` related functions were removed. You need to set the `napi4` feature in order to use tsfns.

**Comment by martonlanga** [comment]
Thanks for the answer @adumbidiot 

What do you recommend using instead of `libuv`?

**Comment by adumbidiot** [comment]
From what i can tell, the all the libuv feature did was provide a way to spawn tasks on node's libuv threadpool. The `tokio` feature will likely let you achieve something similar by allowing you to spawn tasks on a tokio runtime managed by this library, or you could also build and manage your own threadpool. Threadsafe functions give you a lot of flexibility and options.

**Comment by Brooooooklyn** [comment]
> Thanks for the answer @adumbidiot 
> 
> 
> 
> What do you recommend using instead of `libuv`?

From the code snippets, you seemed not using `libuv` related features. So I guess you could just switch to `napi4`.

**Comment by martonlanga** [comment]
Alright, thanks.

One more question: previously I was calling `release()` on `tsfn` when I was done sending messages. This function no longer exists, so does that mean it gets cleaned up automatically?
Saw that that there is `abort()` now, but that seems to have a different functionality.

**Comment by Brooooooklyn** [comment]
> So does that mean it gets cleaned up automatically?

Yes, `napi-rs` call the `tsfn#release` automatically when `tsfn` dropped
