### ISSUE TITLE
MacOS build failed due to undefined symbols

### ISSUE THREAD

**Issue by DaAitch** [napi-rs/napi-rs#354]
I set up my build according to the package-template, but I thought I should open the issue in this repo.

In order to make the build work on MacOS, I have to add linker rust flags:
```bash
RUSTFLAGS="-C link-args=-Wl,-undefined,dynamic_lookup" npm run build:debug
```

That's also correct for C/C++ builds on MacOS as per default the MacOS linker doesn't allow undefined symbols which we have in every node module.

Is it correct that I have to build it that way? It would be cool if the build takes care on MacOS to add those linker flags or maybe at least add it to the documentation?

Thank you
Kindly regards

**Comment by adumbidiot** [comment]
The [build script](https://github.com/napi-rs/napi-rs/blob/main/build/src/macos.rs) should those flags. Are you running the build script in the top-level code?

**Comment by DaAitch** [comment]
oh I'm so stupid, sorry wasting your time 🤦 .
thank you @adumbidiot 

I had the build commented out, because I was testing something:

```toml
# build = "src/build.rs"
```
