### ISSUE TITLE
problem with tsfn: Ref<T> doesn't impl Send

### ISSUE THREAD

**Issue by DaAitch** [napi-rs/napi-rs#356]
Hi,

taking about two versions, `napi = "0.5"` and latest github version.

I'd like use threadsafe functions for a multithreaded environment.
From main/node thread I'm pushing tasks to an executor, which should call back to node via tsfn.

My setup looks like this:

```rust
#[js_function(0)]
fn dummy(ctx: CallContext) -> Result<JsUndefined> {
    Ok(ctx.env.get_undefined()?)
}

#[js_function(0)]
fn cra_engine_new(ctx: CallContext) -> Result<JsExternal> {
    let js_dummy_func = ctx.env.create_function("dummy", dummy)?;

    let tsfn = ctx.env.create_threadsafe_function(&js_dummy_func, 0, |tscc: ThreadSafeCallContext<Cb>| -> Result<Vec<JsUnknown>> {
        (tscc.value)(&tscc.env)?;
        Ok(vec![]) // unnessesary js call
    })?;

    let engine = NodeEngine::new(CustomEngineData { tsfn }).map_err(error::to_napi_err)?;
    ctx.env.create_external(Arc::new(engine))
}


#[js_function(2)]
fn cra_window_new(ctx: CallContext) -> Result<JsUndefined> {
    let engine = get_engine(&ctx)?;
    let cb = ctx.env.create_reference(ctx.get::<JsFunction>(1)?)?;
    
    // for testing, for now we don't create a window
    engine.spawn(async move {
        engine.custom_data.tsfn.call(Ok(Box::new(move |env| {
            let cb = env.get_reference_value(cb)?;
            cb.call(None, &[]);
            Ok(())
        })), NonBlocking);
    });

    ctx.env.get_undefined()
}
```

At current I think I'm not able to use
- neither version 0.5, because `napi::Ref` is not `Send`, so I cannot pass a js callback over thread boundaries
- nor latest from github because I don't know how to create a reference anymore: `env.create_reference` has been [removed](https://github.com/napi-rs/napi-rs/commit/9c921ffaa36036d8a2e406c45ec3336711969e79#diff-93a919c20317edf8761aea9d0a876d658c4274e040670a7587b46a757cb77cc5L331) and `Ref::new` is only `pub(crate)` 

Can you tell me how to solve this?

Thank you so much
Regards

**Comment by Brooooooklyn** [comment]
Why don't you just do that:

```rust
#[js_function(2)]
fn cra_window_new(ctx: CallContext) -> Result<JsUndefined> {
    let engine = get_engine(&ctx)?;
    let cb = ctx.get::<JsFunction>(1)?;

    let tsfn = ctx.env.create_threadsafe_function(&js_dummy_func, 0, |tscc: ThreadSafeCallContext<...>| -> Result<Vec<JsUnknown>> {
        Ok(vec![]) // unnessesary js call
    })?;
    
    // for testing, for now we don't create a window
    engine.spawn(async move {
        tsfn.call(Ok(...)), NonBlocking);
    });

    ctx.env.get_undefined()
}
```

**Comment by DaAitch** [comment]
Hey @Brooooooklyn ,

thank you for your answer.

> Because in napi-rs, only JsString, JsBuffer and JsArrayBuffer can be converted to Ref, lifetime of other JsValue could be managed with Rust lifetime. IMO, use the Ref with the JsFunction or JsBoolean make people confused.

I think that's wrong, because it should be possible to "store" values and prevent JS GC to recycle them. That has nothing to do with Rust. Look at this example. We don't want to store a specific type string or number in Rust, but simple the `napi_value` and it can also be a function or a boolean, it's a handle.

```js
const x = require('mylib.node');
x.setValue('secret value');
// ...
console.log(x.getValue());
```

In my case I need to "store" a function to pass the reference to the worker thread, that the worker thread can call the tsfn with that reference to my callback. It's like a consumer-producer calling back to nodejs.

I think we need to allow a Ref to any JS type. [node-addon-api](https://github.com/nodejs/node-addon-api/blob/master/doc/reference.md#factory-method) does this as well.

**Comment by Brooooooklyn** [comment]
I will add back `create_reference` in `Env`.

**Comment by Brooooooklyn** [comment]
> Because it should be possible to "store" values and prevent JS GC to recycle them.

Yes, but in `Rust` world, only the values of `JsString` `JsBuffer`, `JsArrayBuffer` need to Interact with GC.

For example, if you want prevent GC in js engine to recycle `JsBoolean`, just get the value of `JsBoolean` and store it in Rust side, it's safe and without any overhead.  And the same with `JsNumber` / `JsFunction` / `JsSymbol` ...

`JsString` / `JsBuffer` / `JsArrayBuffer` is different because you can only get `pointer value` from them, and store the `pointer` is meaningless because GC will recycle the value under the pointers. That is what I mean: ***IMO, use the Ref with the JsFunction or JsBoolean make people confused. ***

In `Rust` codes, prevent `JsBoolean/JsNumber` to be GC will make people confused, why don't you just get the value and store it in Rust side, and destroy them whenever you want.

**Comment by DaAitch** [comment]
> For example, if you want prevent GC in js engine to recycle JsBoolean, just get the value of JsBoolean and store it in Rust side, it's safe and without any overhead. And the same with JsNumber / JsFunction / JsSymbol ...

The thing I'm talking about has nothing to do with the native language, Rust, C++ or C.

I had a look to the impl again. Every `Js*` type of napi-rs is a `Value`, right? A `Value` stores `napi_env, napi_value` and a type, no napi references at all. When NodeJS invokes a native function, passing all the `napi_value` values, it's safe to immediately use them. They are all handles to valid JS objects, but only in that synchronous call from JS. That's also what the [napi reference doc](https://nodejs.org/api/n-api.html#n_api_references_to_objects_with_a_lifespan_longer_than_that_of_the_native_method) says.

I other words (and in my opinion according to what I read in the impl) storing `napi-rs::Js*` values (which are simple `napi_value`s) in Rust is not allowed. JS GC has no idea which handles are held from Rust, unless creating a reference to it.

**Comment by Brooooooklyn** [comment]
> In other words (and in my opinion according to what I read in the impl) storing napi-rs::Js* values (which are simple napi_values) in Rust is not allowed

Yes, that is why `Js*` not implement the `Send/Sync` trait, so people can only use it synchronically.

What I'm talking about is it's no necessary to `store` `Js*` expect `JsString/JsBuffer/JsArrayBuffer`, since you can store the value of them in `Rust` directly, and without any overhead. But if you want store the `Ref` value of them, you need to call additional `napi_create_reference/napi_delete_reference`. For example: 

```rust
struct Options {
  enable_js: bool,
}

#[js_function(1)]
fn create_option(ctx: CallContext)  -> Result<JsExternal> {
  let enable_js: JsBoolean = ctx.get(0)?;

  let options = Options { enable_js: enable_js.get_value()? };

  ctx.env.create_external(options)
}

#[js_function(2)]
fn run_in_other_thread(ctx: CallContext) -> Result<JsUndefined> {
  let callback: JsFunction = ctx.get(0)?;
  let js_options: JsExternal = ctx.get(1)?;
  let options = ctx.env.get_value_external::<Options>(js_options)?;
  let enable_js = options.enable_js;
  let tsfn = ctx.env.create_thread_safe_function(&callback, 1, |ctx: ThreadSafeCallContext<bool>| {
      ....
  });
  thead::spawn(move || {
    tsfn.call(Ok(enable_js), ThreadsafeFunctionCallMode::NonBlocking);
  });
  ctx.env.get_undefined()
}
```

It seems reasonable to store `bool` in `Options` rather than `Ref<JsBoolean>`.

**Comment by DaAitch** [comment]
> Yes, that is why Js* not implement the Send/Sync trait, so people can only use it synchronically.

Yep, I agree so far.

Now about the example:

I think your example is perfectly fine when you export only a couple of JS functions, but what if your architecture has dozens of JS functions and they all run something on the worker thread? Then you probably don't want to create new tsfns in every function for the sake of performance (mainthread: create tsfn, worker-thread: unref tsfn) and boilerplate code.

I can also give some other examples even without tsfn where you need `napi_ref`s:

1. take you're example `fn run_in_other_thread` and let's say we don't have a simple `JsBoolean`, but a `JsObject` with unknown content and you need to pass that back to the js callback? You need a ref to "store" it.

```rust
#[js_function(2)]
fn run_in_other_thread(ctx: CallContext) -> Result<JsUndefined> {
  let js_callback: JsFunction = ctx.get(0)?;
  let js_value: JsUnknown = ctx.get(1)?;

  let js_callback_ref = ctx.env.create_reference(&js_callback)?;
  let js_value_ref = ctx.env.create_reference(&js_value)?;

  let tsfn = ctx.env.create_thread_safe_function(None, 1, |ctx: ThreadSafeCallContext<(JsRef, JsRef)>| {
      let (js_callback_ref, js_value_ref) = ctx.value;
      let js_callback = js_callback_ref.get_value(ctx.env);
      let js_value = js_value_ref.get_value(ctx.env);
      js_callback.call(None, &[js_value])?
  });

  thead::spawn(move || { // Send refs
    tsfn.call(Ok((js_callback_ref, js_value_ref)), ThreadsafeFunctionCallMode::NonBlocking);
  });
  ctx.env.get_undefined()
}
```

2. take my example [with `setValue(value: any), getValue(): any`](https://github.com/napi-rs/napi-rs/issues/356#issuecomment-744480862). You want to store an `any` js value type. You need to create a ref and store that.

```javascript
const lib = require('mylib.node');
lib.setValue({a_very_huge_object: 'with a lot of data'});
// ...
console.log(lib.getValue());
```

```rust
struct MyData {
  value: JsRef,
}

// CallContext::data not (yet?) implemented.
// Can be used for global state https://github.com/napi-rs/napi-rs/blob/f90640d7aab36d83c9d93404e25ad6e9450ce17f/sys/src/lib.rs#L424

#[js_function(1)]
fn set_value(ctx: CallContext<MyData>) -> Result<JsUndefined> {
  let js_value: JsObject = ctx.get(0)?;
  ctx.data.value = Some(ctx.env.create_reference(js_value)?);
  ctx.env.get_undefined()
}

#[js_function(0)]
fn get_value(ctx: CallContext) -> Result<JsUnknown> {
  match ctx.data.value {
    Some(value) => value.get_value(ctx.env),
    None => ctx.env.get_undefined()
  }
}
```

What do you think? Those two examples should show, that refs are needed.

**Comment by Brooooooklyn** [comment]
@DaAitch Please take a look if linked pull request is what you want, feel free to comment/review the linked pr

**Comment by DaAitch** [comment]
awesome, yeah I think that's it!
