### ISSUE TITLE
napi_adjust_external_memory is probably unnecessary in create_*_with_data and drop_buffer

### ISSUE THREAD

**Issue by mika-fischer** [napi-rs/napi-rs#372]
JS already knows the size of a `JsBufferValue` or `JsArrayBufferValue`, so I'm pretty sure additionally using `napi_adjust_external_memory` will just make JS think the buffer is twice as large and additionally causes unnecessary overhead.

Note that node-addon-api also doen't use `napi_adjust_external_memory`: https://github.com/nodejs/node-addon-api/blob/1bdc7584cdea3c5761385c7c08a06e12d9852972/napi-inl.h#L1493-L1502

For `create_external`, on the other hand, it *would* be beneficial to provide an API for the user on the rust size to provide a size hint that then causes `napi_adjust_external_memory` to be called. Otherwise JS has no idea how large the JsExternal really is. This cannot be determined automatically, because computing the size might be arbitrarily complex, so I would just leave it up to the user (and also keep the option of not specifying a size hint at all).

**Comment by Brooooooklyn** [comment]
It's wired because I noticed that GC doesn't work at all in my local machine when I wasn't added the `adjust_external_memory` call. The memory usage increase to `20GB` and no `finalize_cb` got called.

I will confirm the right usage `create_*_with_data` in NodeJS source code.

> For create_external, on the other hand, it would be beneficial to provide an API for the user on the rust size to provide a size hint that then causes napi_adjust_external_memory to be called.

Oh seems like I was missing the `adjust_external_memory` call in `Env::create_external`.

> This cannot be determined automatically, because computing the size might be arbitrarily complex, so I would just leave it up to the user (and also keep the option of not specifying a size hint at all).

I think `mem::size_of::<T>` is enough to compute the size automatically.

**Comment by mika-fischer** [comment]
> 
> 
> It's wired because I noticed that GC doesn't work at all in my local machine when I wasn't added the `adjust_external_memory` call. The memory usage increase to `20GB` and no `finalize_cb` got called.
> 
> I will confirm the right usage `create_*_with_data` in NodeJS source code.

Ah, interesting. Maybe it's just that the adjust calls force the GC to run right now or very soon. Otherwise if you do a lot of work in a tight loop, or if nothing at all happens then it might just be the case that the gc call is delayed.

We also had issues with this in the past, see: https://github.com/nodejs/help/issues/2836

> > This cannot be determined automatically, because computing the size might be arbitrarily complex, so I would just leave it up to the user (and also keep the option of not specifying a size hint at all).
> 
> I think `mem::size_of::<T>` is enough to compute the size automatically.

No, that just computes the size of the type on the stack. If it has allocated data on the heap, that does not get counted. But that is what JS is interested in, the total amount of data that can be freed by dropping the value. The `size_of` is almost always the smallest part and therefore not sufficient.

For instance:
```
struct Foo {
    data: Vec<u8>,
}

fn main() {
    println!("{}", std::mem::size_of::<Foo>());
}
```
always prints `24`, whereas it is clear that the vector can have a size that is variable at runtime.

So as I said, the computation of this size can be quite complex. Think: `HashMap<Cow<String>, HashMap<Vec<u8>, Rc<UserType>>>`

And difficult to do automatically. Think `MyUserDefinedContainer<T>`...

So I would just document this and leave it up to the user to provide a good value.

**Comment by Brooooooklyn** [comment]
After read source codes from nodejs, I believe the `adjust_external_memory` in `create_*_with_data` is unnecessary.

I've done a fix in linked pull request, feel free to leave review comments.
