### ISSUE TITLE
'stdio.h' file not found

### ISSUE THREAD

**Issue by niugm** [napi-rs/napi-rs#390]
when i clone the demo project and run yarn build,i got this error,I guess it is the problem of node installation path,how to solve it?

``` bash
   Compiling napi-sys v0.4.7
error: failed to run custom build command for `napi-sys v0.4.7`

Caused by:
  process didn't exit successfully: `/Users/niugm/demo/target/debug/build/napi-sys-6ff678006d009d25/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=NODE_INCLUDE_PATH
  cargo:rerun-if-changed=src/bindings.h
  cargo:rerun-if-changed=src/lib.rs
  cargo:rerun-if-changed=src/sys.rs

  --- stderr
  /Users/niugm/.nvm/versions/node/v10.23.0/include/node/uv/errno.h:25:10: error: 'errno.h' file not found with <angled> include; use "quotes" instead
  /Users/niugm/.nvm/versions/node/v10.23.0/include/node/uv.h:55:10: fatal error: 'stdio.h' file not found
  /Users/niugm/.nvm/versions/node/v10.23.0/include/node/uv/errno.h:25:10: error: 'errno.h' file not found with <angled> include; use "quotes" instead, err: true
  /Users/niugm/.nvm/versions/node/v10.23.0/include/node/uv.h:55:10: fatal error: 'stdio.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate napi bindings: ()', /Users/niugm/.cargo/registry/src/github.com-1ecc6299db9ec823/napi-sys-0.4.7/build.rs:53:6
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Brooooooklyn** [comment]
seems like you need to run `xcode-select --install` fist

BTW, you can play with this demo project: https://github.com/napi-rs/package-template which doesn't need nodejs headers file nor clang/gcc anymore

**Comment by niugm** [comment]
> seems like you need to run `xcode-select --install` fist
> 
> BTW, you can play with this demo project: https://github.com/napi-rs/package-template which doesn't need nodejs headers file nor clang/gcc anymore.
> 
> Checkout to `main` branch, `master` branch was deprecated.

after changing the main branch, compile pass,I also update the Xcode Command Tool Line to the latest version。Thanks for your quick reply

**Comment by Brooooooklyn** [comment]
> by the way, is there a workflow configuration reference for gitlab?

Not yet, but I will write some documents about it soon in https://napi.rs
