### ISSUE TITLE
`to_js_value()` performance

### ISSUE THREAD

**Issue by probablykasper** [napi-rs/napi-rs#410]
With a large object (8MB worth of JSON), calling `ctx.env.to_js_value()` takes 100-200ms in my case. On the other hand, running `serde_json::to_string_pretty` takes 20-25ms.

It seems like it would be faster to just convert it to a JSON string, send it to Node and then run `JSON.parse()`.

Is there anything that could be done to get a significant performance improvement for `ctx.env.to_js_value()`?

**Comment by Brooooooklyn** [comment]
Calling `NodeJS` N-API has a lot of overhead. Perform `ctx.env.to_js_value()` will call `N-API` many times with a large object.

> Is there anything that could be done to get a significant performance improvement for ctx.env.to_js_value()?

No.

IMO, `ctx.env.to_js_value()` only suitable for convert small object into `JsObject`. With large object, it will be slower than `JSON.parse`.

There are some related discussions like: [this-implementation-is-slow](https://github.com/capnproto/node-capnp/tree/node10#this-implementation-is-slow), [Slower than JSON.parse](https://github.com/luizperes/simdjson_nodejs/issues/28)

**Comment by probablykasper** [comment]
@Brooooooklyn I see, thank you for explaining that.

I don't have anything else to add, so I'll just close this.
