### ISSUE TITLE
Keeping Rust value between function runs

### ISSUE THREAD

**Issue by probablykasper** [napi-rs/napi-rs#421]
I have a struct which is read from a file. I then want to get/set parts of this struct from JavaScript, but without unnecessarily reading the file over and over again. What's the easiest/best way to have the struct persist?

What I tried at first was to pass a closure to `create_named_method`, like below, but turns out it doesn't accept closures.
```rust
#[module_exports]
fn init(mut exports: JsObject) {
  let library = load()?;
  let get_id = |ctx: CallContext| {
    let id = arg_to_string(ctx, 0)?;
    return library.get_id(&id);
  }
  exports.create_named_method("get_id", get_id);
}
```

**Comment by Brooooooklyn** [comment]
You have two options to do that:

Use `Env::create_external` to create `External` Object, return it to JavaScript, and pass it back when you want use it:

```rust
#[module_exports]
fn init(mut exports: JsObject, env: Env) {
  let library = load()?;
  exports.set_named_property"LIBRARY", env.create_external(load()?)?, None)?;
  exports.create_named_method("get_id", get_id)?;
}

#[js_function(1)]
fn get_id(ctx: CallContext) -> Result<JsNumber> {
  let library_external = ctx.get::<JsExternal>(0)?;
  let library: Library = ctx.env.get_value_external(&library_external)?;

  ctx.env.create_uint32(library.id)
}
```

You can attach the native value to `JsObject` via `Env::wrap`, and get it back from `this` in `CallContext`:


```rust
#[module_exports]
fn init(mut exports: JsObject, env: Env) {
  let library = load()?;
  let mut library_object = ctx.env.create_object()?;
  library_object.create_named_method("get_id", get_id)?;
  env.wrap(&mut library_object, library)?;

  exports.set_named_property"Library", library_object)?;
}

#[js_function]
fn get_id(ctx: CallContext) -> Result<JsNumber> {
  let this: JsObject = ctx.this_unchecked()?;
  let library: Library = ctx.env.unwrap(&this)?;

  ctx.env.create_uint32(library.id)
}
```

**Comment by probablykasper** [comment]
@Brooooooklyn Ah, cool. Using `create_external` definitely seems like it should work. I suppose I could create some wrapper in JS that handles passing the struct in and out. Is there any performance overhead to it, or is it basically just passing a reference back and forth?

What I think would be ideal is to keep the struct in Rust and use JS to essentially send CRUD events, like a database (probably should've mentioned, sorry). I'm guessing something like that wouldn't be too easy, if it's even possible?

**Comment by Brooooooklyn** [comment]
> Is there any performance overhead to it

The overhead in this situation is very litter.

> What I think would be ideal is to keep the struct in Rust and use JS to essentially send CRUD events, like a database (probably should've mentioned, sorry). I'm guessing something like that wouldn't be too easy, if it's even possible?

this is what I'm doing in [skia-rs](https://github.com/Brooooooklyn/skia-rs/blob/main/src/ctx.rs)

**Comment by probablykasper** [comment]
@Brooooooklyn I'll check that out. Thanks for the help! Hopefully this issue ends up helping other people with similar goals.

Really appreciate your work on napi-rs
