### ISSUE TITLE
Handling functions while deserializing in `from_js_value`

### ISSUE THREAD

**Issue by dwoznicki** [napi-rs/napi-rs#422]
Hi, I'm trying to deserialize the following JS object

```javascript
{
    entry: {
        'web': __dirname + '/src/index.ts',
    },
    output: {
        path: __dirname + '/lib'
    },
    module: {},
    plugins: [
        () => { console.log('hello world!'); },
    ]
}
```

into a struct using `context.env.from_js_value`, but (unsurprisingly) I get an error when doing so

```
Error: typeof Function value could not be deserialized
```

Ideally, I'd like to just ignore the plugins field altogether during deserialization. I imagine I could just delete plugins from the `JsObject` before calling `from_js_value`, but I'm wondering if there's a more idiomatic way to handle this. Any advice?

**Comment by Brooooooklyn** [comment]
https://serde.rs/attr-skip-serializing.html

**Comment by dwoznicki** [comment]
Aha, I couldn't get `#[serde(skip)]` to work last night, but it appears to work this morning. Thanks!
