### ISSUE TITLE
Return different types

### ISSUE THREAD

**Issue by doodlewind** [napi-rs/napi-rs#434]
There are times when APIs need to return different types, e.g., `canvas.getContext('2d')` returns object or null. Another example is the image class in [skia-canvas](https://github.com/samizdatco/skia-canvas#loadimage) that supports setting string or buffer, which means its `image.src` can return different (primitive or non-primitive) types. But with napi-rs, the return types is by default constrained to things like `Result<JsObject>` or `Result<JsNull>`. Is there some way to support such pattern?

**Comment by Brooooooklyn** [comment]
I think return `JsUnknown` in this scenario is fine:

```rust
JsObject::into_unknown()
JsNull::into_unknown()
```

**Comment by bmacnaughton** [comment]
i'm new to rust, but not to using n-api and node-addon-api, so i'm sure this is just my inexperience, but when i try to use the syntax above, i get:

ambiguous associated type

`help: use fully-qualified syntax: <napi::JsNull as Trait>::into_unknown`

but when i try that i get `use of undeclared type Trait`.

if you can point me at an example of returning different types that would be helpful.
