### ISSUE TITLE
How to build against musl for Alpine?

### ISSUE THREAD

**Issue by pimeys** [napi-rs/napi-rs#446]
Another build problem. We're supporting Alpine Linux, but it seems `cdylib` is not a valid crate type for target `x86_64-unknown-linux-musl`.

Now this gets really interesting, but did anybody find a way to actually build N-API libraries for Alpine? We cannot have a dynamic library, so the only choice then would be `staticlib`? This is a hefty 70 megabytes more for us, and even worse, the resulting `.a` library has a wrong exec format to be loaded with node's `require`.

I think the solution might be to install libc et.al. and use the dynamically built `.so` file. That would not fly well with users who need Alpine...

**Comment by Brooooooklyn** [comment]
`staticlib` is not work, because `NodeJS` only accept `dylib` files during `require`.

> Now this gets really interesting, but did anybody find a way to actually build N-API libraries for Alpine? 

Packages in this https://github.com/napi-rs/node-rs all support `linux-alpine`.

Try to add these config into `.cargo/config`:

```toml
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
```

**Comment by Brooooooklyn** [comment]
> Packages in this https://github.com/napi-rs/node-rs all support linux-alpine.

Here is the Dockerfile which is used to build `linux-musl` target https://github.com/napi-rs/napi-rs/blob/main/alpine.Dockerfile

**Comment by pimeys** [comment]
Will this allow using of `cdylib` as the crate type, or should I go with `staticlib`?

**Comment by Brooooooklyn** [comment]
> Will this allow using of `cdylib` as the crate type

Yes, this flag will allow you build `cdylib` target to `linux-musl`

**Comment by Brooooooklyn** [comment]
Added this issue to [FAQ](https://napi.rs/faq#build-for-linux-alpine) in website

**Comment by pimeys** [comment]
Yeah, I got this working nicely. What it changes for us is we cannot anymore build statically, and we must ask our users to install certain dependencies, such as `libgcc` to get prisma working. We need to discuss this with the product if this is something we want.

**Comment by Brooooooklyn** [comment]
> What it changes for us is we cannot anymore build statically, and we must ask our users to install certain dependencies, such as libgcc to get prisma working.

Oh, what library cause the necessary of static link, I'm happy to try to find workarounds in this situation.

**Comment by pimeys** [comment]
I think this is just a misunderstanding from my side. I tried to build our binaries with the same dockerfile and got things to link dynamically. For the napi module this is fine though, but we might want to do the transition with two builds: all binaries (when we still need them) with the cross-compilation and this napi module directly with alpine as a `cdylib`.
