### ISSUE TITLE
Non-UTF-8 output: LINK : fatal error LNK1201

### ISSUE THREAD

**Issue by niugm** [napi-rs/napi-rs#452]
在windows10上编译，已安装visual studio 2019

下面是报错部分内容，搜索无果，特来求助...
-----------------------  

= note: Non-UTF-8 output: LINK : fatal error LNK1201: \xd0\xb4\xc8\xeb\xb3\xcc\xd0\xf2\xca\xfd\xbe\xdd\xbf\xe2\xa1\xb0C:\\GitLab-Runner\\builds\\Nq4snSLj\\0\\fed\\im\\im-desktop-serverkit\\target\\release\\deps\\im_deskop_serverkit.pdb\xa1\xb1\xca\xb1\xb3\xf6\xb4\xed\xa3\xbb\xc7\xeb\xbc\xec\xb2\xe9\xca\xc7\xb7\xf1\xca\xc7\xb4\xc5\xc5\xcc\xbf\xd5\xbc\xe4\xb2\xbb\xd7\xe3\xa1\xa2\xc2\xb7\xbe\xb6\xce\xde\xd0\xa7\xbb\xf2\xc8\xa8\xcf\xde\xb2\xbb\xb9\xbb\r\n

error: aborting due to previous error

error: could not compile `im-deskop-serverkit`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Internal Error: Command failed: cargo build --release
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at BuildCommand.<anonymous> (C:\GitLab-Runner\builds\Nq4snSLj\0\fed\im\im-desktop-serverkit\node_modules\@napi-rs\cli\scripts\build.js:51:29)
    at Generator.next (<anonymous>)
    at C:\GitLab-Runner\builds\Nq4snSLj\0\fed\im\im-desktop-serverkit\node_modules\@napi-rs\cli\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\GitLab-Runner\builds\Nq4snSLj\0\fed\im\im-desktop-serverkit\node_modules\@napi-rs\cli\node_modules\tslib\tslib.js:110:16)
    at BuildCommand.execute (C:\GitLab-Runner\builds\Nq4snSLj\0\fed\im\im-desktop-serverkit\node_modules\@napi-rs\cli\scripts\build.js:26:24)
    at BuildCommand.validateAndExecute (C:\GitLab-Runner\builds\Nq4snSLj\0\fed\im\im-desktop-serverkit\node_modules\clipanion\lib\index.js:1118:37)
    at Cli.run (C:\GitLab-Runner\builds\Nq4snSLj\0\fed\im\im-desktop-serverkit\node_modules\clipanion\lib\index.js:1371:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Brooooooklyn** [comment]
帮你 decode 了一下 error message: `LINK : fatal error LNK1201: 写入程序数据库“C:GitLab-Runner\buildsNq4snSLj\x00\fedimim-desktop-serverkit\target\releasedepsim_deskop_serverkit.pdb”时出错；请检查是否是磁盘空间不足、路径无效或权限不够\r\n`

应该不是 `napi-rs` 的问题

**Comment by niugm** [comment]
> 帮你 decode 了一下 error message: `LINK : fatal error LNK1201: 写入程序数据库“C:GitLab-Runner\buildsNq4snSLj\x00\fedimim-desktop-serverkit\target\releasedepsim_deskop_serverkit.pdb”时出错；请检查是否是磁盘空间不足、路径无效或权限不够\r\n`
> 
> 应该不是 `napi-rs` 的问题

感谢回复，C盘空间的确不多，还有4.9G，不过编译这个应该够用了。也可能是权限问题？或者说path拼接不对，导致路径无效呢

**Comment by Brooooooklyn** [comment]
path 应该是对的，decode 的时候 \ 被视作转义没有正确处理。路径、 link、权限都是 Rust 的工具链管理的，`napi-rs`没有做任何额外的操作。
我猜测原因可能是:

1. 缓存因素，缓存每次恢复导致权限变化
2. Gitlab-runner 是否运行在 Admin 下, 我记得 C:// 的非 user 目录是需要 Admin 权限才能读写
3. 杀毒软件或者防火墙有时候会阻止读写 `.dll` `.lib` `.pdb` 等格式的文件

**Comment by niugm** [comment]
> path 应该是对的，decode 的时候 \ 被视作转义没有正确处理。路径、 link、权限都是 Rust 的工具链管理的，`napi-rs`没有做任何额外的操作。
> 我猜测原因可能是:
> 
> 1. 缓存因素，缓存每次恢复导致权限变化
> 2. Gitlab-runner 是否运行在 Admin 下, 我记得 C:// 的非 user 目录是需要 Admin 权限才能读写
> 3. 杀毒软件或者防火墙有时候会阻止读写 `.dll` `.lib` `.pdb` 等格式的文件

好的，我再去研究下，windows上编译真是太折腾了

**Comment by niugm** [comment]
![image](https://user-images.githubusercontent.com/7264636/106591631-7868ef80-6589-11eb-9909-73b913074266.png)

我看这里的文件都已经编译出来了

**Comment by Brooooooklyn** [comment]
为什么是一个 `.exe` 文件，`crate-type = ["cdylib"]` 下应该产出一个 `.dll` 文件，你这个项目是 `napi-rs` 项目吗

**Comment by niugm** [comment]
> 为什么是一个 `.exe` 文件，`crate-type = ["cdylib"]` 下应该产出一个 `.dll` 文件，你这个项目是 `napi-rs` 项目吗

的确是这里的问题，我的src中有main.rs，为了测试用的，我把main.rs改名后，问题解决了，感谢您的帮助
