### ISSUE TITLE
Cross compiler: build error for target x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by daihy8759** [napi-rs/napi-rs#461]
```
  = note: x86_64-w64-mingw32-gcc: error: dynamic_lookup: No such file or directory
          x86_64-w64-mingw32-gcc: error: unrecognized command line option '-Wl'; did you mean '-W'?


error: aborting due to previous error; 3 warnings emitted
```

Platform: MacOs
Command: napi build --release --target x86_64-pc-windows-gnu --platform

**Comment by Brooooooklyn** [comment]
Actually cross build library for Windows on the other os is not feasible for now, because it need static link `delayimp.lib` and `node.exe` which could  only be produced on windows.

**Comment by Rdna123** [comment]
I receive the same error when compile with x86_64-pc-windows-gnu to x86_64-pc-windows-gnu

**Comment by Brooooooklyn** [comment]
Try msvc，I've never built napi-rs project target to windows-gnu, and I don't know what need to do with gnu target. Maybe I will try it in next few weeks.
