### ISSUE TITLE
Example Request: Float32Array

### ISSUE THREAD

**Issue by JulianRuiseco** [napi-rs/napi-rs#490]
I was unable to find the Float32 array in the documentation.

I am playing with something like this/

```
let mut argument = ctx.get::<JsArrayBuffer>(0)?;
  let imported_array = argument.into_typedarray(TypedArrayType::Float32, 3, 32)?;
  
  for i in 0..imported_array.get_array_length()? {
    let element: f32 = imported_array.get_element::<napi::sys::napi_typedarray_type::>(i)?;
    value += element;
  }
```

**Comment by DeMoorJasper** [comment]
@JulianRuiseco have you by any chance figured out how this works?

Can't seem to figure out how to properly use `JsTypedArray` in my case it's a `Int32Array` but should essentially work the same I assume?

**Comment by timfish** [comment]
I've not looked into this myself, but are there not existing APIs for directly passing an `ArrayBuffer`?

**Comment by DeMoorJasper** [comment]
@timfish yes could've simply used JsTypedArray thanks for pointing that out, cleaned up the code slightly. Although I was mainly just wondering if there's a more optimal way to loop over it as it's a typed array and it should be fairly safe to use an iterator over it? As you can probably tell I'm fairly new to Rust so sorry if I'm asking some weird questions.

```Rust
let js_mapping_arr: JsTypedArray = ctx.get::<JsTypedArray>(0)?;
let length: u32 = js_mapping_arr.get_array_length()?;

for i in 0..length {
    let value: i32 = js_mapping_arr.get_element::<JsNumber>(i)?.get_int32()?;
}
```

**Comment by timfish** [comment]
I see that `JsTypedArrayValue` derefs to `[u8]` and then you can [`iter()`](https://docs.rs/napi/1.4.0/napi/struct.JsTypedArrayValue.html#method.iter) over that, [chunk](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.chunks) that into groups of 4 and then convert to `i32` but I'm not sure it would be any faster than what you already have and it wouldn't be as clear.

**Comment by Brooooooklyn** [comment]
The fastest way is using `serde_json::to_string` + `JSON.parse`, see https://github.com/napi-rs/napi-rs/pull/558
