### ISSUE TITLE
Using cross for compilation instead of cargo.

### ISSUE THREAD

**Issue by josephwinston** [napi-rs/napi-rs#491]
How difficult would it be to use <https://github.com/rust-embedded/cross> instead of cargo?

**Comment by messense** [comment]
It should be possible, I've done similar stuff in https://github.com/PyO3/setuptools-rust/pull/134 and it works.

**Comment by Brooooooklyn** [comment]
We are using `zig` + `cargo-xwin` solution now, I believe it's more lightweight compared with https://github.com/rust-embedded/cross
