### ISSUE TITLE
FunctionReference alternative?

### ISSUE THREAD

**Issue by fanatid** [napi-rs/napi-rs#506]
[node-addon-api](https://github.com/nodejs/node-addon-api) allow store function with [FunctionReference](https://github.com/nodejs/node-addon-api/blob/main/doc/function_reference.md) for calls in the future. Is it possible to save function to static variable in `napi-rs`?

**Comment by Brooooooklyn** [comment]
There is `Env::create_reference` and `Env::get_reference_value`

**Comment by fanatid** [comment]
Thank you!
