### ISSUE TITLE
Serializing Rust enum to JS value loses variant information

### ISSUE THREAD

**Issue by b-zee** [napi-rs/napi-rs#507]
This:

```
#[derive(Serialize, Deserialize)]
enum MyEnum {
    A { value: u32 },
    B { value: u32 },
}

pub fn call(ctx: CallContext) -> Result<JsUnknown> {
    ctx.env.to_js_value(&MyEnum::A { value: 15 })
}
```

Results in:

```json
{ "value": 15 }
```

But should result in ([see Serde](https://serde.rs/enum-representations.html))

```json
{ "A": { "value": 15 } }
```

Otherwise there will be no way to know what Enum variant was returned.

**Comment by b-zee** [comment]
Dirty workaround for now:

```rust
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Tag<T> {
    V(T),
}
```

Usage example 

```rust
pub fn call(ctx: CallContext) -> Result<JsUnknown> {
    ctx.env.to_js_value(&Tag::V(MyEnum::A { value: 15 }))
}
```

Yields (with superfluous `type` property):

```json
{ "A": { "value": 15 }, "type": "V" }
```

**Comment by Brooooooklyn** [comment]
Because https://github.com/napi-rs/napi-rs/blob/main/napi/src/js_values/ser.rs#L239

**Comment by Beraliv** [comment]
I'm still learning Rust but can try this challenge if no one picked it before of course

**Comment by probablykasper** [comment]
fwiw the [typescript-type-def](https://crates.io/crates/typescript-type-def) crate supports this, so that could be worth looking into

**Comment by CMCDragonkai** [comment]
Is this the only way to pass structured enums from Rust back to JS?

I was thinking that an idiomatic TS version of Rust enums is:

```
{
  type: 'A',
  ...
}
```

Or:

```
['A', ...]
```

In both cases there is a disambiguator. So rust enums could be turned into JS structures like above.
