### ISSUE TITLE
N-API renamed to Node-API

### ISSUE THREAD

**Issue by orangecms** [napi-rs/napi-rs#567]
Hi there! The Node.js team [has renamed N-API to Node-API](
https://nodejs.medium.com/renaming-n-api-to-node-api-27aa8ca30ed8).

See also https://twitter.com/nodejs/status/1395065501055737859?s=19

I'll file some PRs to update some docs here if that's okay.

Thanks! ✨🐢🚀✨

**Comment by Brooooooklyn** [comment]
Close because https://github.com/napi-rs/napi-rs/pull/568, thanks
