### ISSUE TITLE
Call overhead benchmark

### ISSUE THREAD

**Issue by Brooooooklyn** [napi-rs/napi-rs#57]
**Pass JsObject to N-APi** functions vs **Encode object into Flatbuffers and decode it in the N-API side**.

**Comment by aqrln** [comment]
tangential but related idea: `serde` serializer and deserializer for napi values

**Comment by Brooooooklyn** [comment]
Some results of them: https://napi-rs.github.io/napi-rs/dev/bench/

**Comment by Brooooooklyn** [comment]
https://napi-rs.github.io/napi-rs/dev/bench/

**Comment by floatdrop** [comment]
@Brooooooklyn any plans to update these benchmarks (or integrate them into release cycle)?

**Comment by Brooooooklyn** [comment]
@floatdrop It's a litter bit hard for now, because benchmark results seems to be not stable in CI.
