### ISSUE TITLE
A possible bottleneck with tokio/promises

### ISSUE THREAD

**Issue by pimeys** [napi-rs/napi-rs#596]
We have a user with a performance regression with lots of parallel calls:

https://github.com/prisma/prisma/issues/7404

I suspect it might be the channel in the tokio/promise resolving, that acts as a bottleneck here compared to our old implementation with a http server, that can spread incoming and outgoing requests per thread better.

I'm actually thinking is the channel even needed here. Could we just get a callback and send that to the `spawn`? A bit like neon does:

https://github.com/pimeys/hello-neon/blob/main/src/lib.rs#L54-L77

**Comment by Brooooooklyn** [comment]
After few hours digging, I found that the `neon` implementation has no performance differences between the current implementation in `napi-rs`: (Note the `jemallocator` was disabled during the benchmark)

```
Running "Query" suite...
Progress: 100%

  napi-rs:
    34 802 ops/s, ±2.19%   | fastest

  neon:
    32 486 ops/s, ±2.45%   | slowest, 6.65% slower

Finished 2 cases!
  Fastest: napi-rs
  Slowest: neon
```

The benchmark code from `napi-rs`:

```rust
use napi::{CallContext, JsExternal, JsObject, JsString};

#[derive(Clone)]
pub struct QueryEngine {
  datamodel: String,
}

unsafe impl Sync for QueryEngine {}

impl QueryEngine {
  pub async fn query(&self) -> String {
    let data = serde_json::json!({
        "findFirstBooking": {
            "id": "ckovh15xa104945sj64rdk8oas",
            "name": "1883da9ff9152",
            "forename": "221c99bedc6a4",
            "description": "8bf86b62ce6a",
            "email": "9d57a869661cc",
            "phone": "7e0c58d147215",
            "arrivalDate": -92229669,
            "departureDate": 202138795,
            "price": -1592700387,
            "advance": -369294193,
            "advanceDueDate": 925000428,
            "kids": 520124290,
            "adults": 1160258464,
            "status": "NO_PAYMENT",
            "nourishment": "BB",
            "createdAt": "2021-05-19T12:58:37.246Z",
            "room": { "id": "ckovh15xa104955sj6r2tqaw1c", "name": "38683b87f2664" }
        }
    });

    serde_json::to_string(&data).unwrap()
  }
}

#[js_function(1)]
fn new_engine(ctx: CallContext) -> napi::Result<napi::JsExternal> {
  let a = ctx.get::<JsString>(0)?.into_utf8()?;
  let model = a.into_owned()?;
  let model_len = model.len();
  let qe = QueryEngine { datamodel: model };
  ctx.env.create_external(qe, Some(model_len as i64))
}

#[js_function(1)]
fn query(ctx: CallContext) -> napi::Result<JsObject> {
  let ext = ctx.get::<JsExternal>(0)?;
  let qe = ctx.env.get_value_external::<QueryEngine>(&ext)?;
  let qe = qe.clone();
  ctx
    .env
    .execute_tokio_future(async move { Ok(qe.query().await) }, |env, v| {
      env.create_string_from_std(v)
    })
}

pub fn register_js(exports: &mut JsObject) -> napi::Result<()> {
  exports.create_named_method("engine", new_engine)?;
  exports.create_named_method("query", query)?;
  Ok(())
}
```

And I have also implemented the `execute_tokio_future` in the **Static way like the neon one**, and there is no performance different between the old and new implementation.

**Comment by Brooooooklyn** [comment]
You can find the benchmark code in `query-bench` branch

**Comment by pimeys** [comment]
What about saturating all the cores as much as possible? Like, spawn 1000 promises at the same time, do something on the rust side that takes (asynchronously) about 20-30 millisecods and measure that. What I see is if I measure sequential actions, we're good. But if pushing more promises at the same time, we hit some bottleneck here. Haven't tested neon in this fashion yet, but our http server implementation is about 1.5-2x faster compared to napi with a larger throughput.

**Comment by Brooooooklyn** [comment]
> What about saturating all the cores as much as possible? Like, spawn 1000 promises at the same time, do something on the rust side that takes (asynchronously) about 20-30 millisecods and measure that.

Oh I just realized the benchmark is running serially, after change the the benchmark code into parallel mode, the old implementation became slow:

```ts
  b.add('napi-rs', async () => {
      await Promise.all(Array.from({ length: 100 }).map(() => query(e)))
    }),
    b.add('neon', async () => {
      await Promise.all(
        Array.from({ length: 100 }).map(() => engineQueryAsync()),
      )
    }),
```
got the result:

```
Running "Query" suite...
Progress: 100%

  napi-rs:
    785 ops/s, ±1.41%     | slowest, 51.6% slower

  neon:
    1 622 ops/s, ±0.99%   | fastest

Finished 2 cases!
  Fastest: neon
  Slowest: napi-rs
```

After refactor the `tokio_rt` and remove `channel` in it:

```
Running "Query" suite...
Progress: 100%

  napi-rs:
    1 585 ops/s, ±3.80%   | fastest

  neon:
    1 401 ops/s, ±3.09%   | slowest, 11.61% slower

Finished 2 cases!
  Fastest: napi-rs
  Slowest: neon
```

**Comment by pimeys** [comment]
Nice! Thanks for validating my concerns!
