### ISSUE TITLE
Tokio promise rejection

### ISSUE THREAD

**Issue by Progdrasil** [napi-rs/napi-rs#610]
I am working with some asynchronous code that is fallible. And the failure mode is a structure with multiple fields which I would like to pass to the javascript side. 

Take for example a simple [`reqwest::post`](https://docs.rs/reqwest/0.11.3/reqwest/struct.RequestBuilder.html#method.send), there might be an error sending the message, but you might receive an error from the remote in the response object. You might end up with a signature such as the following

```rust
async fn login(username: &str, password: &str) -> Result<Result<SuccessObj, RemoteError>, reqwest::Error>
```

So when launching the future with `Env::execute_tokio_future` the resolver's `data` parameter is of a `Result` as well. . Currently if this result is an error, the only way I have to send it as is to the JS side is to serialize it with serde and to parse the json from the js side, which is not elegant.

Rust side
```rust
ctx.env.execute_tokio_future(
    login(&username, &password).map(|res| res.map_err(|e| Error::from_reason(e.to_string())),
    |&mut env, data| match data {
        Ok(d) => env.to_js_value(d),
        Err(e) => Err(Error::from_reason(serde_json::to_string(e)?)
    }
)
```
JavaScript side
```js
login("username", "bad password").catch((e) => {
    const error = JSON.parse(e.message);
    errorHandlingLogic(error);
});
```

It would be much more ergonomic to be able to send and `NapiValue` in the error of the resolver as well. Personally something more along the lines of
```rust
ctx.env.execute_tokio_future(
    login(&username, &password).map(|res| res.map_err(|e| Error::from_reason(e.to_string())),
    |&mut env, data| match data {
        Ok(d) => env.to_js_value(d),
        Err(e) => Err(Error::custom(e))
    }
)
```
JavaScript side
```js
login("username", "bad password").catch(errorHandlingLogic);
```

**Comment by Brooooooklyn** [comment]
You can use [`or_else`](https://doc.rust-lang.org/std/result/enum.Result.html#method.or_else) to make `Result` always return `JsValue`:

`res.or_else(|e| env.create_string("Error"))`

**Comment by wemeetagain** [comment]
Using `or_else` doesn't necessarily work (ergonomically) if you need to do something with a returned value.

eg:

```rust
#[napi]
pub fn process_data(env: Env, data: JsBuffer) -> Result<JsObject> {
  let data = data.into_ref()?;
  env.execute_tokio_future(async move {
    // do something with data that may error
    // ...
    Ok(data)
  }, move |env, data| {
    data.unref(*env)?;
    env.get_undefined()
  })
}
```

If the future returns Err, there will be a memory leak (data is never unrefed).
`or_else` doesn't work in this case since `data` has been moved into the future.
The (un-ergonomic) solution for now is that the future return type needs to be wrapped in an additional Result<> such that the outer result is always Ok so that the resolver is always run.
