### ISSUE TITLE
ThreadSafe functions can cause an SIGABRT

### ISSUE THREAD

**Issue by pimeys** [napi-rs/napi-rs#612]
The usual test repo:

https://github.com/pimeys/napi-bug-repo

What this does is an asynchronous function, that calls a stored thread-safe function N amount of times. And from the JavaScript side we call this function as fast as we can. What I'd expect to happen:

```
call_no_263_53
call_no_263_54
call_no_263_55
call_no_263_56
call_no_263_57
call_no_263_58
call_no_263_59
call_no_263_60
call_no_263_61
call_no_263_62
call_no_263_63
call_no_263_64
call_no_263_65
call_no_263_66
call_no_263_67
call_no_263_68
call_no_263_69
call_no_263_70
call_no_263_71
```

This should continue until `9999_99`.

What actually happens:

```
call_no_263_69
call_no_263_70
call_no_263_71
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `0`', /home/pimeys/code/napi-rs/napi/src/threadsafe_function.rs:411:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
fish: Job 1, 'node index.js' terminated by signal SIGABRT (Abort)
```

I found this by accident when I was trying to put some heat to our logger. It's quite hard to reproduce with Prisma and our current logging levels, but I was able to get the crash by using the log level `trace` and called a query as fast as I could in a tight loop.

The log level is not allowed in the released client, but eventually somebody will have enough callbacks to trigger the abort.

**Comment by pimeys** [comment]
You can prevent this by just sleeping a bit (even a millisecond) in the call before calling the callback.

**Comment by pimeys** [comment]
And the other way to prevent this is to use the `Blocking` mode and set the channel size to as small as possible. `1` will not abort, so doesn't `3`, but with `10` I can get this to abort already.

**Comment by Brooooooklyn** [comment]
Remove this line: https://github.com/pimeys/napi-bug-repo/blob/main/src/lib.rs#L33 seems to fix this issue.
The `unref` here seems to fix the issue that thread safe function prevented Node.js process to exit. Becaue the `ThreadSafeFunction` in constructor is used to `clone` in `call`. 
But in your code example, `ThreadSafeFunction` is behind a `Arc<RwLock>`, **clone** this structure doesn't trigger the **clone** in `ThreadSafeFunction` inner. So you don't need to call `unref` in constructor, and it seems like `ThreadSafeFunction` will not prevent the Node.js to exit.

**Comment by Brooooooklyn** [comment]
`thread '<unnamed>' panicked at 'assertion failed: (left == right) ` this happened after `drop` to be called in `ThreadSafeFunction`, and I noticed that insert some ***slow*** logic like `print something` after the `ThreadSafeFunction::call` would prevent this panic happen.

The panic happend because this line: https://github.com/napi-rs/napi-rs/blob/main/napi/src/threadsafe_function.rs#L411. And it looks weird, the `10` is  the value of `napi_pending_exception`: https://github.com/napi-rs/napi-rs/blob/main/sys/src/lib.rs#L120. And it should not happen after the `napi_get_and_clear_last_exception` called. I think it's a `Node.js` bug here.

**Comment by Brooooooklyn** [comment]
This issue seems to be fixed in the latest Node.js
