### ISSUE TITLE
Wrapped native objects can cause memory leaks

### ISSUE THREAD

**Issue by devongovett** [napi-rs/napi-rs#613]
I noticed while benchmarking Parcel's [source map](https://github.com/parcel-bundler/source-map) package that the process used a very large amount of memory - over 20 GB in some cases - before being killed by macOS. In these benchmarks, instances of a native class are created in a loop. They should be short lived and get garbage collected by v8 almost immediately. However, the native objects seem to be leaking somehow.

Here's a smaller reproduction: https://github.com/devongovett/napi-memory-leak. It is just a struct with a `Vec` that holds 100,000 bytes of data. From JS, we create an instance of this class 500,000 times in a loop and watch the memory usage. I would expect these instances to be garbage collected, and the native memory to be freed, but it seems that the memory usage only grows.

Steps to run it:

1. git clone git@github.com:devongovett/napi-memory-leak.git
2. cd napi-memory-leak
3. yarn
4. yarn build-release
5. node test.js
6. Observe memory usage with Activity Monitor

Any ideas?

**Comment by Brooooooklyn** [comment]
After a quick debug, I found there is 2 problems in you example.

The first: For the `wrap` situation, developers should call `adjust_external_memory` after `warp` if ***wrapped object is big***, (I should document this point). See [napi_adjust_external_memory](https://nodejs.org/api/n-api.html#n_api_napi_adjust_external_memory):

Developers need do this manually beacuse `napi-rs` can not caculate the actually size allocated for the native object, see: https://github.com/napi-rs/napi-rs/issues/372#issuecomment-748866431

But the memory is still growth after these codes added:

```rust
let size = test.data.len() as i64;
ctx.env.wrap(&mut this, test)?;
ctx.env.adjust_external_memory(size)?;
```

And the `finalize` function passed to the `napi_wrap` didn't be called at all, memory even keeping growth.

Event I trigger `global.gc()`:

```diff
// node --expose-gc ./test.js
for (let i = 0; i < 500000; i++) {
    let sm = new SourceMap()
    if (i % 1000 === 0) {
+     displayMemoryUsageFromNode()
+     global.gc()
    }
  }
```

<details>
  <summary>displayMemoryUsageFromNode</summary>


╔═══════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss   │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟───────┼───────────┼──────────┼──────────┼──────────────╢
║ +1 MB │  0 B      │ +5.73 kB │ +40 B    │  0 B         ║
╚═══════╧═══════════╧══════════╧══════════╧══════════════╝

╔═══════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss   │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟───────┼───────────┼──────────┼──────────┼──────────────╢
║ +1 GB │ +266 kB   │ +1.13 MB │ +40 B    │  0 B         ║
╚═══════╧═══════════╧══════════╧══════════╧══════════════╝

╔═══════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss   │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟───────┼───────────┼──────────┼──────────┼──────────────╢
║ +2 GB │ +266 kB   │ +283 kB  │ +40 B    │ -162 kB      ║
╚═══════╧═══════════╧══════════╧══════════╧══════════════╝

╔══════════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss      │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟──────────┼───────────┼──────────┼──────────┼──────────────╢
║ +3.01 GB │ +266 kB   │ +987 kB  │ +40 B    │ -162 kB      ║
╚══════════╧═══════════╧══════════╧══════════╧══════════════╝

╔══════════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss      │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟──────────┼───────────┼──────────┼──────────┼──────────────╢
║ +4.01 GB │ +266 kB   │ +1.41 MB │ +40 B    │ -162 kB      ║
╚══════════╧═══════════╧══════════╧══════════╧══════════════╝

╔══════════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss      │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟──────────┼───────────┼──────────┼──────────┼──────────────╢
║ +5.01 GB │ +791 kB   │ +84.2 kB │ -162 kB  │ -162 kB      ║
╚══════════╧═══════════╧══════════╧══════════╧══════════════╝
</details>


And if I insert some async logic every 1000 times in the loop, the `gc` seems work properly again:

```diff
+function sleep() {
+  return new Promise((resolve) => setTimeout(resolve, 1000))
+}

+async function main() {
  for (let i = 0; i < 500000; i++) {
    let sm = new SourceMap()
    if (i % 1000 === 0) {
      displayMemoryUsageFromNode()
+     await sleep()
    }
  }
+}

+main()
```

<details>
  <summary>displayMemoryUsageFromNode</summary>

╔════════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss    │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟────────┼───────────┼──────────┼──────────┼──────────────╢
║ +86 kB │  0 B      │ +5.79 kB │ +40 B    │  0 B         ║
╚════════╧═══════════╧══════════╧══════════╧══════════════╝

╔═════════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss     │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟─────────┼───────────┼──────────┼──────────┼──────────────╢
║ +102 MB │ +524 kB   │ -1.22 MB │ -170 kB  │ -162 kB      ║
╚═════════╧═══════════╧══════════╧══════════╧══════════════╝

╔═════════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss     │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟─────────┼───────────┼──────────┼──────────┼──────────────╢
║ +135 MB │ +524 kB   │ -469 kB  │ -170 kB  │ -162 kB      ║
╚═════════╧═══════════╧══════════╧══════════╧══════════════╝

╔═════════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss     │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟─────────┼───────────┼──────────┼──────────┼──────────────╢
║ +102 MB │  0 B      │ -975 kB  │ -170 kB  │ -162 kB      ║
╚═════════╧═══════════╧══════════╧══════════╧══════════════╝

╔═════════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss     │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟─────────┼───────────┼──────────┼──────────┼──────────────╢
║ +103 MB │  0 B      │ -1 MB    │ -170 kB  │ -162 kB      ║
╚═════════╧═══════════╧══════════╧══════════╧══════════════╝

╔═════════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss     │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟─────────┼───────────┼──────────┼──────────┼──────────────╢
║ +103 MB │  0 B      │ -1.09 MB │ -170 kB  │ -162 kB      ║
╚═════════╧═══════════╧══════════╧══════════╧══════════════╝

╔═════════╤═══════════╤══════════╤══════════╤══════════════╗
║ rss     │ heapTotal │ heapUsed │ external │ arrayBuffers ║
╟─────────┼───────────┼──────────┼──────────┼──────────────╢
║ +101 MB │ -3.15 MB  │ -1.1 MB  │ -170 kB  │ -162 kB      ║
╚═════════╧═══════════╧══════════╧══════════╧══════════════╝
</details>

It seems like a bug in Node.js? I will submit a issue to Node.js if I confirmed that.

**Comment by devongovett** [comment]
Ah, that makes sense! I was wondering if it was something like that. Thanks for looking into it!
