### ISSUE TITLE
Create JsObject reference

### ISSUE THREAD

**Issue by Huntragon** [napi-rs/napi-rs#646]
I'm trying to create an JsObject (obtained as an argument) reference in order to share it between threads (so I can share the object to a Task, and then compute that object in a different thread instead of having to convert the whole object to a Rust struct). My object is quite big in my use case, so conversion takes quite a bit of time. 

It seems that `into_ref()` is only implemented for a few data types (JsString, JsArrayBuffer), so it's not aplicable to my use case. There's also `env.create_reference<T>` which returns a `Ref<()>`, which I can then dereference using `env.get_reference_value<T>`, however, this requires access to `env`, which I don't have in the compute function of the task.
Is there any way I can do this, or do I need to process the object argument in the `js_function`?

Example code:
```
#[js_function(1)]
fn get_json_async(ctx: CallContext) -> Result<JsObject>{
    let root = ctx.get::<JsObject>(0)?.into_ref()?;
    let start = Instant::now();
    let async_task = AsyncJson{
        obj: root,
        start
    };
    let t = ctx.env.spawn(async_task)?;
    Ok(t.promise_object())
}

struct AsyncJson{
    obj: Ref<JsObject>,
    start: Instant
}

impl Task for AsyncJson{
    type Output = String;
    type JsValue = JsString;

    fn compute(&mut self) -> Result<Self::Output> {
        let mut node = Node::new();
        create_node_recursive(&self.obj, &mut node);
        println!("Took {} us to create internal struct", self.start.elapsed().as_micros());
        let json = serde_json::to_string(&node).map_err(|err|{napi::Error::from_reason(format!("Error serializing to JSON: {}", err))})?;
        println!("Took {} us to serialize struct to JSON", self.start.elapsed().as_micros());
        Ok(json)
    }

    fn resolve(self, env: Env, output: Self::Output) -> Result<Self::JsValue> {
        self.obj.unref(env);
        env.create_string_from_std(output)
    }

    fn reject(self, env: Env, err: Error) -> Result<Self::JsValue> {
        self.obj.unref(env);
        Err(err)
    }
}
```

**Comment by Brooooooklyn** [comment]
> in order to share it between threads

No, you can't do this because `JsObject` can only be used in the `Main thread`. The reason why `JsBuffer` and `JsArraybuffer` can be called with `into_ref` is because the `Ref` inner them is actually `Vec<u8>` data rather than the  `JavaScript` Object, so it could be shared between threads.

**Comment by Huntragon** [comment]
Ok, got it. Thanks
