### ISSUE TITLE
About passing data from Rust to Node.js

### ISSUE THREAD

**Issue by huming2207** [napi-rs/napi-rs#706]
Hi @Brooooooklyn 

I would like to know is it possible to pass events (or any other wrapped objects) to Node.js with `napi-rs`? For example, something like `EventEmitter` with `node-addon-api`  in C++?

Regards,
Jackson

**Comment by Brooooooklyn** [comment]
Like this?

```rust

#[js_function]
fn create_stream(ctx: CallContext) -> napi::Result<napi::JsObject> {
  let mut result = ctx.env.create_object()?;
  result.set_named_property("onData", ctx.env.create_function("onData", on_data))?;
  ctx.env.wrap(&mut result, NativeStruct {});
  Ok(result)
}

#[js_function]
fn on_data(ctx: CallContext) -> napi::Result<napi::JsUndefined> {
  let this: JsObject = ctx.env.this_unchecked();
  let native_obj = ctx.env.unwrap::<NativeStruct>(&this)?;
  ...
  ctx.env.get_undefined()
}

```

**Comment by huming2207** [comment]
> Like this?
> 
> ```rust
> #[js_function]
> fn create_stream(ctx: CallContext) -> napi::Result<napi::JsObject> {
>   let mut result = ctx.env.create_object()?;
>   result.set_named_property("onData", ctx.env.create_function("onData", on_data))?;
>   ctx.env.wrap(&mut result, NativeStruct {});
>   Ok(result)
> }
> 
> #[js_function]
> fn on_data(ctx: CallContext) -> napi::Result<napi::JsUndefined> {
>   let this: JsObject = ctx.env.this_unchecked();
>   let native_obj = ctx.env.unwrap::<NativeStruct>(&this)?;
>   ...
>   ctx.env.get_undefined()
> }
> ```

Oh got it, thanks!
