### ISSUE TITLE
Not calling `unref` can cause the program to not exit

### ISSUE THREAD

**Issue by pimeys** [napi-rs/napi-rs#724]
Hey, so while debugging [this issue](https://github.com/prisma/prisma/issues/8989), I found out the way to cut the memory leak was to _not unref_ the threadsafe function:

https://github.com/prisma/prisma-engines/pull/2196/files

This fixes the leak, but introduces another problem: the program will not exit cleanly. I couldn't find a good smaller reproduction, but when compiling the node api query engine with `cargo build -p query-engine-node-api`, copying `target/debug/libquery_engine.so` to somewhere with a `.node` ending, and running the following script:

```javascript
const engine = require('./libquery_engine.so.node');

async function main() {
  const datamodel = `
      datasource db {
        provider = "postgres"
        url      = "postgresql://postgres:prisma@localhost:5432/"
      }

      generator js {
        provider        = "prisma-client-js"
      }

      model Test {
        id    Int     @id
        field String?
      }
    `;

  const conn = new engine.QueryEngine({
    datamodel: datamodel,
    logLevel: "debug",
    logQueries: true,
    configDir: "."
  }, (_err, log) => {
    console.log(log);
  });

  await conn.connect();

  const query = {
    query: `mutation { queryRaw(query: "SELECT 1") }`,
    variables: {},
  };

  console.log(conn.query(JSON.stringify(query), "{}"));

  await conn.disconnect();
}
main()
```

We see the program never exiting. Is it correct to remove the `unref`? And if so, is there a way to get a program to exit normally?

**Comment by Brooooooklyn** [comment]
I think I've found the root cause, I'm refactoring the codes of  `query-engine-node-api`
