### ISSUE TITLE
Assertion `val->IsArrayBufferView()' failed

### ISSUE THREAD

**Issue by kdy1** [napi-rs/napi-rs#735]
I'm not sure about the cause, but I think I faced this when I tried to use buffer or string mixed.

Log: https://github.com/vercel/next.js/pull/28883/checks?check_run_id=3560578176#step:4:353

I'm not sure about what information I should provide, so please ask me if there's one

**Comment by Brooooooklyn** [comment]
This error usually occurs when calling `into_value()` on a JavaScript value that is not a Buffer, for example: 


```rust
#[js_function(1)]
fn get_buffer_length(ctx: CallContext) -> Result<JsNumber> {
  let js_buffer: JsBuffer = ctx.get(0)?; // fine
  let buffer_value = js_buffer.into_value()?; // panic
}
```

```ts
getBufferLenght("NOT A BUFFER")
```

`ctx.get` isn't perform runtime typecheck for performance, but maybe it is worse to provide another API which perform runtime typecheck and provide more readable error message for non-performance sensitive scenario.

**Comment by kdy1** [comment]
Oh, thanks! I wasn't aware of it. I think I can fix it.
Should I close this issue, or left this as an issue for readable error messages?

**Comment by Brooooooklyn** [comment]
Just left it, I will add a new API in `CallContext` for runtime typecheck. Thanks!

**Comment by Brooooooklyn** [comment]
Closed in https://github.com/napi-rs/napi-rs/pull/696

You can perform strict runtime tyepecheck by `strict` param:

```rs
#[napi(strict)]
fn fibonacci(n: u32) -> u32 {
  match n {
    1 | 2 => 1,
    _ => fibonacci(n - 1) + fibonacci(n - 2),
  }
}
```
