### ISSUE TITLE
`#[napi]` questions

### ISSUE THREAD

**Issue by Mesteery** [napi-rs/napi-rs#758]
Hello I have some questions about the new `#[napi]`:
 - how to make a class with a static method that returns an instance (which is not the constructor, of course)
 - how to export a const/static?
 - ...I have (or probably will have) more, but these are the only ones that come to mind at the moment.

Thanks a lot for your work!

**Comment by forehalo** [comment]
- checkout `examples\napi\src\class.rs`, there is an `new`  function which is a static function to construct an class
- the `const/static` is not supported yet

We will ship the new docs soon to clear all the stuff related to the `#[napi]` macro.

**Comment by Mesteery** [comment]
> checkout examples\napi\src\class.rs, there is an new function which is a static function to construct an class

I saw this. But I was talking about a static method other than the constructor returning an instance of the class/struct. Currently it doesn't work throwing an error like "NapiToValue".

**Comment by forehalo** [comment]
@Mesteery nope, it is a **static method**, only the one decorated with `#[napi(constructor]` would be transformed to constructor. see `examples/napi/type.d.ts` as well.

```rust
#[napi]
impl Animal {
  #[napi]
  pub fn get_kind() -> Kind {
    Kind::Dog
  }
}
```
```ts
// type.d.ts
export class Animal {
  static getKind() -> Kind
}
```
![image](https://user-images.githubusercontent.com/8281226/134672469-c565ea3d-58fa-453c-b343-4ed200994c18.png)

**Comment by Mesteery** [comment]
Okay, I get this. But I would have liked to know if it is possible to return an instance of the class in a static method.
E.g.
```rust
#[napi]
impl Klass {
  #[napi]
  pub fn fromSomething(...) -> Self {}
}
```
```js
Klass.fromSomething(...)
```

**Comment by forehalo** [comment]
> But I would have liked to know if it is possible to return an instance of the class in a static method.

Check that example pls.

To be clear, any functions, include static methods,  that return a rust struct to node are only allowed if the structs' definitions are marked as constructor:
```rust
#[napi(constructor)]
struct S {
  pub name: String,
  pub nick_name: String,
}
```

In other words, the `ToNapiValue` trait will only be auto implemented in such case, because we won't be able to know the arguments used to call node's [`napi_new_instance`](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html#n_api_napi_new_instance):

```rust
#[napi]
impl S {
  #[napi]
  fn create_s(name: String) -> Self {
    // ..
  }
}

// GENERATED CONTENT
// under the hood
fn __napi__create_s(env: napi_env, cb: napi_cb) -> napi_val {
  // what should the `args` be like?
  // struct ctor makes us available by iterating it's all fields like:
  //   let args = [name, nick_name];
  // but fn ctor is not possible to let us detect the args content:
  //   the ctor requires a string, is it name or nick_name?
  napi_new_instance(env, ctor, args, argc, ret)
}
```

another approach to provide static instance factory is writing a js wrapper:

```js
const { S } = require('./index.node')

S.create = (name: String) => {
  return new S(name)
}

```

More detail will be introduced in the coming docs.

**Comment by Mesteery** [comment]
Okay, does this work?
```rust
#[napi]
impl S {
  #[napi]
  fn create_s(name: String) -> Self {
    // ..
  }

  #[napi]
  fn create_a() -> Self {}
}
```

**Comment by forehalo** [comment]
The compiler will complain if not

**Comment by Mesteery** [comment]
Exactly... that's what happens

**Comment by Mesteery** [comment]
```rs
struct NativeKlass {
  something: String,
}

#[napi(constructor)]
struct Klass {
  klass: NativeKlass,
}

#[napi]
impl Klass {
  #[napi]
  pub fn new(something: String) -> Self {
    Self {
      klass: NativeKlass {
        something: something,
      },
    }
  }
}
```
I have another question, how can I have a private attribute? This doesn't compile.
```
pattern does not mention field `klass`
missing field `klass` rustc (E0027)
```

**Comment by forehalo** [comment]
@Mesteery making struct itself as `constructor` requires all it's fields to be public.

you could do it currently by:

```rust
struct NativeKlass {
  something: String,
}

#[napi]
struct Klass {
  klass: NativeKlass,
}

#[napi]
impl Klass {
  #[napi(constructor)]
  pub fn new(something: String) -> Self {
    Self {
      klass: NativeKlass { something },
    }
  }
}
```

If you meet other confusing compiling errors, you would probably use the `napi_bindgen` branch of napi/napi-derive to get the latest updates, , which introduces more friendly error messages.

**Comment by forehalo** [comment]
@Mesteery

> By the way, this join my first question: how to have a struct with privates attributes and two (or more) static method returning class' instance



It's not possible for a class to have two or more constructors, right?

The function decorated with `#[napi(constructor)]` is the one called when `new Class()` called in node. 

For static class factory, like `Class.create()`, it's quite tricky to be done in rust side because the limit of napi. The easiest way is wrapping the things in js.

```js
import { Klass } from './index.node'

Klass.fromSpecialSomething = (something) => {
  return new Klass(something)
}

export { Klass }
```

If you still prefer them to be possible in rust side, I would give it a try and I can't promise you the usage would be clean enough.

**Comment by forehalo** [comment]
> Yeah sure, but it would have been better if it was supported out of the box.

it's impossible

**Comment by Mesteery** [comment]
I assume this is solved by https://github.com/napi-rs/napi-rs/commit/cedb7b163b88f13213eb70cf0478bd5eb6b5d935? Thank you!
