### ISSUE TITLE
Should napi-rs be a dependency or devDependency?

### ISSUE THREAD

**Issue by alcuadrado** [napi-rs/napi-rs#78]
Hi,

I'm learning rust to be able to create N-API  rust modules, so I find this project incredibly interesting.

I'm creating my first module, and I noticed that the README indicates that `napi-rs` should be a dependency, but it's not one in the example module.

Maybe it should be a dev dependency?

**Comment by Brooooooklyn** [comment]
Yes, it should be devDependency, I will update `README` soon

**Comment by alcuadrado** [comment]
Thanks for the quick response!
