### ISSUE TITLE
how to handle reference counted data when wrapped in javascript

### ISSUE THREAD

**Issue by bmacnaughton** [napi-rs/napi-rs#780]
i am seeing unexpected/unpredictable behavior where the reference count looks like rust is not seeing javascript delete operations.

my repro code:
```
#![deny(clippy::all)]

#[macro_use]
extern crate napi_derive;

use std::str;
use std::string::String;
use std::rc::Rc;

use napi::{
  Env, CallContext, Result,
  JsUndefined, JsBuffer, JsObject, JsUnknown,
};


#[cfg(all(
  any(windows, unix),
  target_arch = "x86_64",
  not(target_env = "musl"),
  not(debug_assertions)
))]
#[global_allocator]
static ALLOC: mimalloc::MiMalloc = mimalloc::MiMalloc;


enum ArgType {
  Buffer(JsBuffer),
  Thing(Rc<SubThing>)
}

pub struct Thing {
  pub ref_thing: Rc<SubThing>,
}

pub struct SubThing {
  data: Vec<String>,
}

impl Thing {
  pub fn new(data: Rc<SubThing>) -> Self {
    Thing {
      ref_thing: data,
    }
  }

  pub fn clone(self) -> Thing {
    let ref_thing: Rc<SubThing> = Rc::clone(&self.ref_thing);
    Thing {
      ref_thing
    }
  }
}

/// JavaScript-callable constructor to create a Thing
#[js_function(1)]
fn constructor(ctx: CallContext) -> Result<JsUndefined> {
  let mut this: JsObject = ctx.this_unchecked();

  let arg = get_arg(&ctx)?;

  // if they passed an instance then it's a quick clone of the data.
  if let ArgType::Thing(existing) = arg {
    let aho = Thing::new(existing);
    ctx.env.wrap(&mut this, aho)?;
    return ctx.env.get_undefined()
  }

  let data: Vec<String> = Vec::new();
  let sub_thing = SubThing {data};
  let thing = Thing {
    ref_thing: Rc::new(sub_thing)
  };


  ctx.env.wrap(&mut this, thing)?;

  ctx.env.get_undefined()
}

fn get_arg(ctx: &CallContext) -> Result<ArgType> {
  let something = ctx.get::<JsUnknown>(0)?;

  let arg_type = something.get_type();

  if let Err(e) = arg_type {
    return Err(e);
  }

  let object: JsObject;
  unsafe {
    object = something.cast::<JsObject>();
  }

  if object.is_buffer()? {
    unsafe {
      let buffer: JsBuffer = something.cast::<JsBuffer>();
      return Ok(ArgType::Buffer(buffer));
    }
  }

  // this line should throw if the object is not an AhoCorasick instance.
  let thing: &mut Thing = ctx.env.unwrap(&object)?;
  let sub_thing: Rc<SubThing> = Rc::clone(&thing.ref_thing);

  Ok(ArgType::Thing(sub_thing))
}

#[module_exports]
fn init(mut exports: JsObject, env: Env) -> Result<()> {
  let thing = env.define_class("Thing", constructor, &[
  ])?;
  exports.set_named_property("Thing", thing)?;

  exports.create_named_method("info", info)?;
  Ok(())
}


#[js_function(1)]
fn info(ctx: CallContext) -> Result<JsObject> {
  let this: JsObject = ctx.get::<JsObject>(0)?;
  //let this: JsObject = ctx.this_unchecked();

  let thing: &mut Thing = ctx.env.unwrap(&this)?;

  let mut o: JsObject = ctx.env.create_object()?;
  let ref_count = ctx.env.create_int32(Rc::strong_count(&thing.ref_thing) as i32)?;
  let string_count = ctx.env.create_int32(thing.ref_thing.data.len() as i32)?;


  o.set_named_property("refCount", ref_count)?;
  o.set_named_property("stringCount", string_count)?;

  Ok(o)
}
```

repro steps:
(node v14.17.3, though i don't think the node version matters)
- `T = require('./index.linux-x64-gnu.node')`
- `a = new T.Thing(Buffer.from('x'))`
- `T.info(a)` => `{ refCount: 1, stringCount: 0 }`
- `b = new T.Thing(a)`
- `T.info(a)` => `{ refCount: 2, stringCount: 0 }`
- `c = new T.Thing(b)`
- `T.info(a)` => `{ refCount: 3, stringCount: 0 }`
- `delete a` => `true`
- `T.info(b)` => `{ refCount: 3, stringCount: 0 }`
- `delete b` => `true`
- `T.info(c)` => `{ refCount: 3, stringCount: 0 }`
- `d = new T.Thing(c)`
- `T.info(d)` => `{ refCount: 4, stringCount: 0 }`

but:
- `a = new T.Thing(Buffer.from('x'))`
- `T.info(a)` => `{ refCount: 1, stringCount: 0 }`
- `b = new T.Thing(a)`
- `T.info(a)` => `{ refCount: 2, stringCount: 0 }`
- `delete a` => `true`
- `T.info(b)` => `{ refCount: 1, stringCount: 0 }`

I'm relatively new to rust so i'm guessing that i'm not setting a lifetime appropriately when an existing instance is passed in. Is that the case? Any pointers or help you can provide would be appreciated. while the example struct is simple, my real code has a bigger, more expensive-to-construct data structure and being able to reuse it is important.

I'm coming from a c/c++ node-api/node-addon-api background and think napi-rs is awesome! thank you for it.

**Comment by Brooooooklyn** [comment]
> why is it that deleting javascript references doesn't seem to translate to drop() calls consistently?

It because delete object is not meaning to trigger GC. Finalizer callback is called while GC.

**Comment by bmacnaughton** [comment]
thanks. kind of a dumb question of mine in retrospect.
