### ISSUE TITLE
Add a guide of how to setup a basic project

### ISSUE THREAD

**Issue by oyyd** [napi-rs/napi-rs#83]
It would be nice if there is a guide(or a CLI, a template repo) to help users setup a project so that they can take a try and play around as quickly as possible.

I guess building for different platforms would be the most challenging part and I hope it could be included.

**Comment by Brooooooklyn** [comment]
I've created a template project for developing node package with `napi-rs`, which including `Build/Testing/CI/Release` 
https://github.com/napi-rs/package-template
