### ISSUE TITLE
Allow throwing a SyntaxError

### ISSUE THREAD

**Issue by idan-at** [napi-rs/napi-rs#833]
Hey,

Relatd to https://github.com/swc-project/swc/discussions/2650

I'd like to refine swc error handling and throw a `SyntaxError` instead of an `Error`.

I see [here](https://github.com/napi-rs/napi-rs/blob/main/crates/napi/src/error.rs#L21) that some global JS errors are supported, but not `SyntaxErrorr`.

Any objections to support it? 

If you're fine with adding it, I can contribute.

EDIT: I see `napi` doesn't have an API for that :( Any suggestions?

**Comment by Brooooooklyn** [comment]
The original Node-API doesn't expose ability to create `SyntaxError`: https://nodejs.org/api/n-api.html#napi_create_type_error

**Comment by idan-at** [comment]
you're correct, [I'm working on it](https://github.com/nodejs/node/pull/40736) :)

**Comment by Brooooooklyn** [comment]
See https://github.com/napi-rs/napi-rs/releases/tag/napi%401.7.8

There is a workaround for this scenario

**Comment by idan-at** [comment]
thank you! now that I take a look better, seems like `swc` actually needs `create_syntax_error` ([here](https://github.com/swc-project/swc/discussions/2650)).

do you think we need to add it in a similar way or wait for the napi PR to be merged & deployed?

**Comment by idan-at** [comment]
@Brooooooklyn hey,

https://github.com/nodejs/node/pull/40736 was merged and released in v17.2.0 (https://github.com/nodejs/node/pull/40983).

I'd be happy to contribute to napi-rs with this new addition. Can you please guide me?

should I just add it [here](https://github.com/napi-rs/napi-rs/blob/main/crates/sys/src/lib.rs) under the `napi8` feature?
