### ISSUE TITLE
Document more explicitly that `rustup` is required to be installed if `--target` is not specified.

### ISSUE THREAD

**Issue by ShadowJonathan** [napi-rs/napi-rs#869]
On the [npm page](https://www.npmjs.com/package/@napi-rs/cli?activeTab=readme), it is not clear that `rustup` is specified to be installed, and/or that `--target` will absolve this pre-install requirement.

This is a bit of a rough edge, I observed someone trying to make rust-node bindings work, which were mysteriously failing due to `rustup` not being installed.

`rustup` should not always be expected to be installed, it is a developer tool, which may be absent in environments like container builds, which should only contain build tools (`cargo`, `rustc`, etc.)

**Comment by Brooooooklyn** [comment]
> rustup should not always be expected to be installed, it is a developer tool, which may be absent in environments like container builds, which should only contain build tools (cargo, rustc, etc.)

Yes, you are right.

I will  add document: **If no --target specified, you need `rustup` installed so that napi cli could determinded the default target**.

**Comment by Brooooooklyn** [comment]
Documented both in https://napi.rs/docs/cli/build and help info in `cli`.

**Comment by JensTimmerman** [comment]
Can this documentation be enhanced a little bit? I found out I need to pass --target now somewhere, but what should the value be? What are the possible values?

**Comment by JensTimmerman** [comment]
I believe it needs to be one of the values in the output of `rustc --print target-list`
