### ISSUE TITLE
implement coerce_to_bool?

### ISSUE THREAD

**Issue by bmacnaughton** [napi-rs/napi-rs#870]
i've been working with napi-rs - it's an awesome package, thank you for the work.

i'm also still getting comfortable with rust, so this might be done somewhere. but if it is not done, do you think it makes sense? if you do, then i'll work on a PR to see if i can fit it into your framework.

i've implemented the following just to see how it works, so the biggest question for me is how to generalize it and fit it into napi-rs. one thought is that CoerceToBoolean should be a trait that the other js types implement. but it doesn't need to be because it seems like a blanket implementation (not sure how to do that) could implement it because the operation is independent of the type being coerced.

```
#[js_function(1)]
fn get_as_bool(ctx: CallContext) -> Result<JsBoolean> {
    let mut val: napi_value = std::ptr::null_mut();
    let jsu: JsUnknown = ctx.get::<JsUnknown>(0)?;

    unsafe {
        let mut status: napi_sys::napi_status = napi_sys::napi_coerce_to_bool(
            ctx.env.raw(),
            jsu.raw(),
            &mut val
        );
        if status != napi_sys::Status::napi_ok {
            let e = napi::Error {status: Status::InvalidArg, reason: "hmmm".to_string()};
            napi::JsTypeError::from(e).throw_into(ctx.env.raw());
        }
        let b: &mut bool = &mut false;
        status = napi_sys::napi_get_value_bool(ctx.env.raw(), val, &mut *b);
        if status != napi_sys::Status::napi_ok {
            let e = napi::Error {status: Status::InvalidArg, reason: "hmmm2".to_string()};
            napi::JsTypeError::from(e).throw_into(ctx.env.raw());
        }

        ctx.env.get_boolean(*b)
    }
}
```

obviously, your check_status! macro would make things nicer.

any comments about how i've done the above are welcome as well - i'm still learning and feedback is helpful.

**Comment by Brooooooklyn** [comment]
Seems like `coerce_to_bool` is missed:  https://github.com/napi-rs/napi-rs/blob/v1/napi/src/js_values/mod.rs#L605

Because I'm hurry to release `v2` version, so I'll fix it immediately.

**Comment by Brooooooklyn** [comment]
Fixed in https://github.com/napi-rs/napi-rs/commit/5d32a54d6c2a01d7114f1eafdf86889e15efdb8f
