### ISSUE TITLE
Ability to create weak references?

### ISSUE THREAD

**Issue by devongovett** [napi-rs/napi-rs#886]
`env.create_reference` initializes the ref count to 1 by default. But sometimes it would be useful to create a weak reference, e.g. setting the ref count to 0. `node-addon-api` in C++ allows passing an initial ref count for example: https://github.com/nodejs/node-addon-api/blob/main/doc/reference.md#factory-method. Should napi-rs have an option for this, or perhaps a new method like `create_weak_reference`? It's possible by using the `sys` bindings directly, but would be nice to have a safe wrapper.

Example usecase: https://github.com/parcel-bundler/parcel-css/pull/10/commits/ee2e927d96180c2497da0142a77f1fef5ee7b7ce

**Comment by Brooooooklyn** [comment]
Closed in https://github.com/napi-rs/napi-rs/commit/12df7e0159c1f8a9d0340ece7299391f71192420
