### ISSUE TITLE
Add support for Android armv7

### ISSUE THREAD

**Issue by mohammedelsir-lab** [napi-rs/napi-rs#895]
Hi how you doing Brooooooklyn  can you add napi rs support for Android armv7 please

**Comment by Brooooooklyn** [comment]
uhhh, support android armv7 is not hard. What's your use case? I was assuming that Android armv7 devices were obsolete

**Comment by mohammedelsir-lab** [comment]
I use terminal called termux work on Android for development I work on nextjs project but swc don't because there no support for Android arm7 so I have to work with babel instead which is too slow

**Comment by mohammedelsir-lab** [comment]
I think Android armv7 is functioning  well ❤️‍🩹
