### ISSUE TITLE
Deployment must fail if a package for a platform cannot be published

### ISSUE THREAD

**Issue by kdy1** [napi-rs/napi-rs#898]
e.g. If freebsd platform package is broken, CI must fail at least on last npm publish step.

**Comment by Brooooooklyn** [comment]
@kdy1 seems like build failure in SWC FreeBSD CI is due to `npm` error. You can enable FreeBSD and retry it... And change the option `if-no-files-found`  of `actions/upload-artfacts` to `error` as a workaround: https://github.com/actions/upload-artifact#customization-if-no-files-are-found

**Comment by kdy1** [comment]
Did it, thanks!
