### ISSUE TITLE
Issue building classes for windows ia32

### ISSUE THREAD

**Issue by kyleshay** [napi-rs/napi-rs#905]
I was not able to get this example to run with ia32 (worked fine with x64 and I could build it on my mac as well.)
https://github.com/napi-rs/napi-rs/blob/main/examples/napi/src/class.rs

Even with a simple class along the lines of this. It builds fine, but even when I just call `require('./index.node')` it shuts down the program:

```rust
use napi::bindgen_prelude::*;

#[napi]
pub struct MyClass(u32);

#[napi]
impl MyClass {
    #[napi(constructor)]
    pub fn new() -> Result<Self> {
        Ok(Self(13))
    }
}
```

```toml
napi = "2.0.0-beta.2"
napi-derive = "2.0.0-beta.1"

napi-build = "1.2"
```

```json
"@napi-rs/cli": "2.0.0-beta.3"
```

_Originally posted by @kyleshay in https://github.com/napi-rs/napi-rs/issues/896#issuecomment-985769190_

**Comment by Brooooooklyn** [comment]
It works on my Windows. With rust `1.57.0` and `node 16.13.1 ia32` https://github.com/Brooooooklyn/napi-rs-win-i686-check

**Comment by Brooooooklyn** [comment]
@kyleshay Check the latest CI build. It works fine.

**Comment by kyleshay** [comment]
Interesting! Thanks so much for creating that repo - I just tried it and it worked. I diffed it against what I had and noticed that I don't have the `--release` flag passed in.

If you remove that from the build script, then you can repro the issue that I had.

**Comment by kyleshay** [comment]
@Brooooooklyn - to be specific I was using this scrip below (no `--release`)
```json
   "bundle-ia32": "napi build --platform --js false --target i686-pc-windows-msvc"
```

Just swapped to using `--release` and it works from the interactive node shell (node, then require('./') but then I'm running into the classic:

> error Command failed with exit code 3221225477.

I've added
```

[profile.release]
lto = false
codegen-units = 32
```
but same issue.

**Comment by kyleshay** [comment]
I also wanted to mention I'm specifically seeing those errors when trying to require the module in an electron app. Maybe they can be triggered other ways though?
```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
yarn
mv ~/path/index.node ./index.node
sed -i '1irequire('./index.node')' main.js
yarn start
```
If I run `node main.js` it runs fine. Is there some other configuration that needs to be done for it to be compatible with electron?

the electron-quick-start uses ^16.0.2, also tried with 13.6.3

**Comment by Brooooooklyn** [comment]
It's a known rust compiler ICE: https://github.com/rust-lang/rust/issues/67497

**Comment by Brooooooklyn** [comment]
Also tracked with https://github.com/napi-rs/napi-rs/issues/297

**Comment by kyleshay** [comment]
Thanks so much for those resources. So there is no work around for now to build classes for ia32 with --release or without --release?

Just curious, thanks so much for your help!

**Comment by Brooooooklyn** [comment]
> So there is no work around for now to build classes for ia32 with --release or without --release?

Try `$Env:CARGO_PROFILE_DEBUG_CODEGEN_UNITS=256 yarn bundle-ia32`
