### ISSUE TITLE
Finish all N-API binding

### ISSUE THREAD

**Issue by Brooooooklyn** [napi-rs/napi-rs#92]
API remains:

- [x] Enum types
- [x] napi_create_buffer_copy
- [x] napi_create_date
- [x] napi_create_typedarray
- [x] napi_create_dataview
- [x] napi_create_bigint_int64
- [x] napi_create_bigint_uint64
- [x] napi_create_bigint_words
- [x] napi_create_string_latin1
- [x] napi_get_prototype
- [x] napi_get_typedarray_info
- [ ] napi_get_dataview_info
- [x] napi_get_date_value
- [x] napi_get_value_bigint_int64
- [x] napi_get_value_bigint_uint64
- [x] napi_get_value_bigint_words
- [x] napi_get_value_string_latin1
- [x] napi_get_global
- [x] napi_instanceof
- [x] napi_is_error
- [x] napi_is_typedarray
- [x] napi_is_dataview
- [x] napi_strict_equals
- [x] napi_detach_arraybuffer
- [x] napi_is_detached_arraybuffer

**Comment by oyyd** [comment]
@Brooooooklyn I would like to implement some apis. Maybe I could start with `bigint` related apis (e.g. `napi_get_value_bigint_int64`, `napi_get_value_bigint_uint64` and `napi_get_value_bigint_words`)?

**Comment by Brooooooklyn** [comment]
@oyyd great, I would like finish https://github.com/napi-rs/napi-rs/pull/94 before anything else in https://github.com/napi-rs/napi-rs/milestone/1
