### ISSUE TITLE
Factory method on instance of class

### ISSUE THREAD

**Issue by Huntragon** [napi-rs/napi-rs#930]
I have a class that enables some cryptographic functions (lets call it Crypto). Normally you create an instance with a certain key, and that key is used to encrypt and decrypt data. However, there I need some more specific crytographic functions which need both a key and another buffer used as AAD, with the key being the same as in the original class. So my idea was to create a factory method on Crypto that takes &self and a Buffer, and returns an instance of CryptoAAD. However, when doing this I the following error: `Error: Failed to initialize class `createAadCrypto`

The following code causes this error:
```
use napi::bindgen_prelude::*;
use napi_derive::napi;

#[napi]
pub struct Crypto{
    key: Vec<u8>
}

#[napi]
pub struct AadCrypto{
    key: Vec<u8>,
    aad: Vec<u8>
}

#[napi]
impl Crypto{
    #[napi(constructor)]
    pub fn new(key: Buffer) -> Self{
        Self{key: key.to_vec()}
    }

    #[napi(js_name = "createAadCrypto", factory)]
    pub fn create_aad_crypto(&self, aad: Buffer) -> AadCrypto{
        let aad = aad.to_vec();
        AadCrypto{key: self.key.clone(), aad}
    } 
}
```

**Comment by Brooooooklyn** [comment]
1. `factory` should return `Self` or `Result<Self>`
2. `factory` should not be an methods, it should be a `associated` function

Here is preview version of v2 documentation: https://website-lynweklm.vercel.app/docs/concepts/class
