### ISSUE TITLE
[napi] add a api like drop_wrapped() but returns wrapped variables

### ISSUE THREAD

**Issue by oyyd** [napi-rs/napi-rs#932]
napi-rs has `drop_wrapped()`:

https://github.com/napi-rs/napi-rs/blob/abf99a52ce8a76a84e66d32f66b518588093e4ec/napi/src/env.rs#L874

and `unwrap()`:

https://github.com/napi-rs/napi-rs/blob/abf99a52ce8a76a84e66d32f66b518588093e4ec/napi/src/env.rs#L822

We can get the mutable references but I can't find a way to move variables out of wrappers and own them.
Maybe we could have an api similar to `drop_wrapped()` but return the wrapped variable.

**Comment by Brooooooklyn** [comment]
Does [mem::take](https://doc.rust-lang.org/std/mem/fn.take.html) or [mem::replace](https://doc.rust-lang.org/std/mem/fn.replace.html) work in your scenario?

**Comment by oyyd** [comment]
I think so if I impl Default to my struct. That's enough for me and thanks for the tips :)
