### ISSUE TITLE
Converting Buffer to Vector fails

### ISSUE THREAD

**Issue by PlainBane** [napi-rs/napi-rs#935]
Example code from [Docs](https://napi.rs/docs/concepts/values#buffer) fails to compile with error :
```
 let buf = Vec::<u8>::from(buf);
    |               ^^^^^^^^^^^^^^^ the trait `From<napi::bindgen_prelude::Buffer>` is not implemented for `Vec<u8>`
```
napi 2
rustc 1.57.0

**Comment by Brooooooklyn** [comment]
@PlainBane It was a bug in 2.0.0, you can use `let buf: Vec<u8> = buf.into();` to instead.
