### ISSUE TITLE
v2: generated js bindings only works with `--platform`

### ISSUE THREAD

**Issue by punkeel** [napi-rs/napi-rs#936]
The generated JS bindings file at `index.js` only supports building with `--platform`. I'm not sure it's realistic to support other scenarios (in my case, I'm always building `index.node` and using a simple `require('./index.node')`).

From what I could dig, the template is here -- and indeed isn't conditional on `--platform`.
https://github.com/napi-rs/napi-rs/blob/f4b0a2e3228eb9d6d2c8f51e31d250930799ce1d/cli/src/js-binding-template.ts

**Comment by Brooooooklyn** [comment]
You can disable the js binding file generation by pass `--js false` to `build` command. I'll disable the `--js` by default if no `--platform` flag provided.
