### ISSUE TITLE
[Feature] v2: allow disabling `.d.ts` generation

### ISSUE THREAD

**Issue by punkeel** [napi-rs/napi-rs#937]
With v2, the `.d.ts` files are now auto-generated on build. Would it be acceptable to add an option to disable this? ie `--dts=false`, similar to `--js=false`?

**Comment by yisibl** [comment]
The `--dts` option is already available, and can be flexibly configured in package.json if not needed.

` "build": "napi build --platform --release --js js-binding.js --dts js-binding.d.ts",`

**Comment by punkeel** [comment]
`--dts` exists but `--dts=false` still creates a file named `false` (whereas `--js=false` [disables](https://github.com/napi-rs/napi-rs/blob/f4b0a2e3228eb9d6d2c8f51e31d250930799ce1d/cli/src/build.ts#L302) creating the `.js` file).

**Comment by Brooooooklyn** [comment]
@punkeel you can disable `type-def` feature in `napi-derive` crate to disable the `.d.ts` generation.

```toml
napi-derive = {default-features=false, version = "2"}
```
