### ISSUE TITLE
Addon functions become undefined when addon is also required in a `worker_thread`

### ISSUE THREAD

**Issue by dguenther** [napi-rs/napi-rs#943]
It appears that when a `napi-rs` 2.0 module is required both on the main thread and in a `worker_thread`, exported functions can become undefined. I originally saw [this issue](https://github.com/Brooooooklyn/blake-hash/issues/29) in blake-hash, and found a reproduction case that I've tested on `package-template` and `@node-rs/xxhash` as well.

I also tested the same reproduction case with `@node-rs/xxhash` v1.0.1 and the issue doesn't reproduce -- it works as expected on that version.

## Reproduction case

Using commit [`d6bb01d`](https://github.com/napi-rs/package-template/commit/d6bb01d6b0610ec13544bda1e009ec71490b9cde) from `main` branch of `package-template`:

```js
const { Worker, isMainThread } = require('worker_threads')

// When testing, replace with path to a local build of package-template
const template = require('/Users/dguenther/repos/package-template')

if (isMainThread) {
    console.log('outside worker')
    new Worker(__filename)
} else {
    console.log('inside worker')
}

console.log(template)
if (template.plus100) {
    console.log(template.plus100(0))
}
```

Logs from running the reproduction case:

```
outside worker
{ plus100: [Function: plus100] }
100
inside worker
{ plus100: undefined }
```

**Comment by Brooooooklyn** [comment]
Related: https://github.com/Brooooooklyn/blake-hash/issues/29

**Comment by Brooooooklyn** [comment]
Ref: https://github.com/nodejs/node/issues/41243

**Comment by devongovett** [comment]
Just came across this as well. Parcel depends heavily on worker_threads. What is the reason to use a dynamic library constructor rather than napi's init function?

**Comment by Brooooooklyn** [comment]
As you see, NAPI-RS v2 doesn't need the `#[module_exports]` or `#[init]` to initialize the native module. So we need to pre-collect the function/class/const/enum to exports in the `__attribute((constructor))` via the `proc_macro`: https://github.com/napi-rs/napi-rs/blob/main/crates/backend/src/codegen/fn.rs#L332. And initialize them in the `napi_init` function

**Comment by devongovett** [comment]
I'm pretty sure it needs to run once per thread though (each worker thread is a separate v8 isolate), and the constructor will only be invoked once (on whatever thread loads the native module first). Perhaps the #[module_exports] function can be generated by the macro?

**Comment by Brooooooklyn** [comment]
> Perhaps the #[module_exports] function can be generated by the macro?

I've considered this solution, but `proc_macro` don't have the API for something like **This is the last `#[napi]` macro, I can generate the `extern "C" napi_register_module_v1`** here.

Seems like we need to find some other workaround for this situation.

**Comment by devongovett** [comment]
Perhaps you could do it the opposite way, i.e. generate that function the _first_ time the `#[napi]` macro is called. I guess you'd have to track it per crate, maybe using the `CARGO_CRATE_NAME` environment variable or something? https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

Then, you could generate a static variable in the output code to hold references to all the initializer functions, and push them inside constructor functions.

Pseudo code:

```rust
static mut register_fns: Vec<???> = Vec::new();

fn some_fn_generated_by_napi(...) {
  // ...
}

fn register_some_fn(env: napi_env, exports: napi_value) {
  register_module_export(exports, "some_fn", some_fn_generated_by_napi);
}

__attribute((constructor))
fn some_constructor() {
  register_fns.push(register_some_fn);
}

// Only generated the first time #[napi] is called (per crate?)
fn napi_register_module_v1(env: napi_env, exports: napi_value) {
  for register_fn in register_fns) {
    register_fn(env, exports);
  }
}
```

Of course, I haven't tried this, so maybe it won't work. 😄

**Comment by Brooooooklyn** [comment]
@devongovett Thank you for the warm tips. I've fixed it via some `Rust` dark magic.

**Comment by devongovett** [comment]
Whoa fancy. Nice work! 😄
