### ISSUE TITLE
LSP autocomplete useless with napi macros

### ISSUE THREAD

**Issue by mischnic** [napi-rs/napi-rs#944]
I can see how/why this happened, but from a user's perspective autocomplete being broken inside of constructs using the napi macro is very frustrating. 

![Bildschirmfoto 2021-12-18 um 12 25 39](https://user-images.githubusercontent.com/4586894/146639234-f73e7461-69ee-416e-9ad0-822ae94bf434.png)

![Bildschirmfoto 2021-12-18 um 12 25 51](https://user-images.githubusercontent.com/4586894/146639238-d14c228c-c014-4db8-8414-a24f536fb6d7.png)

**Comment by sam3d** [comment]
I've been able to fix this this (in rust-analyzer) by disabling proc attr macro support:

![image](https://user-images.githubusercontent.com/8385528/146649030-4bf971eb-3195-41cc-b3c9-0a6d725031af.png)

**Comment by numToStr** [comment]
With `rust-analyzer 2022-01-10`, you can also do the following to ignore the `napi` macro.

- **VSCode**
```json
"rust-analyzer.procMacro.ignored": { "napi-derive": ["napi"] }
```

- **Neovim**
```lua
['rust-analyzer'] = {
    procMacro = {
        ignored = {
            ['napi-derive'] = { 'napi' },
        },
    },
},
```

**Comment by oyyd** [comment]
Sorry for my mis-operation that unpin this issue..

**Comment by BB-fat** [comment]
@numToStr Do you know how to solve this problem in RustHover?

**Comment by GavTheGreat1** [comment]
['rust-analyzer'] = {
    procMacro = {
        ignored = {
            ['napi-derive'] = ["napi"] } },
        },
    },
},

**Comment by eric-gitta-moore** [comment]
> @numToStr Do you know how to solve this problem in RustRover?

Also looking for a solution in RustRover

**Comment by dalisoft** [comment]
@numToStr solution worked in VSCode. Thank you

**Comment by Qard** [comment]
This doesn't seem to be a useful solution anymore as instead of just highlighting the struct name in red, it now highlights _the entire impl_ in yellow with a warning message of `napi: proc-macro is explicitly disabled (rust-analyzer proc-macro-disabled)`, making things even _less_ readable. 😐

**Comment by pipex** [comment]
@Qard I got rid of the diagnostic with this configuration on my nvim. Got it from here https://users.rust-lang.org/t/how-to-disable-rust-analyzer-proc-macro-warnings-in-neovim/53150

```
rust_analyzer = {
        settings = {
          ["rust-analyzer"] = {
            cargo = {
              allFeatures = true,
            },
            procMacro = {
              enabled = true,
              ignored = {
                ["napi-derive"] = { "napi" },
              },
            },
            diagnostics = {
              enable = true,
              disabled = { "unresolved-proc-macro" },
              enableExperimental = true,
            },
          },
        },
      },
```

**Comment by pipex** [comment]
Actually it doesn't seem like it's working yet for me

**Comment by LeMikaelF** [comment]
@pipex you just had the wrong disabled diagnostic! I got it working with your suggestion and `proc-macro-disabled`. 

Actually, all that's needed is this:

```lua
procMacro = {
  ignored = {
    ['napi-derive'] = { 'napi' },
  },
},
diagnostics = {
  disabled = { 'proc-macro-disabled' },
},

```

**Comment by BadMachine** [comment]
> Actually it doesn't seem like it's working yet for me

Same here
