### ISSUE TITLE
Object with methods

### ISSUE THREAD

**Issue by probablykasper** [napi-rs/napi-rs#962]
I'd like to use the `#[napi]` macro for my methods, but I'm a bit confused about how I should do this.

The docs say that `Unlike Class you can't assign function or method to Object.` I'd like to have a JsObject with methods, like I do now in v1. Is that not possible when using the `#[napi]` macro?

Also, as far as I understand, when you have a `#[napi]` function, it's automatically exported. Is there any way around that for creating object methods?

I currently have this code for napi v1:
```rust
#[module_exports]
fn init(mut exports: JsObject) -> napi::Result<()> {
  exports.create_named_method("method1", method1)?;
  // etc
  exports.create_named_method("load_data", load_data)?;
  Ok(())
}

#[js_function(0)]
pub fn load_data_js(ctx: CallContext) -> NResult<JsObject> {
  let data: Data = load_data(&is_dev)?;
  let mut new_this: JsObject = ctx.env.create_object()?;
  ctx.env.wrap(&mut new_this, data)?;
  new_this = init_data_instance(new_this)?;
  return Ok(new_this);
}

fn init_data_instance(mut exports: JsObject) -> NResult<JsObject> {
  exports.create_named_method("method1", method1)?;
  // etc
  Ok(exports)
}
```

**Comment by Brooooooklyn** [comment]
Hey @probablykasper 

`#[napi(object)]` in V2 can only represent a pure Object which doesn't contain any method on it.

If you want to create `Object` with methods, you can use the `low-level` API:

```rust
/// the same with NAPI-RS v1
#[js_function]
fn xxx {}

#[napi]
fn create_object_with_method(env: Env) -> Result<JsObject> {
   let object = env.create_object()?;
   ....
}
```

**Comment by probablykasper** [comment]
Ah, that's unfortunate. Would love to be able to something like this:
```rust
#[module_exports]
fn init(mut exports: JsObject) -> napi::Result<()> {
  exports.create_named_method("doStuff", do_stuff)?;
  Ok(())
}

#[js_function]
fn do_stuff(arg1: u32, arg2: u32) -> SomeSerializableObject {
  // ...
}
```

Could this be issue be considered a feature request?

**Comment by Brooooooklyn** [comment]
@probablykasper you can return another **class instance** after https://github.com/napi-rs/napi-rs/pull/964 released :

```rust
#[napi(constructor)]
struct Foo {
  name: String,
}

#[napi]
impl Foo {
  #[napi]
  pub fn bar(&self) -> String {
    "bar".to_owned()
  }
}


#[napi]
fn load_foo() -> Foo {
  Foo { name: "f".to_owned() }
}
```
