### ISSUE TITLE
module_exports macro is broken in napi-rs@2

### ISSUE THREAD

**Issue by hardfist** [napi-rs/napi-rs#972]
I run the compat mode according to the doc https://napi.rs/docs/compat-mode/recipes/registering-module.
```rust
#[macro_use]
extern crate napi_derive;

use napi::*;

#[module_exports]
fn init(mut exports: JsObject) -> Result<()> {
  exports.create_named_method("hello", hello)?;

  Ok(())
}

#[js_function]
fn hello(ctx: CallContext) -> Result<JsString> {
  todo!()
}
```
but it compiles with the following error
![image](https://user-images.githubusercontent.com/8898718/147388788-89f6c335-53a7-4d31-a67c-7d63e28e15c6.png)

**Comment by Brooooooklyn** [comment]
`compat-mode` feature need to be enabled when you want to use `v1` macros.
