### ISSUE TITLE
`&str` is not working as intended

### ISSUE THREAD

**Issue by h-a-n-a** [napi-rs/napi-rs#973]
This issue is mainly about a mis-matched behavior between `&'static str` and `String` type ported to Node side. For `&str`, the value returned to JS type is broken without a compile time error, and which would not be compiled successfully with single `&str` on the param of a function. For more detail, please refer to this repro repo.

https://github.com/h-a-n-a/issue_1223_napi_rs_str

**Comment by Brooooooklyn** [comment]
Fixed in https://github.com/napi-rs/napi-rs/pull/1023
