### ISSUE TITLE
Keys in structs which have a napi(js_name="containing.special+characters") should be string quoted in defintions file.

### ISSUE THREAD

**Issue by Half-Shot** [napi-rs/napi-rs#986]
E.g.

```rust
#[napi(object)]
pub struct JiraIssueMessageBody {
    #[napi(js_name = "uk.half-shot.matrix-hookshot.jira.issue")]
    pub jira_issue: JiraIssueSimpleItem,
}
```

Currently gets translated to the following in the `lib.d.ts` file.

```ts
export interface JiraIssueMessageBody {
  uk.half-shot.matrix-hookshot.jira.issue: JiraIssueSimpleItem
}
```

**Comment by Brooooooklyn** [comment]
It's hard to determine whether to add quotes around the interface key.

You can rename your TypeScript type as: `#[napi(js_name = "'uk.half-shot.matrix-hookshot.jira.issue'")]`

**Comment by Half-Shot** [comment]
That seems to cause the actual key name to become `'uk.half-shot.matrix-hookshot.jira.issue'` in the code itself, rather than `'uk.half-shot.matrix-hookshot.jira.issue`.
