### ISSUE TITLE
New project created with @napi-rs/cli doesn't create .cargo dir, .js, .d.ts files

### ISSUE THREAD

**Issue by AlCalzone** [napi-rs/napi-rs#988]
I tried to follow the getting started guide at https://napi.rs/docs/introduction/simple-package but I'm getting stuck pretty early. According to the documentation, the generated directory should contain a `.cargo` directory and building should generate `index.js` and `index.d.ts` files in the root. Neither happens for me.

Even after changing the build commands to
```
    "build": "napi build --platform --release --js index.js --dts index.d.ts",
    "build:debug": "napi build --platform --js index.js --dts index.d.ts",
```
`yarn build` does not generate these files.

What might I be missing?

**Comment by Brooooooklyn** [comment]
@AlCalzone did you install the latest `@napi-rs/cli` in global?

**Comment by AlCalzone** [comment]
Yeah, I did. Just minutes before I tried that.

**Comment by JMLX42** [comment]
@AlCalzone what version of `yarn` are you using?

Running `yarn run build` with yarn 1.22.17 properly creates the `index.d.ts` and `index.js` files. But with yarn 3.2.0 the files are *not* generated and there is an error in the console:

```
Failed to write type def file: Os { code: 20, kind: NotADirectory, message: "Not a directory" }
```

**Comment by Brooooooklyn** [comment]
@JMLX42 Do you have the pnp feature enabled?

**Comment by JMLX42** [comment]
> Do you have the pnp feature enabled?

@Brooooooklyn how can I check that? What is the recommended config?

**Comment by JMLX42** [comment]
I have the following in my `.yarnrc.yml`:

```
nodeLinker: node-modules
```

Which AFAIK means PNP is disabled. Is that what napi expects?

**Comment by AlCalzone** [comment]
> what version of `yarn` are you using?

I didn't change anything from the template. It also seemed to work on another project, so I'm at a loss what was wrong there.

**Comment by Brooooooklyn** [comment]
Close in https://github.com/napi-rs/napi-rs/pull/1492
